from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')

start=s.index('let warehouseRemoteReady=')
end=s.index('const id=()=>', start)

block=r'''let warehouseRemoteReady=false,warehouseRemoteRevision=0,warehouseRemoteUpdatedAt=0,warehouseSaveTimer=null,warehouseSaveInFlight=false,warehousePullInFlight=false,warehouseWatchStarted=false;
const WAREHOUSE_DIRTY_KEY=KEY+'_cloud_dirty_v2',WAREHOUSE_MIGRATION_KEY=KEY+'_cloud_sync_v2_migrated';
let warehouseLocalDirty=localStorage.getItem(WAREHOUSE_DIRTY_KEY)==='1',warehouseLastCloudSnapshot=null,warehouseLastSyncedText='',warehouseLastObservedSnapshot=null;
const WAREHOUSE_ARRAY_FIELDS=['products','movements','sales','purchases','reservations','kaspiAdExpenses'];
const WAREHOUSE_VOLATILE_SETTINGS=new Set(['serverMarketStatus','d1WarehouseRevision','d1WarehouseUpdatedAt','d1MigratedAt','localWarehouseUpdatedAt','activeView','selectedOrderMarket','selectedWbAccount','orderPeriodMode','orderCustomFrom','orderCustomTo','reportPeriodPreset','reportPeriod','selectedPeriodPreset','selectedPeriod','unmatchedOrderFilter']);
function cloudStatus(text,mode=''){const el=document.getElementById('cloudStatus');if(!el)return;el.textContent=text;el.style.color=mode==='bad'?'var(--bad)':mode==='warn'?'var(--warn)':mode==='ok'?'var(--ok)':''}
function warehouseSnapshot(){const settings={...(state.settings||{})};for(const k of WAREHOUSE_VOLATILE_SETTINGS)delete settings[k];return {products:state.products||[],movements:state.movements||[],sales:state.sales||[],purchases:state.purchases||[],reservations:state.reservations||[],kaspiAdExpenses:state.kaspiAdExpenses||[],settings,marketOrderState:state.marketOrderState||{},marketplaceLiveSince:state.marketplaceLiveSince||{},kaspiBaselineAt:state.kaspiBaselineAt||null}}
function normalizeWarehouseSnapshot(x){x=x&&typeof x==='object'?x:{};return {products:Array.isArray(x.products)?x.products:[],movements:Array.isArray(x.movements)?x.movements.filter(m=>!['резерв','отмена резерва'].includes(String(m?.type||''))):[],sales:Array.isArray(x.sales)?x.sales:[],purchases:Array.isArray(x.purchases)?x.purchases:[],reservations:Array.isArray(x.reservations)?x.reservations:[],kaspiAdExpenses:Array.isArray(x.kaspiAdExpenses)?x.kaspiAdExpenses:[],settings:x.settings&&typeof x.settings==='object'?x.settings:{},marketOrderState:x.marketOrderState&&typeof x.marketOrderState==='object'?x.marketOrderState:{},marketplaceLiveSince:x.marketplaceLiveSince&&typeof x.marketplaceLiveSince==='object'?x.marketplaceLiveSince:{},kaspiBaselineAt:x.kaspiBaselineAt||null}}
function hasWarehouseData(x){return !!((x?.products?.length||0)+(x?.purchases?.length||0)+(x?.sales?.length||0)+(x?.movements?.length||0)+(x?.reservations?.length||0))}
function warehouseKey(field,x){if(!x)return'';if(field==='sales')return String(x.externalKey||x.id||'');if(field==='reservations')return String((x.source||'')+'|'+(x.externalKey||x.id||''));if(field==='kaspiAdExpenses')return String(x.id||x.importId||[x.date,x.day,x.productId,x.sku,x.amount].join('|'));return String(x.id||'')}
function jsonSame(a,b){return JSON.stringify(a??null)===JSON.stringify(b??null)}
function itemVersion(x){return Math.max(0,Number(x?._syncUpdatedAt||0),Number(x?.updatedAt||0),Number(x?.receivedAt||0),Number(x?.date||0),Number(x?.createdAt||0))}
function mergeArray3(field,base,remote,local,remoteUpdated,localUpdated){const bm=new Map((base||[]).map(x=>[warehouseKey(field,x),x]).filter(x=>x[0])),rm=new Map((remote||[]).map(x=>[warehouseKey(field,x),x]).filter(x=>x[0])),lm=new Map((local||[]).map(x=>[warehouseKey(field,x),x]).filter(x=>x[0])),keys=new Set([...bm.keys(),...rm.keys(),...lm.keys()]),out=[];for(const k of keys){const b=bm.get(k),r=rm.get(k),l=lm.get(k);if(!b){if(r&&!l)out.push(r);else if(l&&!r)out.push(l);else if(r&&l)out.push(itemVersion(l)>itemVersion(r)?l:itemVersion(r)>itemVersion(l)?r:(localUpdated>remoteUpdated?l:r));continue}if(!l&&r){if(jsonSame(r,b))continue;out.push(r);continue}if(!r&&l){if(jsonSame(l,b))continue;out.push(l);continue}if(!l&&!r)continue;if(jsonSame(l,b)){out.push(r);continue}if(jsonSame(r,b)){out.push(l);continue}out.push(itemVersion(l)>itemVersion(r)?l:itemVersion(r)>itemVersion(l)?r:(localUpdated>remoteUpdated?l:r))}return out}
function mergeObject3(base,remote,local,remoteUpdated,localUpdated){base=base&&typeof base==='object'?base:{};remote=remote&&typeof remote==='object'?remote:{};local=local&&typeof local==='object'?local:{};const out={},keys=new Set([...Object.keys(base),...Object.keys(remote),...Object.keys(local)]);for(const k of keys){const b=base[k],r=remote[k],l=local[k];if(jsonSame(l,b)){if(r!==undefined)out[k]=r;continue}if(jsonSame(r,b)){if(l!==undefined)out[k]=l;continue}if(l===undefined){if(r!==undefined)out[k]=r;continue}if(r===undefined){out[k]=l;continue}if(l&&r&&typeof l==='object'&&typeof r==='object'&&!Array.isArray(l)&&!Array.isArray(r))out[k]=mergeObject3(b,r,l,remoteUpdated,localUpdated);else out[k]=localUpdated>remoteUpdated?l:r}return out}
function mergeWarehouseSnapshots(base,remote,local,remoteUpdated=0,localUpdated=0){base=normalizeWarehouseSnapshot(base);remote=normalizeWarehouseSnapshot(remote);local=normalizeWarehouseSnapshot(local);const out={};for(const f of WAREHOUSE_ARRAY_FIELDS)out[f]=mergeArray3(f,base[f],remote[f],local[f],remoteUpdated,localUpdated);out.settings=mergeObject3(base.settings,remote.settings,local.settings,remoteUpdated,localUpdated);out.marketOrderState=mergeObject3(base.marketOrderState,remote.marketOrderState,local.marketOrderState,remoteUpdated,localUpdated);out.marketplaceLiveSince=mergeObject3(base.marketplaceLiveSince,remote.marketplaceLiveSince,local.marketplaceLiveSince,remoteUpdated,localUpdated);const times=[Number(remote.kaspiBaselineAt||0),Number(local.kaspiBaselineAt||0)].filter(Boolean);out.kaspiBaselineAt=times.length?Math.min(...times):null;return out}
function stripSyncStamp(x){if(!x||typeof x!=='object')return x;const y={...x};delete y._syncUpdatedAt;return y}
function stampChangedWarehouseEntities(){const prev=warehouseLastObservedSnapshot;if(!prev)return;const now=Date.now();for(const field of WAREHOUSE_ARRAY_FIELDS){const oldMap=new Map((prev[field]||[]).map(x=>[warehouseKey(field,x),x]));for(const item of(state[field]||[])){const key=warehouseKey(field,item),old=oldMap.get(key);if(!old||!jsonSame(stripSyncStamp(old),stripSyncStamp(item)))item._syncUpdatedAt=now}}}
function applyWarehouseSnapshot(remote){const snap=normalizeWarehouseSnapshot(remote),feeds={kaspiOrderFeed:state.kaspiOrderFeed||[],wbOrderFeed:state.wbOrderFeed||[],ozonOrderFeed:state.ozonOrderFeed||[],kaspiOrders:state.kaspiOrders||{}},localSettings={...(state.settings||{})};state={...state,...snap,...feeds};state.reservations=Array.isArray(state.reservations)?state.reservations:[];state.kaspiAdExpenses=Array.isArray(state.kaspiAdExpenses)?state.kaspiAdExpenses:[];state.settings={...snap.settings,...localSettings};state.purchases.forEach(x=>{x.status=['to_forwarder','to_me','at_warehouse','received'].includes(String(x.status||''))?String(x.status):'received';if(x.status==='received'){x.receivedAt=Number(x.receivedAt||x.date)||Date.now();x.remainingQty=Number.isFinite(Number(x.remainingQty))?Math.max(0,Number(x.remainingQty)):Math.max(0,Number(x.qty)||0);x.landedUnitCost=Number(x.landedUnitCost)||((Number(x.unitCost)||0)+((Number(x.delivery)||0)/(Math.max(1,Number(x.qty)||1))))}else{x.receivedAt=Number(x.receivedAt)||0;x.remainingQty=0;x.landedUnitCost=Number(x.landedUnitCost)||0}});warehouseLastObservedSnapshot=normalizeWarehouseSnapshot(warehouseSnapshot())}
function markWarehouseDirty(){warehouseLocalDirty=true;localStorage.setItem(WAREHOUSE_DIRTY_KEY,'1');cloudStatus('есть изменения','warn')}
function clearWarehouseDirty(){warehouseLocalDirty=false;localStorage.removeItem(WAREHOUSE_DIRTY_KEY)}
function scheduleWarehouseSave(delay=700){if(!warehouseRemoteReady)return;clearTimeout(warehouseSaveTimer);warehouseSaveTimer=setTimeout(()=>pushWarehouseToD1().catch(e=>{console.warn('D1 warehouse save failed',e);cloudStatus('ошибка сохранения','bad')}),delay)}
function save(){stampChangedWarehouseEntities();state.settings.localWarehouseUpdatedAt=Date.now();saveLocalOnly();const snap=normalizeWarehouseSnapshot(warehouseSnapshot()),text=JSON.stringify(snap);warehouseLastObservedSnapshot=snap;if(text!==warehouseLastSyncedText){markWarehouseDirty();scheduleWarehouseSave()}}
async function fetchWarehouseCloud(){const r=await fetch(MILLIONER_API+'/api/warehouse-state',{cache:'no-store'});let data={};try{data=await r.json()}catch{}if(!r.ok||data.ok===false)throw new Error(data.error||('HTTP '+r.status));return data}
async function pushWarehouseToD1(){if(!warehouseRemoteReady||warehouseSaveInFlight||!warehouseLocalDirty)return false;warehouseSaveInFlight=true;cloudStatus('сохраняю…','warn');try{for(let attempt=0;attempt<3;attempt++){const localSnap=normalizeWarehouseSnapshot(warehouseSnapshot()),sentText=JSON.stringify(localSnap),r=await fetch(MILLIONER_API+'/api/warehouse-state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseRevision:warehouseRemoteRevision,state:localSnap})});let data={};try{data=await r.json()}catch{}if(r.status===409){const remoteData=await fetchWarehouseCloud();const remoteSnap=normalizeWarehouseSnapshot(remoteData.state),localUpdated=Number(state.settings.localWarehouseUpdatedAt||Date.now()),merged=mergeWarehouseSnapshots(warehouseLastCloudSnapshot,remoteSnap,localSnap,Number(remoteData.updatedAt||0),localUpdated);warehouseRemoteRevision=Number(remoteData.revision||0);warehouseRemoteUpdatedAt=Number(remoteData.updatedAt||0);warehouseLastCloudSnapshot=remoteSnap;warehouseLastSyncedText=JSON.stringify(remoteSnap);applyWarehouseSnapshot(merged);saveLocalOnly();markWarehouseDirty();continue}if(!r.ok||data.ok===false)throw new Error(data.error||('HTTP '+r.status));warehouseRemoteRevision=Number(data.revision||warehouseRemoteRevision);warehouseRemoteUpdatedAt=Number(data.updatedAt||Date.now());warehouseLastCloudSnapshot=localSnap;warehouseLastSyncedText=sentText;state.settings.d1WarehouseRevision=warehouseRemoteRevision;state.settings.d1WarehouseUpdatedAt=warehouseRemoteUpdatedAt;state.settings.d1MigratedAt=state.settings.d1MigratedAt||Date.now();saveLocalOnly();const currentText=JSON.stringify(normalizeWarehouseSnapshot(warehouseSnapshot()));if(currentText===sentText){clearWarehouseDirty();cloudStatus('синхронизировано','ok')}else{markWarehouseDirty();scheduleWarehouseSave(100)}return true}throw new Error('Не удалось разрешить конфликт версий')}finally{warehouseSaveInFlight=false}}
async function pullWarehouseFromD1({force=false}={}){if(warehousePullInFlight||warehouseSaveInFlight)return false;if(!navigator.onLine){cloudStatus('офлайн','warn');return false}warehousePullInFlight=true;if(force)cloudStatus('проверяю…','warn');try{const data=await fetchWarehouseCloud();if(!data.exists){warehouseRemoteRevision=0;warehouseRemoteUpdatedAt=0;warehouseRemoteReady=true;warehouseLastCloudSnapshot=normalizeWarehouseSnapshot({});warehouseLastSyncedText=JSON.stringify(warehouseLastCloudSnapshot);markWarehouseDirty();await pushWarehouseToD1();return true}const remoteRevision=Number(data.revision||0),remoteUpdated=Number(data.updatedAt||0),remoteSnap=normalizeWarehouseSnapshot(data.state);if(!warehouseRemoteReady){warehouseRemoteRevision=remoteRevision;warehouseRemoteUpdatedAt=remoteUpdated;warehouseRemoteReady=true;warehouseLastCloudSnapshot=remoteSnap;warehouseLastSyncedText=JSON.stringify(remoteSnap)}if(remoteRevision>warehouseRemoteRevision||force){if(warehouseLocalDirty){const merged=mergeWarehouseSnapshots(warehouseLastCloudSnapshot,remoteSnap,warehouseSnapshot(),remoteUpdated,Number(state.settings.localWarehouseUpdatedAt||0));warehouseRemoteRevision=remoteRevision;warehouseRemoteUpdatedAt=remoteUpdated;warehouseLastCloudSnapshot=remoteSnap;warehouseLastSyncedText=JSON.stringify(remoteSnap);applyWarehouseSnapshot(merged);saveLocalOnly();markWarehouseDirty();await pushWarehouseToD1()}else{warehouseRemoteRevision=remoteRevision;warehouseRemoteUpdatedAt=remoteUpdated;warehouseLastCloudSnapshot=remoteSnap;warehouseLastSyncedText=JSON.stringify(remoteSnap);applyWarehouseSnapshot(remoteSnap);clearWarehouseDirty();state.settings.d1WarehouseRevision=remoteRevision;state.settings.d1WarehouseUpdatedAt=remoteUpdated;saveLocalOnly();render();cloudStatus('синхронизировано','ok')}}else cloudStatus(warehouseLocalDirty?'есть изменения':'синхронизировано',warehouseLocalDirty?'warn':'ok');return true}catch(e){console.warn('D1 warehouse pull failed',e);cloudStatus('ошибка/офлайн','bad');return false}finally{warehousePullInFlight=false}}
async function bootstrapWarehouseD1(){const rawLocal=localStorage.getItem(KEY);if(rawLocal&&!localStorage.getItem(KEY+'_pre_d1'))localStorage.setItem(KEY+'_pre_d1',rawLocal);if(rawLocal&&!localStorage.getItem(KEY+'_pre_cloud_v2'))localStorage.setItem(KEY+'_pre_cloud_v2',rawLocal);const localSnap=normalizeWarehouseSnapshot(warehouseSnapshot()),localUpdated=Number(state.settings.localWarehouseUpdatedAt||0);cloudStatus('подключение…','warn');try{const data=await fetchWarehouseCloud();warehouseRemoteRevision=Number(data.revision||0);warehouseRemoteUpdatedAt=Number(data.updatedAt||0);warehouseRemoteReady=true;if(!data.exists){warehouseLastCloudSnapshot=normalizeWarehouseSnapshot({});warehouseLastSyncedText=JSON.stringify(warehouseLastCloudSnapshot);markWarehouseDirty();await pushWarehouseToD1();localStorage.setItem(WAREHOUSE_MIGRATION_KEY,'1');return {mode:'uploaded-local'}}const remoteSnap=normalizeWarehouseSnapshot(data.state);warehouseLastCloudSnapshot=remoteSnap;warehouseLastSyncedText=JSON.stringify(remoteSnap);const firstV2=localStorage.getItem(WAREHOUSE_MIGRATION_KEY)!=='1';if(firstV2){const merged=mergeWarehouseSnapshots(null,remoteSnap,localSnap,warehouseRemoteUpdatedAt,localUpdated);applyWarehouseSnapshot(merged);saveLocalOnly();markWarehouseDirty();await pushWarehouseToD1();localStorage.setItem(WAREHOUSE_MIGRATION_KEY,'1');render();return {mode:'migrated-merged'}}if(warehouseLocalDirty){const merged=mergeWarehouseSnapshots(warehouseLastCloudSnapshot,remoteSnap,localSnap,warehouseRemoteUpdatedAt,localUpdated);applyWarehouseSnapshot(merged);saveLocalOnly();markWarehouseDirty();await pushWarehouseToD1();render();return {mode:'merged-dirty'}}applyWarehouseSnapshot(remoteSnap);clearWarehouseDirty();state.settings.d1WarehouseRevision=warehouseRemoteRevision;state.settings.d1WarehouseUpdatedAt=warehouseRemoteUpdatedAt;state.settings.d1MigratedAt=state.settings.d1MigratedAt||Date.now();saveLocalOnly();render();cloudStatus('синхронизировано','ok');return {mode:'loaded-d1'}}catch(e){warehouseRemoteReady=false;console.warn('D1 warehouse bootstrap failed; keeping local data',e);cloudStatus('офлайн — локальная копия','warn');return {mode:'local-fallback',error:String(e.message||e)}}}
function startWarehouseCloudWatcher(){if(warehouseWatchStarted)return;warehouseWatchStarted=true;setInterval(()=>pullWarehouseFromD1(),15000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')pullWarehouseFromD1({force:true})});window.addEventListener('focus',()=>pullWarehouseFromD1({force:true}));window.addEventListener('online',()=>pullWarehouseFromD1({force:true}));window.addEventListener('beforeunload',()=>{if(warehouseLocalDirty)try{navigator.sendBeacon&&navigator.sendBeacon(MILLIONER_API+'/api/warehouse-state-beacon','')}catch{}})}
'''

s=s[:start]+block+s[end:]

old_header='<div class="sync"><span id="dotKaspi" class="dot warn"></span>Kaspi · последняя синхронизация: <span id="lastSync">—</span></div>'
new_header='<div class="sync"><span id="dotKaspi" class="dot warn"></span>Kaspi · последняя синхронизация: <span id="lastSync">—</span> · облако: <span id="cloudStatus">подключение…</span></div>'
if old_header in s:
    s=s.replace(old_header,new_header,1)
elif 'id="cloudStatus"' not in s:
    raise SystemExit('header sync marker not found')

old_boot='bootstrapWarehouseD1().finally(()=>loadSharedOrderCache({silent:true}));setTimeout(()=>maybeAutoGoogleBackup(),2500);setInterval(()=>loadSharedOrderCache({silent:true}),300000);setInterval(()=>maybeAutoGoogleBackup(),60*60*1000);'
new_boot='bootstrapWarehouseD1().finally(()=>{startWarehouseCloudWatcher();return loadSharedOrderCache({silent:true})});setTimeout(()=>maybeAutoGoogleBackup(),2500);setInterval(()=>loadSharedOrderCache({silent:true}),300000);setInterval(()=>maybeAutoGoogleBackup(),60*60*1000);'
if old_boot in s:
    s=s.replace(old_boot,new_boot,1)
elif 'startWarehouseCloudWatcher()' not in s.split('</script>')[-2]:
    raise SystemExit('bootstrap marker not found')

p.write_text(s,encoding='utf-8')
print('live D1 warehouse sync patched')
