from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
old="""function purchaseDemandQty(p,days=PURCHASE_COVER_DAYS){if(!p||isBundleProduct(p))return 0;const n=Math.max(1,Number(days)||PURCHASE_COVER_DAYS),since=reportPeriodStart(n),until=reportPeriodEnd(n);return financialSales().filter(x=>Number(x.date)>=since&&Number(x.date)<until).reduce((sum,sale)=>{const qty=Math.max(0,Number(sale.qty)||0);if(String(sale.productId)===String(p.id))return sum+qty;const soldProduct=prod(sale.productId);if(!isBundleProduct(soldProduct))return sum;const part=bundleComponents(soldProduct).find(x=>String(x.productId)===String(p.id));return sum+(part?qty*part.qty:0)},0)}"""
new="""function purchaseDemandQty(p,days=PURCHASE_COVER_DAYS){if(!p||isBundleProduct(p))return 0;const n=Math.max(1,Number(days)||PURCHASE_COVER_DAYS),since=reportPeriodStart(n),until=reportPeriodEnd(n),feeds=[...(state.kaspiOrderFeed||[]),...(state.wbOrderFeed||[]),...(state.ozonOrderFeed||[])];let total=0;for(const o of feeds){const market=String(o.market||((state.kaspiOrderFeed||[]).includes(o)?'Kaspi':(state.wbOrderFeed||[]).includes(o)?'WB':'Ozon')),date=Number(o.creationDate)||0;if(!(date>=since&&date<until)||marketplaceLifecycleStage(market,o.status,o.state)==='cancelled')continue;const qty=Math.max(0,Number(o.qty)||0);if(!qty)continue;if(String(o.productId||'')===String(p.id)){total+=qty;continue}const orderedProduct=prod(o.productId);if(!isBundleProduct(orderedProduct))continue;const part=bundleComponents(orderedProduct).find(x=>String(x.productId)===String(p.id));if(part)total+=qty*part.qty}for(const sale of(state.sales||[])){if(['Kaspi','WB','WB2','Ozon'].includes(String(sale.channel||'')))continue;const date=Number(sale.date)||0;if(!(date>=since&&date<until))continue;const qty=Math.max(0,Number(sale.qty)||0);if(String(sale.productId)===String(p.id))total+=qty;else{const soldProduct=prod(sale.productId);if(isBundleProduct(soldProduct)){const part=bundleComponents(soldProduct).find(x=>String(x.productId)===String(p.id));if(part)total+=qty*part.qty}}}return total}"""
if old not in s: raise SystemExit('purchaseDemandQty pattern not found')
s=s.replace(old,new,1)
old2="""function purchaseRecommendation(p){if(!p||isBundleProduct(p))return null;const demand=purchaseDemandQty(p),daily=demand/PURCHASE_COVER_DAYS,available=productAvailableStock(p),inbound=purchaseInboundQty(p.id),coverage=available+inbound,targetQty=Math.ceil(demand),days=daily>0?coverage/daily:Infinity;if(!(daily>0)||days>=PURCHASE_COVER_DAYS)return null;const qty=Math.max(0,targetQty-coverage),unitCost=purchaseLastUnitCost(p.id),estimatedCost=qty*unitCost;return qty>0?{productId:p.id,product:p,qty,demand,daily,available,inbound,days,unitCost,estimatedCost}:null}"""
new2="""function purchaseRecommendation(p){if(!p||isBundleProduct(p))return null;const demand=purchaseDemandQty(p),daily=demand/PURCHASE_COVER_DAYS,available=productAvailableStock(p),inbound=purchaseInboundQty(p.id),coverage=available+inbound,days=daily>0?coverage/daily:Infinity;if(!(daily>0)||days>=PURCHASE_COVER_DAYS)return null;const qty=Math.max(1,Math.ceil(demand)),unitCost=purchaseLastUnitCost(p.id),estimatedCost=qty*unitCost;return {productId:p.id,product:p,qty,demand,daily,available,inbound,days,unitCost,estimatedCost}}"""
if old2 not in s: raise SystemExit('purchaseRecommendation pattern not found')
s=s.replace(old2,new2,1)
s=s.replace(' · продажи ${x.daily.toFixed(1)}/день · запас ${x.days.toFixed(1)} дн.',' · заказы ${x.daily.toFixed(1)}/день · запас ${x.days.toFixed(1)} дн.',1)
p.write_text(s,encoding='utf-8')
