from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')
start = s.find('function renderReports(){')
if start < 0:
    raise SystemExit('renderReports missing')
end = s.find('\nfunction openProduct(', start)
if end < 0:
    raise SystemExit('openProduct marker missing')
new = r'''function renderReports(){let since=Date.now()-selectedPeriod*86400000,ss=financialSales().filter(s=>s.date>=since),rev=ss.reduce((a,s)=>a+(Number(s.qty)||0)*(Number(s.price)||0),0),cost=ss.reduce((a,s)=>a+(Number(s.qty)||0)*(Number(s.cost)||0),0),fees=ss.reduce((a,s)=>a+(Number(s.qty)||0)*(Number(s.fee)||0),0);document.getElementById('rRevenue').textContent=fmt(rev);document.getElementById('rCost').textContent=fmt(cost);document.getElementById('rFees').textContent=fmt(fees);document.getElementById('rProfit').textContent=fmt(rev-cost-fees);let names=['Kaspi','WB','Ozon','Ручная'];document.getElementById('mpReport').innerHTML=names.map(n=>{let a=ss.filter(s=>s.channel===n),channelRev=a.reduce((x,s)=>x+(Number(s.qty)||0)*(Number(s.price)||0),0),channelProfit=a.reduce((x,s)=>x+(Number(s.qty)||0)*((Number(s.price)||0)-(Number(s.cost)||0)-(Number(s.fee)||0)),0);return `<div class="item row" role="button" tabindex="0" style="cursor:pointer" onclick="openMarketplaceReport('${n}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();openMarketplaceReport('${n}')}"><div class="grow"><b>${n}</b><div class="muted">${a.reduce((x,s)=>x+(Number(s.qty)||0),0)} шт. · прибыль ${fmt(channelProfit)}</div></div><b>${fmt(channelRev)}</b></div>`}).join('')}
function marketplaceProductStats(market){const since=Date.now()-selectedPeriod*86400000,rows=financialSales().filter(s=>s.date>=since&&s.channel===market),map=new Map();for(const sale of rows){const p=prod(sale.productId),key=sale.productId||'unknown',qty=Number(sale.qty)||0,revenue=qty*(Number(sale.price)||0),cost=qty*(Number(sale.cost)||0),fees=qty*(Number(sale.fee)||0);let x=map.get(key);if(!x){x={productId:sale.productId,name:p?.name||'Неизвестный товар',qty:0,revenue:0,cost:0,fees:0,profit:0};map.set(key,x)}x.qty+=qty;x.revenue+=revenue;x.cost+=cost;x.fees+=fees;x.profit+=revenue-cost-fees}return [...map.values()].sort((a,b)=>b.revenue-a.revenue)}
function openMarketplaceReport(market){const rows=marketplaceProductStats(market),qty=rows.reduce((a,x)=>a+x.qty,0),revenue=rows.reduce((a,x)=>a+x.revenue,0),profit=rows.reduce((a,x)=>a+x.profit,0),period=selectedPeriod===1?'сегодня':selectedPeriod+' дней';const body=rows.length?rows.map((x,i)=>`<div class="item row" style="margin-top:8px;${x.productId?'cursor:pointer':''}" ${x.productId?`onclick="openProduct('${x.productId}')"`:''}><div class="grow"><div class="name">${i+1}. ${esc(x.name)}</div><div class="muted">${x.qty} шт. · себестоимость ${fmt(x.cost)} · прибыль ${fmt(x.profit)}</div></div><div class="right"><b>${fmt(x.revenue)}</b><div class="muted">выручка</div></div></div>`).join(''):'<div class="empty">За выбранный период продаж нет</div>';showSheet(`<h3>${esc(market)} · товары</h3><div class="item"><div class="row"><div class="grow"><b>${qty} шт.</b><div class="muted">Период: ${period} · прибыль ${fmt(profit)}</div></div><div class="right"><b>${fmt(revenue)}</b><div class="muted">выручка</div></div></div></div>${body}`)}'''
s = s[:start] + new + s[end:]
p.write_text(s, encoding='utf-8')
