const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const source=fs.readFileSync(__dirname+'/android.js','utf8');
function context(prompt){const calls=[];const c={window:null,prompt,alert:s=>calls.push(['error',s]),atob:s=>Buffer.from(s,'base64').toString('binary'),Uint8Array,File:class{constructor(parts,name,options){this.parts=parts;this.name=name;this.type=options.type;}},openView:v=>calls.push(['view',v]),financeProcessStatementFile:async(f,o)=>calls.push(['preview',f,o]),financeConsumeSharedStatement:null};c.window=c;vm.createContext(c);vm.runInContext(source,c);return {c,calls};}
test('shared PDF reaches preview with unchanged filename and bytes',async()=>{const bytes=Buffer.from('%PDF-1.7\nfixture');const {c,calls}=context(()=>JSON.stringify({name:'Банк 2026.pdf',base64:bytes.toString('base64')}));assert.equal(await c.financeConsumeSharedStatement(),true);assert.equal(calls[1][0],'preview');assert.equal(calls[1][1].name,'Банк 2026.pdf');assert.deepEqual(Buffer.from(calls[1][1].parts[0]),bytes);assert.equal(calls[1][2].shared,true);});
test('empty/error shares do not reach import preview',async()=>{const empty=context(()=>null);assert.equal(await empty.c.financeConsumeSharedStatement(),false);assert.equal(empty.calls.length,0);const bad=context(()=>JSON.stringify({error:'PDF слишком большой'}));await bad.c.financeConsumeSharedStatement();assert.equal(bad.calls.length,1);assert.equal(bad.calls[0][0],'error');});
test('backup crosses native save adapter exactly; errors remain visible',async()=>{let message;const {c}=context(m=>{message=m;return 'ok';});const backup=JSON.stringify({format:'luxar-finance-backup',accounts:[{id:'original',title:'длинное имя'}]});await c.AndroidFinances.saveBackup(backup,'finances.json');assert.equal(JSON.parse(message.slice(13)).text,backup);const bad=context(()=>'Ошибка сохранения');await assert.rejects(bad.c.AndroidFinances.saveBackup(backup,'finances.json'),/Ошибка сохранения/);});
