CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY,
  applied_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS migration_imports (
  backup_sha256 TEXT PRIMARY KEY,
  imported_at BIGINT NOT NULL,
  source_tables INTEGER NOT NULL,
  source_rows BIGINT NOT NULL,
  verified_at BIGINT
);

CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT '',
  photo TEXT NOT NULL DEFAULT '',
  min_stock INTEGER NOT NULL DEFAULT 0,
  stock INTEGER NOT NULL DEFAULT 0,
  cost DOUBLE PRECISION NOT NULL DEFAULT 0,
  total_profit DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS product_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  market TEXT NOT NULL,
  sku TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE (market, sku)
);

CREATE TABLE IF NOT EXISTS marketplace_order_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  market TEXT NOT NULL,
  order_id TEXT NOT NULL,
  code TEXT NOT NULL DEFAULT '',
  entry_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT '',
  state TEXT NOT NULL DEFAULT '',
  creation_date BIGINT NOT NULL DEFAULT 0,
  sku TEXT NOT NULL DEFAULT '',
  product_name TEXT NOT NULL DEFAULT '',
  qty DOUBLE PRECISION NOT NULL DEFAULT 0,
  unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  total_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  seller_delivery_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
  marketplace_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
  fee_source TEXT NOT NULL DEFAULT '',
  raw_json TEXT NOT NULL DEFAULT '',
  first_seen_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE (market, order_id, entry_id)
);

CREATE TABLE IF NOT EXISTS sync_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  market TEXT NOT NULL,
  started_at BIGINT NOT NULL,
  finished_at BIGINT,
  ok INTEGER NOT NULL DEFAULT 0,
  items INTEGER NOT NULL DEFAULT 0,
  error TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS wb_finance_rows (
  market TEXT NOT NULL,
  rrd_id TEXT NOT NULL,
  report_id TEXT NOT NULL DEFAULT '',
  rr_date BIGINT NOT NULL DEFAULT 0,
  sale_date BIGINT NOT NULL DEFAULT 0,
  vendor_code TEXT NOT NULL DEFAULT '',
  nm_id TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  doc_type TEXT NOT NULL DEFAULT '',
  operation TEXT NOT NULL DEFAULT '',
  qty DOUBLE PRECISION NOT NULL DEFAULT 0,
  retail_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  for_pay DOUBLE PRECISION NOT NULL DEFAULT 0,
  acquiring_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
  delivery_service DOUBLE PRECISION NOT NULL DEFAULT 0,
  paid_storage DOUBLE PRECISION NOT NULL DEFAULT 0,
  paid_acceptance DOUBLE PRECISION NOT NULL DEFAULT 0,
  deduction DOUBLE PRECISION NOT NULL DEFAULT 0,
  penalty DOUBLE PRECISION NOT NULL DEFAULT 0,
  additional_payment DOUBLE PRECISION NOT NULL DEFAULT 0,
  rebill_logistic_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
  raw_json TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (market, rrd_id)
);

CREATE TABLE IF NOT EXISTS wb_ad_costs (
  market TEXT NOT NULL,
  day TEXT NOT NULL,
  advert_id TEXT NOT NULL,
  upd_num TEXT NOT NULL DEFAULT '',
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  campaign TEXT NOT NULL DEFAULT '',
  payment_type TEXT NOT NULL DEFAULT '',
  raw_json TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (market, day, advert_id, upd_num)
);

CREATE TABLE IF NOT EXISTS wb_finance_sync_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  market TEXT NOT NULL,
  started_at BIGINT NOT NULL,
  finished_at BIGINT,
  ok INTEGER NOT NULL DEFAULT 0,
  finance_ok INTEGER NOT NULL DEFAULT 0,
  promotion_ok INTEGER NOT NULL DEFAULT 0,
  finance_items INTEGER NOT NULL DEFAULT 0,
  ad_items INTEGER NOT NULL DEFAULT 0,
  error TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS warehouse_state (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  payload TEXT NOT NULL DEFAULT '{}',
  revision BIGINT NOT NULL DEFAULT 0,
  updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS warehouse_audit (
  revision BIGINT PRIMARY KEY,
  updated_at BIGINT NOT NULL,
  payload_sha256 TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'api'
);

CREATE TABLE IF NOT EXISTS stock_sync_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  market TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT 'preview',
  started_at BIGINT NOT NULL,
  finished_at BIGINT,
  ok INTEGER NOT NULL DEFAULT 0,
  warehouse_id TEXT NOT NULL DEFAULT '',
  linked INTEGER NOT NULL DEFAULT 0,
  mapped INTEGER NOT NULL DEFAULT 0,
  missing INTEGER NOT NULL DEFAULT 0,
  items INTEGER NOT NULL DEFAULT 0,
  error TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS wb_stock_links (
  market TEXT NOT NULL,
  sku TEXT NOT NULL,
  chrt_id BIGINT NOT NULL,
  source TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (market, sku)
);

CREATE TABLE IF NOT EXISTS wb_stock_state (
  market TEXT PRIMARY KEY,
  warehouse_id TEXT NOT NULL DEFAULT '',
  payload_hash TEXT NOT NULL DEFAULT '',
  last_sent_at BIGINT NOT NULL DEFAULT 0,
  last_items INTEGER NOT NULL DEFAULT 0,
  last_error TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS kaspi_price_template (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  raw_xml TEXT NOT NULL DEFAULT '',
  feed_key TEXT NOT NULL DEFAULT '',
  primary_store_id TEXT NOT NULL DEFAULT '',
  offer_count INTEGER NOT NULL DEFAULT 0,
  store_ids TEXT NOT NULL DEFAULT '[]',
  merchant_id TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS kaspi_sku_aliases (
  old_sku TEXT PRIMARY KEY,
  seller_sku TEXT NOT NULL,
  updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS kaspi_price_feed_access (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  last_fetched_at BIGINT NOT NULL DEFAULT 0,
  fetch_count INTEGER NOT NULL DEFAULT 0,
  last_user_agent TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS kaspi_report_orders (
  order_id TEXT PRIMARY KEY,
  code TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '',
  state TEXT NOT NULL DEFAULT '',
  creation_date BIGINT NOT NULL DEFAULT 0,
  completion_date BIGINT NOT NULL DEFAULT 0,
  approved_by_bank_date BIGINT NOT NULL DEFAULT 0,
  total_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  delivery_cost_for_seller DOUBLE PRECISION NOT NULL DEFAULT 0,
  raw_json TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL DEFAULT 0,
  lines_json TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS kaspi_report_cache_state (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  last_refresh_at BIGINT NOT NULL DEFAULT 0,
  last_items INTEGER NOT NULL DEFAULT 0,
  last_error TEXT NOT NULL DEFAULT '',
  line_recovery_started_at BIGINT NOT NULL DEFAULT 0,
  line_recovery_finished_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS kaspi_report_returns (
  order_id TEXT PRIMARY KEY,
  code TEXT NOT NULL DEFAULT '',
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  return_date BIGINT NOT NULL DEFAULT 0,
  original_completion_date BIGINT NOT NULL DEFAULT 0,
  detected_at BIGINT NOT NULL DEFAULT 0,
  date_source TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS wb_buyout_cache (
  market TEXT NOT NULL,
  period_key TEXT NOT NULL,
  payload TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL DEFAULT 0,
  last_attempt_at BIGINT NOT NULL DEFAULT 0,
  last_error TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (market, period_key)
);

CREATE TABLE IF NOT EXISTS wb_sales_live_rows (
  market TEXT NOT NULL,
  sale_id TEXT NOT NULL,
  srid TEXT NOT NULL DEFAULT '',
  sale_date BIGINT NOT NULL DEFAULT 0,
  last_change_date BIGINT NOT NULL DEFAULT 0,
  vendor_code TEXT NOT NULL DEFAULT '',
  nm_id TEXT NOT NULL DEFAULT '',
  barcode TEXT NOT NULL DEFAULT '',
  is_return INTEGER NOT NULL DEFAULT 0,
  finished_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  price_with_disc DOUBLE PRECISION NOT NULL DEFAULT 0,
  for_pay DOUBLE PRECISION NOT NULL DEFAULT 0,
  raw_json TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (market, sale_id)
);

CREATE TABLE IF NOT EXISTS wb_sales_live_state (
  market TEXT PRIMARY KEY,
  last_attempt_at BIGINT NOT NULL DEFAULT 0,
  last_success_at BIGINT NOT NULL DEFAULT 0,
  last_change_date BIGINT NOT NULL DEFAULT 0,
  last_error TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS wb_realized_status_tracker (
  market TEXT NOT NULL,
  order_id TEXT NOT NULL,
  rid TEXT NOT NULL DEFAULT '',
  sku TEXT NOT NULL DEFAULT '',
  nm_id TEXT NOT NULL DEFAULT '',
  unit_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  current_status TEXT NOT NULL DEFAULT '',
  sold_at BIGINT NOT NULL DEFAULT 0,
  returned_at BIGINT NOT NULL DEFAULT 0,
  baseline INTEGER NOT NULL DEFAULT 1,
  updated_at BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (market, order_id)
);

CREATE TABLE IF NOT EXISTS wb_realized_tracker_state (
  market TEXT PRIMARY KEY,
  initialized_at BIGINT NOT NULL DEFAULT 0,
  last_sync_at BIGINT NOT NULL DEFAULT 0,
  last_error TEXT NOT NULL DEFAULT '',
  recovery_tag TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS wb_dashboard_daily (
  market TEXT NOT NULL,
  day TEXT NOT NULL,
  buyout_count INTEGER NOT NULL DEFAULT 0,
  buyout_sum DOUBLE PRECISION NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (market, day)
);

CREATE TABLE IF NOT EXISTS wb_dashboard_daily_state (
  market TEXT PRIMARY KEY,
  last_attempt_at BIGINT NOT NULL DEFAULT 0,
  last_success_at BIGINT NOT NULL DEFAULT 0,
  next_allowed_at BIGINT NOT NULL DEFAULT 0,
  last_error TEXT NOT NULL DEFAULT '',
  updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_product_links_product ON product_links(product_id);
CREATE INDEX IF NOT EXISTS idx_order_lines_market_date ON marketplace_order_lines(market, creation_date DESC);
CREATE INDEX IF NOT EXISTS idx_order_lines_market_sku ON marketplace_order_lines(market, sku);
CREATE INDEX IF NOT EXISTS idx_sync_runs_market_started ON sync_runs(market, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_sync_runs_market_started ON stock_sync_runs(market, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_wb_finance_market_date ON wb_finance_rows(market, rr_date DESC);
CREATE INDEX IF NOT EXISTS idx_wb_finance_market_sale_date ON wb_finance_rows(market, sale_date DESC);
CREATE INDEX IF NOT EXISTS idx_wb_ads_market_day ON wb_ad_costs(market, day DESC);
CREATE INDEX IF NOT EXISTS idx_wb_finance_runs_market ON wb_finance_sync_runs(market, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_kaspi_report_return_date ON kaspi_report_returns(return_date DESC);
CREATE INDEX IF NOT EXISTS idx_kaspi_report_completion ON kaspi_report_orders(completion_date DESC);
CREATE INDEX IF NOT EXISTS idx_wb_sales_live_market_date ON wb_sales_live_rows(market, sale_date DESC);
CREATE INDEX IF NOT EXISTS idx_wb_realized_market_sold ON wb_realized_status_tracker(market, sold_at);
CREATE INDEX IF NOT EXISTS idx_wb_realized_market_returned ON wb_realized_status_tracker(market, returned_at);
