CREATE TABLE IF NOT EXISTS warehouse_backups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL DEFAULT '',
  payload TEXT NOT NULL,
  revision BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_warehouse_backups_created_at
  ON warehouse_backups(created_at DESC);
