ALTER TABLE wb_ad_limits
  ADD COLUMN IF NOT EXISTS schedule_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS start_time TEXT NOT NULL DEFAULT '09:00',
  ADD COLUMN IF NOT EXISTS last_scheduled_start_day TEXT NOT NULL DEFAULT '';

