"""Regenerate the isolated finance UI from the warehouse's proven finance engine.

Only finance functions are copied. Warehouse startup, watchers and integrations
are deliberately outside the generated entry point.
"""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
source = (root / 'index.html').read_text()
output = root / 'finances'
output.mkdir(exist_ok=True)
css = source.split('<style>', 1)[1].split('</style>', 1)[0]
(output / 'base.css').write_text(css)
section = re.search(r'<section id="finance"[\s\S]*?</section>', source).group()
section = section.replace('class="view"', 'class="view active"', 1)
# Historical imports and server restore belong in Settings, outside daily work.
section = re.sub(r'  <div class="finance-panel finance-import-panel">[\s\S]*?id="financeLegacyImportStatus"[^>]*>.*?</div></div>', '', section)
(output / 'section.html').write_text(section)
core = source[source.index('const FINANCE_DIRTY_KEY'):source.index('function render(){')]
core = core.replace("'milioner-finance-cache-v1'", "'luxar-finance-cache-v1'")
core = core.replace("'milioner-finance-local-ready-v1'", "'luxar-finance-local-ready-v1'")
core = core.replace("'sklad-share-target-v1'", "'luxar-finance-share-target-v1'")
core = core.replace("'/__shared_finance_statement__'", "'/finances/__shared_finance_statement__'")
core = core.replace('нашим складом без OpenAI', 'приложением без OpenAI')
helpers = []
for prefix in ('function jsonSame(', 'function itemVersion(', 'function mergeArray3(', 'function mergeObject3('):
    helpers.append(next(line for line in source.splitlines() if line.startswith(prefix)))
helpers = '\n'.join(helpers).replace('warehouseKey', 'financeEntityKey')
helpers = helpers.replace("if(field==='purchases'&&warehouseDeletedPurchaseIds.has(String(k)))continue;", '')
start = source.index("type==='financeAccount'")
end = source.index('showSheet(s)}', start) + len('showSheet(s)}')
modal = "function openModal(type,pid=''){let s='';if(" + source[start:end]
(output / 'core.js').write_text('// Generated by scripts/build-finance-app.py; edit the source financial engine.\n' +
    'let financeStatementDraft=null;\nfunction financeEntityKey(_field,x){return String(x?.id||"")}\n' +
    helpers + '\n' + core + '\n' + modal + '\n')
sw = (root / 'sw.js').read_text().replace('sklad-share-target-v1', 'luxar-finance-share-target-v1')
sw = sw.replace('/__shared_finance_statement__', '/finances/__shared_finance_statement__')
sw = sw.replace('/share/finance-statement', '/finances/share/finance-statement')
sw = sw.replace('/?share=', '/finances/?share=')
(output / 'sw.js').write_text(sw)
shell = (output / 'shell.html').read_text()
(output / 'index.html').write_text(shell.replace('{{FINANCE_SECTION}}', section))
print('Generated finance section, styles, engine and share service worker.')
