from pathlib import Path


def once(s, old, new, label):
    n=s.count(old)
    if n!=1:
        raise SystemExit(f'{label}: expected 1 match, got {n}')
    return s.replace(old,new,1)

# Backend
p=Path('cloudflare/millioner-api/src/index.js')
s=p.read_text(encoding='utf-8')
s=once(s,"MAX(CASE WHEN l.market='WB' THEN l.sku END) AS wb,\n                 MAX(CASE WHEN l.market='Ozon' THEN l.sku END) AS ozon","MAX(CASE WHEN l.market='WB' THEN l.sku END) AS wb,\n                 MAX(CASE WHEN l.market='WB2' THEN l.sku END) AS wb2,\n                 MAX(CASE WHEN l.market='Ozon' THEN l.sku END) AS ozon",'products wb2')
s=once(s,"for (const market of ['Kaspi', 'WB']) {","for (const market of ['Kaspi', 'WB', 'WB2']) {",'sync markets')
s=once(s,"if (scheduled && market === 'WB') {\n        const gate = await getWbSyncGate(env.DB);","if (scheduled && (market === 'WB' || market === 'WB2')) {\n        const gate = await getWbSyncGate(env.DB, market);",'wb gate caller')
s=once(s,"async function getWbSyncGate(db) {\n  const row = await db.prepare(`SELECT MAX(started_at) AS lastAttempt FROM sync_runs WHERE market='WB'`).first();","async function getWbSyncGate(db, market='WB') {\n  const row = await db.prepare('SELECT MAX(started_at) AS lastAttempt FROM sync_runs WHERE market=?').bind(market).first();",'wb gate')
s=once(s,"for (const market of ['Kaspi', 'WB', 'Ozon']) {","for (const market of ['Kaspi', 'WB', 'WB2', 'Ozon']) {",'status markets')
s=once(s,"if (market === 'WB') nextSyncAt = lastAttempt ? lastAttempt + WB_MIN_SYNC_MS : Date.now();","if (market === 'WB' || market === 'WB2') nextSyncAt = lastAttempt ? lastAttempt + WB_MIN_SYNC_MS : Date.now();",'wb next sync')
s=once(s,"configured: market === 'Kaspi' ? Boolean(env.KASPI_WORKER_URL) : market === 'WB' ? Boolean(env.WB_TOKEN) : false,","configured: market === 'Kaspi' ? Boolean(env.KASPI_WORKER_URL) : market === 'WB' ? Boolean(env.WB_TOKEN) : market === 'WB2' ? Boolean(env.WB_TOKEN_2) : false,",'wb2 configured')
s=once(s,"mode: market === 'WB' ? (env.WB_TOKEN ? 'marketplace-api' : 'missing-token') : market === 'Kaspi' ? (env.KASPI_TOKEN ? 'worker+direct-recovery' : 'worker-only') : 'off',","mode: market === 'WB' ? (env.WB_TOKEN ? 'marketplace-api' : 'missing-token') : market === 'WB2' ? (env.WB_TOKEN_2 ? 'marketplace-api' : 'missing-token') : market === 'Kaspi' ? (env.KASPI_TOKEN ? 'worker+direct-recovery' : 'worker-only') : 'off',",'wb2 mode')
s=once(s,"else if (market === 'WB') lines = await fetchWb(env);","else if (market === 'WB' || market === 'WB2') lines = await fetchWb(env, market);",'wb2 sync')
s=once(s,"async function fetchWb(env) {\n  const token = String(env.WB_TOKEN || '').trim();\n  if (!token) throw new Error('WB_TOKEN is not configured in millioner-api');","async function fetchWb(env, market='WB') {\n  const token = String((market === 'WB2' ? env.WB_TOKEN_2 : env.WB_TOKEN) || '').trim();\n  if (!token) throw new Error((market === 'WB2' ? 'WB_TOKEN_2' : 'WB_TOKEN') + ' is not configured in millioner-api');",'wb2 token')
s=once(s,"for (const [market, field] of [['Kaspi','kaspi'],['WB','wb'],['Ozon','ozon']]) {","for (const [market, field] of [['Kaspi','kaspi'],['WB','wb'],['WB2','wb2'],['Ozon','ozon']]) {",'wb2 product link')
s=once(s,"if (x === 'wb' || x === 'wildberries') return 'WB';","if (x === 'wb' || x === 'wildberries' || x === 'wb1') return 'WB';\n  if (x === 'wb2' || x === 'wildberries2') return 'WB2';",'normalize wb2')
p.write_text(s,encoding='utf-8')

# Frontend
p=Path('index.html')
s=p.read_text(encoding='utf-8')
old='<h2>Заказы</h2><div class="market-tabs"><button class="market-tab active" data-market="Kaspi" onclick="selectOrderMarket(\'Kaspi\')">Kaspi</button><button class="market-tab" data-market="WB" onclick="selectOrderMarket(\'WB\')">WB</button><button class="market-tab" data-market="Ozon" onclick="selectOrderMarket(\'Ozon\')">Ozon</button></div>'
new=old+'\n  <div id="wbAccountTabs" class="market-tabs" style="display:none;margin-top:-2px"><button class="market-tab" data-wb-account="all" onclick="selectWbAccount(\'all\')">Все</button><button class="market-tab" data-wb-account="WB" onclick="selectWbAccount(\'WB\')">WB 1</button><button class="market-tab" data-wb-account="WB2" onclick="selectWbAccount(\'WB2\')">WB 2</button></div>'
s=once(s,old,new,'tabs')
s=once(s,"let selectedOrderMarket=['Kaspi','WB','Ozon'].includes(state.settings.selectedOrderMarket)?state.settings.selectedOrderMarket:'Kaspi';let unmatchedOrderFilter=state.settings.unmatchedOrderFilter===true;","let selectedOrderMarket=['Kaspi','WB','Ozon'].includes(state.settings.selectedOrderMarket)?state.settings.selectedOrderMarket:'Kaspi';let selectedWbAccount=['all','WB','WB2'].includes(state.settings.selectedWbAccount)?state.settings.selectedWbAccount:'all';let unmatchedOrderFilter=state.settings.unmatchedOrderFilter===true;",'wb account state')
s=once(s,"function isCompletedOrder(market,status,state=''){const s=String(status||'').toUpperCase(),st=String(state||'').toUpperCase();return market==='WB'?st==='SOLD':s==='COMPLETED'}","function isWbMarket(market){return market==='WB'||market==='WB2'}\nfunction isCompletedOrder(market,status,state=''){const s=String(status||'').toUpperCase(),st=String(state||'').toUpperCase();return isWbMarket(market)?st==='SOLD':s==='COMPLETED'}",'wb helper')
s=once(s,"if(market==='WB')return ['SORTED','ACCEPTED_BY_CARRIER','SENT_TO_CARRIER','READY_FOR_PICKUP','SOLD'].includes(st);","if(isWbMarket(market))return ['SORTED','ACCEPTED_BY_CARRIER','SENT_TO_CARRIER','READY_FOR_PICKUP','SOLD'].includes(st);",'wb2 sale state')
s=once(s,"function selectOrderMarket(market){selectedOrderMarket=market;state.settings.selectedOrderMarket=market;save();renderMarketplaceOrders();document.querySelectorAll('.market-tab').forEach(b=>b.classList.toggle('active',b.dataset.market===market))}","function selectOrderMarket(market){selectedOrderMarket=market;state.settings.selectedOrderMarket=market;save();renderMarketplaceOrders();document.querySelectorAll('.market-tab[data-market]').forEach(b=>b.classList.toggle('active',b.dataset.market===market))}\nfunction selectWbAccount(account){selectedWbAccount=account;state.settings.selectedWbAccount=account;save();renderMarketplaceOrders()}",'wb account select')
s=s.replace("if(market==='WB'){if(['CANCELED'","if(isWbMarket(market)){if(['CANCELED'",1)
s=s.replace("if(market==='WB')return ({WAITING:","if(isWbMarket(market))return ({WAITING:",1)
s=once(s,"function renderKaspiOrders(){renderMarketplaceOrders()}function normalizeName(s){return String(s||'').trim().toLowerCase().replace(/\\s+/g,' ')}function marketplaceField(market){return market==='Kaspi'?'kaspi':market==='WB'?'wb':market==='Ozon'?'ozon':null}","function renderKaspiOrders(){renderMarketplaceOrders()}function normalizeName(s){return String(s||'').trim().toLowerCase().replace(/\\s+/g,' ')}function marketplaceField(market){return market==='Kaspi'?'kaspi':market==='WB'?'wb':market==='WB2'?'wb2':market==='Ozon'?'ozon':null}",'wb2 field')
s=once(s,"function mergeOrderFeeds(local,remote){const map=new Map();for(const o of(local||[]))map.set(String(o.orderId)+':'+String(o.entryId),o);for(const o of(remote||[])){const key=String(o.orderId)+':'+String(o.entryId),prev=map.get(key)||{};","function mergeOrderFeeds(local,remote){const map=new Map();for(const o of(local||[]))map.set(String(o.market||'')+'|'+String(o.orderId)+':'+String(o.entryId),o);for(const o of(remote||[])){const key=String(o.market||'')+'|'+String(o.orderId)+':'+String(o.entryId),prev=map.get(key)||{};",'merge keys')
# Keep grouped orders account-safe.
s=once(s,"function groupMarketplaceOrders(feed){const groups=new Map();for(const row of(feed||[])){const key=marketplaceOrderKey(row);if(!key)continue;let g=groups.get(key);if(!g){g={key,orderId:row.orderId,code:row.code,creationDate:Number(row.creationDate)||0,status:row.status,state:row.state,lines:[]};groups.set(key,g)}","function groupMarketplaceOrders(feed){const groups=new Map();for(const row of(feed||[])){const orderKey=marketplaceOrderKey(row);if(!orderKey)continue;const key=String(row.market||'')+'|'+orderKey;let g=groups.get(key);if(!g){g={key,market:row.market||'',orderId:row.orderId,code:row.code,creationDate:Number(row.creationDate)||0,status:row.status,state:row.state,lines:[]};groups.set(key,g)}",'group keys')
# Minimal render injection: filter combined WB feed and show selector. Existing card code remains.
needle="function renderMarketplaceOrders(){const list=document.getElementById('kaspiOrderList');if(!list)return;const market=selectedOrderMarket;const feed=market==='Kaspi'?state.kaspiOrderFeed:market==='WB'?state.wbOrderFeed:state.ozonOrderFeed;"
repl="function renderMarketplaceOrders(){const list=document.getElementById('kaspiOrderList');if(!list)return;const market=selectedOrderMarket,tabs=document.getElementById('wbAccountTabs');if(tabs){tabs.style.display=market==='WB'?'flex':'none';tabs.querySelectorAll('[data-wb-account]').forEach(b=>b.classList.toggle('active',b.dataset.wbAccount===selectedWbAccount))}let feed=market==='Kaspi'?state.kaspiOrderFeed:market==='WB'?state.wbOrderFeed:state.ozonOrderFeed;if(market==='WB'&&selectedWbAccount!=='all')feed=(feed||[]).filter(o=>String(o.market||'WB')===selectedWbAccount);"
s=once(s,needle,repl,'render filter')
# Make card status WB2-aware and label account in state badge.
s=s.replace("const statusClass=(market==='WB'&&", "const gm=g.market||market,wb=isWbMarket(gm),statusClass=(wb&&",1)
s=s.replace("(market==='WB'?stateUpper==='SOLD'", "(wb?stateUpper==='SOLD'",1)
s=s.replace("${esc(marketplaceStatusLabel(market,g.status,g.state))}","${esc(marketplaceStatusLabel(gm,g.status,g.state))}",1)
s=s.replace("<div class=\"order-meta\"><span class=\"badge\">${esc(marketplaceStateLabel(market,g.state))}</span></div>","<div class=\"order-meta\">${gm==='WB2'?'<span class=\"badge\">WB 2</span>':gm==='WB'?'<span class=\"badge\">WB 1</span>':''}<span class=\"badge\">${esc(marketplaceStateLabel(gm,g.state))}</span></div>",1)
# Route WB2 link to its own product field.
s=once(s,"function openWbLink(encodedKey){const key=decodeURIComponent(encodedKey);const o=(state.wbOrderFeed||[]).find(x=>String(x.orderId)+':'+String(x.entryId)===key);if(!o)return alert('Заказ WB не найден. Обновите загрузку WB.');openMarketplaceLink('WB',o.sku,o.code||o.orderId||'',key,o.productName||'')}","function openWbLink(encodedKey){const key=decodeURIComponent(encodedKey);const o=(state.wbOrderFeed||[]).find(x=>String(x.orderId)+':'+String(x.entryId)===key);if(!o)return alert('Заказ WB не найден. Обновите загрузку WB.');openMarketplaceLink(o.market==='WB2'?'WB2':'WB',o.sku,o.code||o.orderId||'',key,o.productName||'')}",'wb2 link')
s=once(s,"const feed=market==='Kaspi'?state.kaspiOrderFeed:market==='WB'?state.wbOrderFeed:state.ozonOrderFeed;","const feed=market==='Kaspi'?state.kaspiOrderFeed:isWbMarket(market)?state.wbOrderFeed:state.ozonOrderFeed;",'attach feed')
s=once(s,"const p={id:id(),name,category:'',photo:'',kaspi:'',wb:'',ozon:'',min:0,stock:0,cost:0,totalProfit:0};","const p={id:id(),name,category:'',photo:'',kaspi:'',wb:'',wb2:'',ozon:'',min:0,stock:0,cost:0,totalProfit:0};",'new product field')
# Replace shared cache loader to fetch both accounts independently from central API.
start=s.index('async function loadSharedOrderCache({silent=true}={})')
end=s.index('\nasync function checkMarketStatus(market)',start)
loader="""async function loadSharedOrderCache({silent=true}={}){try{const status=await apiJson(MILLIONER_API+'/api/market-status');state.settings.serverMarketStatus={};for(const x of(status.markets||[]))state.settings.serverMarketStatus[x.market]=x;const [kdResult,w1Result,w2Result]=await Promise.allSettled([apiJson(MILLIONER_API+'/api/orders?market=Kaspi&limit=500'),apiJson(MILLIONER_API+'/api/orders?market=WB&limit=500'),apiJson(MILLIONER_API+'/api/orders?market=WB2&limit=500')]);let k=[],w1=[],w2=[],warnings=[];if(kdResult.status==='fulfilled'){k=normalizeServerFeed(kdResult.value.orders,'Kaspi');if(k.length){state.kaspiOrderFeed=mergeOrderFeeds(state.kaspiOrderFeed,k);applyMarketplaceTransitions('Kaspi',state.kaspiOrderFeed)}}else warnings.push('Kaspi: '+String(kdResult.reason?.message||kdResult.reason));if(w1Result.status==='fulfilled'){w1=normalizeServerFeed(w1Result.value.orders,'WB');state.wbOrderFeed=mergeOrderFeeds(state.wbOrderFeed,w1);if(w1.length)applyMarketplaceTransitions('WB',state.wbOrderFeed.filter(o=>String(o.market||'WB')==='WB'))}else warnings.push('WB 1: '+String(w1Result.reason?.message||w1Result.reason));if(w2Result.status==='fulfilled'){w2=normalizeServerFeed(w2Result.value.orders,'WB2');state.wbOrderFeed=mergeOrderFeeds(state.wbOrderFeed,w2);if(w2.length)applyMarketplaceTransitions('WB2',state.wbOrderFeed.filter(o=>String(o.market||'WB')==='WB2'))}else warnings.push('WB 2: '+String(w2Result.reason?.message||w2Result.reason));const success=(status.markets||[]).map(x=>Number(x.lastSuccessAt||0)).filter(Boolean);if(success.length)state.settings.lastSync=Math.max(Number(state.settings.lastSync||0),...success);save();render();if(warnings.length)console.warn('Shared cache partial update',warnings.join('; '));return {kaspi:k.length,wb:w1.length,wb2:w2.length,status,warnings}}catch(e){console.error('Shared cache error',e);if(!silent)alert('Ошибка общей базы:\n'+String(e.message||e));return {kaspi:0,wb:0,wb2:0,error:e}}}"""
s=s[:start]+loader+s[end:]
p.write_text(s,encoding='utf-8')

# Smoke markers only; no direct WB Worker calls added.
p=Path('.github/workflows/smoke-test.yml')
s=p.read_text(encoding='utf-8')
marker="              'WB stale-cache UI': 'Последняя копия',"
s=once(s,marker,marker+"\n              'WB2 backend token': 'WB_TOKEN_2',\n              'WB2 account selector': 'id=\"wbAccountTabs\"',\n              'WB2 central cache': 'market=WB2&limit=500',",'smoke markers')
p.write_text(s,encoding='utf-8')
