from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')

pattern=r"function openCorrectReceivedPurchaseShipment\(encodedKey\)\{.*?\n\}\nfunction addEditPurchaseItem"
replacement=r'''function correctPurchaseNewItemOptions(selected=''){return arrivalProductOptions(selected)}
function addCorrectPurchaseItem(selected='',qty='',unitCost=''){
  const box=document.getElementById('correctPurchaseNewItems');if(!box)return;
  const wrap=document.createElement('div');wrap.className='item correct-purchase-new-row';wrap.style.marginBottom='9px';
  const safeQty=Math.max(0,Number(qty)||0)||'',safeUnit=unitCost===''?'':Math.max(0,Number(unitCost)||0);
  wrap.innerHTML=`<div class="field"><label>Поиск товара</label><input class="correct-purchase-q" autocomplete="off" placeholder="Название или артикул" oninput="filterCorrectPurchaseProducts(this)"></div><div class="field"><label>Товар</label><select class="correct-purchase-product">${correctPurchaseNewItemOptions(selected)}</select></div><div class="two"><div class="field"><label>Количество</label><input class="correct-purchase-qty-new" type="number" min="1" step="1" value="${safeQty}"></div><div class="field"><label>Закуп / шт. ₸</label><input class="correct-purchase-unit-new" type="number" min="0" step="0.01" value="${safeUnit}"></div></div><button type="button" class="btn danger full" onclick="this.closest('.correct-purchase-new-row')?.remove()">Убрать товар</button>`;
  box.appendChild(wrap);if(!selected)setTimeout(()=>wrap.querySelector('.correct-purchase-q')?.focus(),0)
}
function filterCorrectPurchaseProducts(input){const row=input.closest('.correct-purchase-new-row'),sel=row?.querySelector('.correct-purchase-product');if(!sel)return;const q=normalizeName(input.value),selected=String(sel.value||'');sel.innerHTML='';for(const p of stockProducts()){const hay=normalizeName([p.name,p.kaspi,p.wb,p.wb2,p.ozon].filter(Boolean).join(' '));if(q&&!hay.includes(q))continue;const o=document.createElement('option');o.value=p.id;o.textContent=p.name;sel.appendChild(o)}if(selected&&[...sel.options].some(o=>o.value===selected))sel.value=selected;if(!sel.options.length){const o=document.createElement('option');o.value='';o.textContent='Ничего не найдено';o.disabled=true;o.selected=true;sel.appendChild(o)}}
function openCorrectReceivedPurchaseShipment(encodedKey){
  const rows=purchaseShipmentRows(encodedKey);if(!rows.length)return alert('Поставка не найдена');
  const first=rows[0],key=encodeURIComponent(String(first.shipmentId||first.id||'')),t=purchaseShipmentTotals({rows}),deliveryValue=Math.round(t.delivery*100)/100;
  const lines=rows.map(x=>{const st=purchaseStatus(x),qty=Math.max(0,Number(x.qty)||0),remaining=Math.max(0,Number(x.remainingQty)||0),sold=st==='received'?Math.max(0,qty-remaining):0,unit=Math.max(0,Number(x.unitCost)||0),statusLabel=st==='received'?'В продаже':st==='at_warehouse'?'На складе':st==='to_me'?'Едет ко мне':'Едет на склад';return `<div class="item correct-purchase-row" data-id="${esc(String(x.id))}" style="margin-bottom:9px"><div class="order-head"><div class="grow"><b>${esc(productNameById(x.productId,'—'))}</b><div class="muted">${statusLabel}${st==='received'&&sold?` · уже выбыло из этой партии: ${sold} шт.`:''}</div></div><span class="badge ${st==='received'?'ok':st==='at_warehouse'?'teal':st==='to_me'?'purple':''}">${statusLabel}</span></div><div class="two" style="margin-top:8px"><div class="field"><label>Количество</label><input class="correct-purchase-qty" type="number" min="${st==='received'?sold:1}" step="1" value="${qty}"></div><div class="field"><label>Закуп / шт. ₸</label><input class="correct-purchase-unit" type="number" min="0" step="0.01" value="${Math.round(unit*100)/100}"></div></div></div>`}).join('');
  showSheet(`<h3>Редактировать поставку</h3><div class="link-note"><b>Исправление приёмки.</b> Можно исправить количество и закупочную цену, указать забытую доставку и добавить товары, которые не внесли при приёмке. Новые товары будут добавлены в эту же поставку как «В продаже» и попадут в остаток/FIFO.</div><div class="field"><label>Дата заказа</label><input id="correctPorDate" type="date" value="${localDateInputValue(first.orderedAt||first.date)}"></div><div class="field"><label>Трек-код / название поставки</label><input id="correctPorBatch" value="${esc(first.batch||'')}"></div><div class="field"><label>Доставка всей поставки ₸</label><input id="correctPorDelivery" type="number" min="0" step="0.01" value="${deliveryValue}"><small class="muted">Сумма распределится по всем товарам партии и пересчитает себестоимость с доставкой.</small></div><h3 style="font-size:16px;margin-top:18px">Товары в поставке</h3>${lines}<h3 style="font-size:16px;margin-top:18px">Забытые товары</h3><div id="correctPurchaseNewItems"></div><button type="button" class="btn full" onclick="addCorrectPurchaseItem()">+ Добавить товар</button><button class="btn dark full" onclick="saveCorrectReceivedPurchaseShipment('${key}')">Сохранить исправление</button>`)
}
function saveCorrectReceivedPurchaseShipment(encodedKey){
  const rows=purchaseShipmentRows(encodedKey);if(!rows.length)return alert('Поставка не найдена');
  const byId=new Map(rows.map(x=>[String(x.id),x])),draft=[...document.querySelectorAll('.correct-purchase-row')].map(el=>({id:String(el.dataset.id||''),qty:Math.max(0,Math.floor(Number(el.querySelector('.correct-purchase-qty')?.value)||0)),unitCost:Math.max(0,Number(el.querySelector('.correct-purchase-unit')?.value)||0)}));
  if(draft.length!==rows.length)return alert('Не удалось прочитать все позиции поставки. Закройте окно и попробуйте снова.');
  for(const d of draft){const x=byId.get(d.id);if(!x)return alert('Одна из позиций поставки не найдена.');const oldQty=Math.max(0,Number(x.qty)||0),oldRemaining=Math.max(0,Number(x.remainingQty)||0),sold=purchaseStatus(x)==='received'?Math.max(0,oldQty-oldRemaining):0;if(d.qty<Math.max(1,sold))return alert(`«${productNameById(x.productId,'Товар')}»: нельзя указать меньше ${Math.max(1,sold)} шт. Из этой партии уже выбыло ${sold} шт.`)}
  const newDraft=[...document.querySelectorAll('.correct-purchase-new-row')].map(el=>({productId:String(el.querySelector('.correct-purchase-product')?.value||''),query:String(el.querySelector('.correct-purchase-q')?.value||'').trim(),qty:Math.max(0,Math.floor(Number(el.querySelector('.correct-purchase-qty-new')?.value)||0)),unitCost:Math.max(0,Number(el.querySelector('.correct-purchase-unit-new')?.value)||0)})).filter(x=>x.productId||x.query||x.qty>0);
  const badNew=newDraft.find(x=>!x.productId||x.qty<=0);if(badNew)return alert('У нового товара выберите позицию и укажите количество.');
  const existingProducts=new Set(rows.map(x=>String(x.productId))),newProducts=newDraft.map(x=>String(x.productId));if(newProducts.some(pid=>existingProducts.has(pid)))return alert('Такой товар уже есть в поставке. Измените его количество в существующей строке.');if(new Set(newProducts).size!==newProducts.length)return alert('Один и тот же новый товар добавлен несколько раз.');
  const changes=[],receivedAt=rows.reduce((a,x)=>Math.max(a,Number(x.receivedAt)||0),0)||Date.now(),shipmentId=String(rows[0].shipmentId||rows[0].id||'');
  for(const d of draft){const x=byId.get(d.id),st=purchaseStatus(x),oldQty=Math.max(0,Number(x.qty)||0),oldRemaining=Math.max(0,Number(x.remainingQty)||0),sold=st==='received'?Math.max(0,oldQty-oldRemaining):0,delta=d.qty-oldQty;if(st==='received'&&delta!==0){const pr=prod(x.productId);if(!pr)return alert('Товар не найден: '+productNameById(x.productId,'—'));const nextStock=(Number(pr.stock)||0)+delta;if(nextStock<0)return alert(`«${pr.name}»: исправление даст отрицательный остаток.`);pr.stock=nextStock;x.remainingQty=Math.max(0,d.qty-sold);log('инвентаризация',pr.id,delta,`коррекция приёмки · поставка ${x.batch||x.shipmentId}`);changes.push(`${pr.name}: ${delta>0?'+':''}${delta} шт.`)}x.qty=d.qty;x.unitCost=d.unitCost;x.buyTotal=d.unitCost*d.qty;if(st!=='received')x.remainingQty=0;}
  const orderedAt=localDateStart(document.getElementById('correctPorDate')?.value),batch=(document.getElementById('correctPorBatch')?.value||'').trim()||String(rows[0].batch||''),now=Date.now();
  for(const n of newDraft){const pr=prod(n.productId);if(!pr)return alert('Не найден добавленный товар');const row={id:id(),shipmentId,status:'received',productId:n.productId,qty:n.qty,remainingQty:n.qty,buyTotal:n.unitCost*n.qty,unitCost:n.unitCost,delivery:0,landedUnitCost:n.unitCost,batch,orderedAt,date:orderedAt,receivedAt,warehouseReceivedAt:receivedAt,createdAt:now,shipmentPurchaseTotal:0,shipmentDeliveryTotal:0};state.purchases.unshift(row);pr.stock=(Number(pr.stock)||0)+n.qty;log('приход',pr.id,n.qty,`добавлено при исправлении приёмки · поставка ${batch||shipmentId}`);changes.push(`${pr.name}: +${n.qty} шт.`)}
  const allRows=purchaseShipmentRows(encodeURIComponent(shipmentId)),totalBuy=allRows.reduce((a,x)=>a+Math.max(0,Number(x.buyTotal)||((Number(x.unitCost)||0)*(Number(x.qty)||0))),0),totalQty=allRows.reduce((a,x)=>a+Math.max(0,Number(x.qty)||0),0),totalDelivery=Math.max(0,Number(document.getElementById('correctPorDelivery')?.value)||0),base=totalBuy>0?totalBuy:totalQty;
  for(const x of allRows){const qty=Math.max(0,Number(x.qty)||0),buy=Math.max(0,Number(x.buyTotal)||((Number(x.unitCost)||0)*qty)),weight=totalBuy>0?buy:qty,deliveryShare=base>0?totalDelivery*(weight/base):0;x.delivery=deliveryShare;x.landedUnitCost=qty?(buy+deliveryShare)/qty:(Number(x.unitCost)||0);x.orderedAt=orderedAt;x.date=orderedAt;x.batch=batch;x.shipmentPurchaseTotal=totalBuy;x.shipmentDeliveryTotal=totalDelivery;if(purchaseStatus(x)==='received'){const pr=prod(x.productId);if(pr)refreshProductAverageCost(pr)}}
  save();closeModal();render();alert(`Поставка исправлена. Доставка: ${fmt(totalDelivery)}.${changes.length?' Изменения: '+changes.join('; '):''}`)
}
function addEditPurchaseItem'''

ns,n=re.subn(pattern,replacement,s,flags=re.S)
if n!=1:
    raise SystemExit(f'correction editor anchor mismatch: {n}')
if 'correctPorDelivery' not in ns or 'addCorrectPurchaseItem' not in ns:
    raise SystemExit('required correction markers missing')
p.write_text(ns,encoding='utf-8')
print('Received purchase editor extended')
