from pathlib import Path

worker=Path('cloudflare/millioner-api/src/index.js')
s=worker.read_text()
old="""        const days=Math.max(1,Math.min(3660,Number(url.searchParams.get('days')||30)));\n        const since=Date.now()-days*86400000;\n        const f=await env.DB.prepare(`SELECT SUM(retail_amount) retailAmount,SUM(for_pay) forPay,SUM(acquiring_fee) acquiring,SUM(delivery_service) delivery,SUM(paid_storage) storage,SUM(paid_acceptance) acceptance,SUM(deduction) deduction,SUM(penalty) penalty,SUM(additional_payment) additionalPayment,SUM(rebill_logistic_cost) rebill FROM wb_finance_rows WHERE market=? AND rr_date>=?`).bind(market,since).first();"""
new="""        const daysRaw=Number(url.searchParams.get('days')||30);\n        const days=daysRaw===-1?-1:Math.max(1,Math.min(3660,daysRaw));\n        const {since,until}=wbFinancePeriodBounds(days);\n        const f=await env.DB.prepare(`SELECT SUM(retail_amount) retailAmount,SUM(for_pay) forPay,SUM(acquiring_fee) acquiring,SUM(delivery_service) delivery,SUM(paid_storage) storage,SUM(paid_acceptance) acceptance,SUM(deduction) deduction,SUM(penalty) penalty,SUM(additional_payment) additionalPayment,SUM(rebill_logistic_cost) rebill FROM wb_finance_rows WHERE market=? AND rr_date>=? AND rr_date<?`).bind(market,since,until).first();"""
if old not in s: raise SystemExit('summary block not found')
s=s.replace(old,new,1)
old2="""        const days=Math.max(1,Math.min(3660,Number(url.searchParams.get('days')||30)));\n        const since=Date.now()-days*86400000;\n        const rows=await env.DB.prepare(`"""
new2="""        const daysRaw=Number(url.searchParams.get('days')||30);\n        const days=daysRaw===-1?-1:Math.max(1,Math.min(3660,daysRaw));\n        const {since,until}=wbFinancePeriodBounds(days);\n        const rows=await env.DB.prepare(`"""
if old2 not in s: raise SystemExit('products period block not found')
s=s.replace(old2,new2,1)
s=s.replace("WHERE f.market=? AND f.rr_date>=?\n          GROUP BY", "WHERE f.market=? AND f.rr_date>=? AND f.rr_date<?\n          GROUP BY",1)
s=s.replace("ORDER BY SUM(f.for_pay) DESC`).bind(market,since).all();", "ORDER BY SUM(f.for_pay) DESC`).bind(market,since,until).all();",1)
insert="""\nfunction wbFinancePeriodBounds(days=30){\n  const offset=5*60*60*1000;\n  const nowLocal=Date.now()+offset;\n  const d=new Date(nowLocal);\n  const localMidnightUtc=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-offset;\n  if(Number(days)===-1)return {since:localMidnightUtc-86400000,until:localMidnightUtc};\n  const n=Math.max(1,Number(days)||1);\n  return {since:localMidnightUtc-(n-1)*86400000,until:localMidnightUtc+86400000};\n}\n"""
marker='async function ensureSchema(db) {'
if insert.strip() not in s:
    if marker not in s: raise SystemExit('worker insert marker not found')
    s=s.replace(marker,insert+'\n'+marker,1)
worker.write_text(s)

html=Path('index.html')
h=html.read_text()
old3="""const body=rows.length?rows.sort((a,b)=>b.profit-a.profit).map((x,i)=>{const p=x.productId?prod(String(x.productId)):null,name=p?.name||x.title||x.vendorCode||('WB '+x.nmId),unit=Number(x.qty)?x.profit/Math.abs(Number(x.qty)):0;return `<div class=\"item\" style=\"margin-top:8px;${p?'cursor:pointer':''}\" ${p?`onclick=\"openProduct('${p.id}','${market}',${periodDays})\"`:''}><div class=\"name\">${i+1}. ${esc(name)}</div><div class=\"muted\">Артикул WB: ${esc(x.vendorCode||'—')}${p?'':' · не привязан к товару склада'}</div><div style=\"display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px\"><div><div class=\"label\">Кол-во в отчёте</div><b>${Number(x.qty||0).toFixed(0)} шт.</b></div><div><div class=\"label\">Прибыль / шт.</div><b>${fmt(unit)}</b></div><div class=\"right\"><div class=\"label\">Чистая прибыль</div><b>${fmt(x.profit)}</b></div></div><div class=\"muted\" style=\"margin-top:8px\">К перечислению: ${fmt(x.forPay)} · расходы WB: ${fmt(x.wbCharges)} · себестоимость FIFO: ${fmt(x.cost)}</div></div>`}).join(''):'<div class=\"empty\">Финансовых строк WB за '+esc(periodText)+' нет</div>';showSheet(`<h3>Продажи ${esc(market)} · ${esc(periodText)}</h3>${head}${body}`)"""
new3="""let body;if(rows.length){body=rows.sort((a,b)=>b.profit-a.profit).map((x,i)=>{const p=x.productId?prod(String(x.productId)):null,name=p?.name||x.title||x.vendorCode||('WB '+x.nmId),unit=Number(x.qty)?x.profit/Math.abs(Number(x.qty)):0;return `<div class=\"item\" style=\"margin-top:8px;${p?'cursor:pointer':''}\" ${p?`onclick=\"openProduct('${p.id}','${market}',${periodDays})\"`:''}><div class=\"name\">${i+1}. ${esc(name)}</div><div class=\"muted\">Артикул WB: ${esc(x.vendorCode||'—')}${p?'':' · не привязан к товару склада'}</div><div style=\"display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px\"><div><div class=\"label\">Реализовано</div><b>${Number(x.qty||0).toFixed(0)} шт.</b></div><div><div class=\"label\">Прибыль / шт.</div><b>${fmt(unit)}</b></div><div class=\"right\"><div class=\"label\">Чистая прибыль</div><b>${fmt(x.profit)}</b></div></div><div class=\"muted\" style=\"margin-top:8px\">К перечислению: ${fmt(x.forPay)} · расходы WB: ${fmt(x.wbCharges)} · себестоимость FIFO: ${fmt(x.cost)}</div></div>`}).join('')}else{const preliminary=marketplaceProductStats(market,periodDays);if(preliminary.length){const pq=preliminary.reduce((a,x)=>a+(Number(x.qty)||0),0),pp=preliminary.reduce((a,x)=>a+(Number(x.profit)||0),0);body=`<div class=\"item\" style=\"margin-top:8px\"><div class=\"name\">Предварительно по реализованным заказам</div><div class=\"muted\" style=\"margin-top:6px\">Финансовый отчёт WB за ${esc(periodText)} ещё не сформирован. Ниже показаны продажи из заказов; комиссии и окончательные удержания WB появятся после формирования финансового отчёта.</div><div class=\"row\" style=\"margin-top:10px\"><div class=\"grow\"><div class=\"label\">Реализовано</div><b>${pq} шт.</b></div><div class=\"right\"><div class=\"label\">Предварительная прибыль</div><b>${fmt(pp)}</b></div></div></div>`+preliminary.map((x,i)=>{const unit=x.qty?x.profit/x.qty:0;return `<div class=\"item\" style=\"margin-top:8px;${x.productId?'cursor:pointer':''}\" ${x.productId?`onclick=\"openProduct('${x.productId}','${market}',${periodDays})\"`:''}><div class=\"name\">${i+1}. ${esc(x.name)}</div><div style=\"display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px\"><div><div class=\"label\">Реализовано</div><b>${x.qty} шт.</b></div><div><div class=\"label\">Прибыль / шт.</div><b>${fmt(unit)}</b></div><div class=\"right\"><div class=\"label\">Предв. прибыль</div><b>${fmt(x.profit)}</b></div></div></div>`}).join('')}else body='<div class=\"empty\">За '+esc(periodText)+' реализованных продаж WB нет</div>'}showSheet(`<h3>Продажи ${esc(market)} · ${esc(periodText)}</h3>${head}${body}`)"""
if old3 not in h: raise SystemExit('frontend report body block not found')
h=h.replace(old3,new3,1)
html.write_text(h)
print('patched WB yesterday report')
# trigger
