from pathlib import Path
p=Path('index.html')
s=p.read_text()
# Make report head replaceable when current finance report has not arrived yet.
old="const head=`<div class=\"item\"><div class=\"row\"><div class=\"grow\"><div class=\"label\">Чистая прибыль · факт WB</div><div class=\"num\">${fmt(totalProfit)}</div></div><div class=\"right\"><div class=\"label\">Реклама со счёта</div><div class=\"num\">${fmt(accountAds)}</div></div></div><div class=\"muted\" style=\"margin-top:8px\">WB выплаты и удержания взяты из финансового отчёта. Себестоимость — FIFO из склада. Общие строки WB без артикула учитываются в общей прибыли.</div></div>`;let body;"
new="let head=`<div class=\"item\"><div class=\"row\"><div class=\"grow\"><div class=\"label\">Чистая прибыль · факт WB</div><div class=\"num\">${fmt(totalProfit)}</div></div><div class=\"right\"><div class=\"label\">Реклама со счёта</div><div class=\"num\">${fmt(accountAds)}</div></div></div><div class=\"muted\" style=\"margin-top:8px\">WB выплаты и удержания взяты из финансового отчёта. Себестоимость — FIFO из склада. Общие строки WB без артикула учитываются в общей прибыли.</div></div>`;let body;"
if old not in s: raise SystemExit('WB head marker not found')
s=s.replace(old,new,1)
old2="const pq=preliminary.reduce((a,x)=>a+(Number(x.qty)||0),0),pr=preliminary.reduce((a,x)=>a+(Number(x.revenue)||0),0);body=`<div class=\"item\" style=\"margin-top:8px\"><div class=\"name\">Продажи уже есть, финансовый отчёт WB ещё ожидается</div><div class=\"muted\" style=\"margin-top:6px\">Чтобы не завышать прибыль, до появления финансовой детализации показываем только реализованное количество и выручку. Комиссии, логистика, хранение и другие удержания WB будут рассчитаны автоматически после появления отчёта.</div><div class=\"row\" style=\"margin-top:10px\"><div class=\"grow\"><div class=\"label\">Реализовано</div><b>${pq} шт.</b></div><div class=\"right\"><div class=\"label\">Выручка</div><b>${fmt(pr)}</b></div></div></div>`+preliminary.map((x,i)=>{return `<div class=\"item\" style=\"margin-top:8px;${x.productId?'cursor:pointer':''}\" ${x.productId?`onclick=\"openProduct('${x.productId}','${market}',${periodDays})\"`:''}><div class=\"name\">${i+1}. ${esc(x.name)}</div><div style=\"display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:10px\"><div><div class=\"label\">Реализовано</div><b>${x.qty} шт.</b></div><div class=\"right\"><div class=\"label\">Выручка</div><b>${fmt(x.revenue)}</b></div></div></div>`}).join('')"
new2="let ratio=market==='WB2'?0.75:0.60;try{const hist=await apiJson(MILLIONER_API+'/api/wb-finance-summary?market='+encodeURIComponent(market)+'&days=30'),hr=Number(hist.retailAmount)||0,hn=Number(hist.netBeforeCost)||0;if(hr>0&&hn>0)ratio=Math.max(0.25,Math.min(1.05,hn/hr))}catch{}const estimated=preliminary.map(x=>{const net=(Number(x.revenue)||0)*ratio,profit=net-(Number(x.cost)||0);return {...x,estimatedNet:net,estimatedProfit:profit}}),pq=estimated.reduce((a,x)=>a+(Number(x.qty)||0),0),pp=estimated.reduce((a,x)=>a+(Number(x.estimatedProfit)||0),0);head=`<div class=\"item\"><div class=\"row\"><div class=\"grow\"><div class=\"label\">Общая прибыль · расчёт WB</div><div class=\"num\">${fmt(pp)}</div></div><div class=\"right\"><div class=\"label\">Реализовано</div><div class=\"num\">${pq} шт.</div></div></div><div class=\"muted\" style=\"margin-top:8px\">Финансовый отчёт WB за этот свежий период ещё не сформирован. Расходы WB рассчитаны по фактической доле выплат и удержаний последних 30 дней; после появления отчёта цифры заменятся на факт автоматически.</div></div>`;body=estimated.map((x,i)=>{const unit=Number(x.qty)?Number(x.estimatedProfit)/Number(x.qty):0;return `<div class=\"item\" style=\"margin-top:8px;${x.productId?'cursor:pointer':''}\" ${x.productId?`onclick=\"openProduct('${x.productId}','${market}',${periodDays})\"`:''}><div class=\"name\">${i+1}. ${esc(x.name)}</div><div style=\"display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px\"><div><div class=\"label\">Реализовано</div><b>${x.qty} шт.</b></div><div><div class=\"label\">Прибыль / шт.</div><b>${fmt(unit)}</b></div><div class=\"right\"><div class=\"label\">Общая прибыль</div><b>${fmt(x.estimatedProfit)}</b></div></div><div class=\"muted\" style=\"margin-top:8px\">Расходы WB пока рассчитаны по факту последних 30 дней · FIFO себестоимость: ${fmt(x.cost)}</div></div>`}).join('')"
if old2 not in s: raise SystemExit('WB fresh fallback marker not found')
s=s.replace(old2,new2,1)
p.write_text(s)
print('patched fresh WB profit fallback')
