from pathlib import Path
p=Path('cloudflare/millioner-api/src/index.js')
s=p.read_text()
# Schema: preserve sale date separately from report date.
s=s.replace("rr_date INTEGER NOT NULL DEFAULT 0,vendor_code", "rr_date INTEGER NOT NULL DEFAULT 0,sale_date INTEGER NOT NULL DEFAULT 0,vendor_code", 1)
s=s.replace("`CREATE INDEX IF NOT EXISTS idx_wb_finance_market_date ON wb_finance_rows(market,rr_date DESC)`,", "`CREATE INDEX IF NOT EXISTS idx_wb_finance_market_date ON wb_finance_rows(market,rr_date DESC)`,\n    `CREATE INDEX IF NOT EXISTS idx_wb_finance_market_sale_date ON wb_finance_rows(market,sale_date DESC)`,", 1)
needle="await ensureColumn(db,'marketplace_order_lines','fee_source',\"TEXT NOT NULL DEFAULT ''\");"
replace=needle+"\n  await ensureColumn(db,'wb_finance_rows','sale_date','INTEGER NOT NULL DEFAULT 0');\n  await db.prepare(`UPDATE wb_finance_rows SET sale_date=COALESCE(CAST(strftime('%s',json_extract(raw_json,'$.saleDt')) AS INTEGER)*1000,CAST(strftime('%s',json_extract(raw_json,'$.sale_dt')) AS INTEGER)*1000,rr_date) WHERE sale_date=0`).run();"
if needle not in s: raise SystemExit('ensure schema marker missing')
s=s.replace(needle,replace,1)
# Sync: rrDate remains report date, saleDate is actual realization date.
old="INSERT INTO wb_finance_rows(market,rrd_id,report_id,rr_date,vendor_code,nm_id,title,doc_type,operation,qty,retail_amount,for_pay,acquiring_fee,delivery_service,paid_storage,paid_acceptance,deduction,penalty,additional_payment,rebill_logistic_cost,raw_json,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(market,rrd_id) DO UPDATE SET report_id=excluded.report_id,rr_date=excluded.rr_date,vendor_code=excluded.vendor_code"
new="INSERT INTO wb_finance_rows(market,rrd_id,report_id,rr_date,sale_date,vendor_code,nm_id,title,doc_type,operation,qty,retail_amount,for_pay,acquiring_fee,delivery_service,paid_storage,paid_acceptance,deduction,penalty,additional_payment,rebill_logistic_cost,raw_json,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(market,rrd_id) DO UPDATE SET report_id=excluded.report_id,rr_date=excluded.rr_date,sale_date=excluded.sale_date,vendor_code=excluded.vendor_code"
if old not in s: raise SystemExit('finance insert sql marker missing')
s=s.replace(old,new,1)
oldbind=".bind(market,rrd,String(x.reportId??''),wbDateMs(x.rrDate||x.saleDt||x.createDate),String(x.vendorCode??''),String(x.nmId??''),String(x.title??''),String(x.docTypeName??''),String(x.sellerOperName??''),wbMoney(x.quantity),wbMoney(x.retailAmount),wbMoney(x.forPay),wbMoney(x.acquiringFee),wbMoney(x.deliveryService),wbMoney(x.paidStorage),wbMoney(x.paidAcceptance),wbMoney(x.deduction),wbMoney(x.penalty),wbMoney(x.additionalPayment),wbMoney(x.rebillLogisticCost),JSON.stringify(x),now).run();"
newbind=".bind(market,rrd,String(x.reportId??''),wbDateMs(x.rrDate||x.createDate),wbDateMs(x.saleDt||x.rrDate||x.createDate),String(x.vendorCode??''),String(x.nmId??''),String(x.title??''),String(x.docTypeName??''),String(x.sellerOperName??''),wbMoney(x.quantity),wbMoney(x.retailAmount),wbMoney(x.forPay),wbMoney(x.acquiringFee),wbMoney(x.deliveryService),wbMoney(x.paidStorage),wbMoney(x.paidAcceptance),wbMoney(x.deduction),wbMoney(x.penalty),wbMoney(x.additionalPayment),wbMoney(x.rebillLogisticCost),JSON.stringify(x),now).run();"
if oldbind not in s: raise SystemExit('finance bind marker missing')
s=s.replace(oldbind,newbind,1)
# Periods: sale date for realized rows, rrDate fallback for service rows.
s=s.replace("WHERE market=? AND rr_date>=? AND rr_date<?`).bind(market,since,until).first();", "WHERE market=? AND COALESCE(NULLIF(sale_date,0),rr_date)>=? AND COALESCE(NULLIF(sale_date,0),rr_date)<?`).bind(market,since,until).first();", 1)
s=s.replace("WHERE f.market=? AND f.rr_date>=? AND f.rr_date<?", "WHERE f.market=? AND COALESCE(NULLIF(f.sale_date,0),f.rr_date)>=? AND COALESCE(NULLIF(f.sale_date,0),f.rr_date)<?", 1)
# Ads need BOTH period edges.
oldad="const day=new Date(since).toISOString().slice(0,10);\n        const a=await env.DB.prepare(`SELECT SUM(amount) allAds,SUM(CASE WHEN lower(payment_type) LIKE '%счет%' OR lower(payment_type) LIKE '%account%' THEN amount ELSE 0 END) accountAds FROM wb_ad_costs WHERE market=? AND day>=?`).bind(market,day).first();"
newad="const day=new Date(since).toISOString().slice(0,10),untilDay=new Date(until).toISOString().slice(0,10);\n        const a=await env.DB.prepare(`SELECT SUM(amount) allAds,SUM(CASE WHEN lower(payment_type) LIKE '%счет%' OR lower(payment_type) LIKE '%account%' THEN amount ELSE 0 END) accountAds FROM wb_ad_costs WHERE market=? AND day>=? AND day<?`).bind(market,day,untilDay).first();"
if oldad not in s: raise SystemExit('summary ads marker missing')
s=s.replace(oldad,newad,1)
oldad2="const day=new Date(since).toISOString().slice(0,10);\n        const ad=await env.DB.prepare(`SELECT SUM(amount) allAds,SUM(CASE WHEN lower(payment_type) LIKE '%счет%' OR lower(payment_type) LIKE '%account%' THEN amount ELSE 0 END) accountAds FROM wb_ad_costs WHERE market=? AND day>=?`).bind(market,day).first();"
newad2="const day=new Date(since).toISOString().slice(0,10),untilDay=new Date(until).toISOString().slice(0,10);\n        const ad=await env.DB.prepare(`SELECT SUM(amount) allAds,SUM(CASE WHEN lower(payment_type) LIKE '%счет%' OR lower(payment_type) LIKE '%account%' THEN amount ELSE 0 END) accountAds FROM wb_ad_costs WHERE market=? AND day>=? AND day<?`).bind(market,day,untilDay).first();"
if oldad2 not in s: raise SystemExit('products ads marker missing')
s=s.replace(oldad2,newad2,1)
# Add row count so frontend knows whether finance data exists.
s=s.replace("const wbCharges=n(f?.acquiring)+n(f?.delivery)+n(f?.storage)+n(f?.acceptance)+n(f?.deduction)+n(f?.penalty)+n(f?.rebill);", "const countRow=await env.DB.prepare(`SELECT COUNT(*) n FROM wb_finance_rows WHERE market=? AND COALESCE(NULLIF(sale_date,0),rr_date)>=? AND COALESCE(NULLIF(sale_date,0),rr_date)<?`).bind(market,since,until).first();\n        const wbCharges=n(f?.acquiring)+n(f?.delivery)+n(f?.storage)+n(f?.acceptance)+n(f?.deduction)+n(f?.penalty)+n(f?.rebill);",1)
s=s.replace("return json({ok:true,market,days,retailAmount:", "return json({ok:true,market,days,rowCount:Number(countRow?.n||0),retailAmount:",1)
# Frontend: never display invented preliminary PROFIT when finance rows are missing.
h=Path('index.html')
t=h.read_text()
old="const pq=preliminary.reduce((a,x)=>a+(Number(x.qty)||0),0),pp=preliminary.reduce((a,x)=>a+(Number(x.profit)||0),0);body=`<div class=\"item\" style=\"margin-top:8px\"><div class=\"name\">Предварительно по реализованным заказам</div><div class=\"muted\" style=\"margin-top:6px\">Финансовый отчёт WB за ${esc(periodText)} ещё не сформирован. Ниже показаны продажи из заказов; комиссии и окончательные удержания WB появятся после формирования финансового отчёта.</div><div class=\"row\" style=\"margin-top:10px\"><div class=\"grow\"><div class=\"label\">Реализовано</div><b>${pq} шт.</b></div><div class=\"right\"><div class=\"label\">Предварительная прибыль</div><b>${fmt(pp)}</b></div></div></div>`+preliminary.map((x,i)=>{const unit=x.qty?x.profit/x.qty:0;return `<div class=\"item\" style=\"margin-top:8px;${x.productId?'cursor:pointer':''}\" ${x.productId?`onclick=\"openProduct('${x.productId}','${market}',${periodDays})\"`:''}><div class=\"name\">${i+1}. ${esc(x.name)}</div><div style=\"display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px\"><div><div class=\"label\">Реализовано</div><b>${x.qty} шт.</b></div><div><div class=\"label\">Прибыль / шт.</div><b>${fmt(unit)}</b></div><div class=\"right\"><div class=\"label\">Предв. прибыль</div><b>${fmt(x.profit)}</b></div></div></div>`}).join('')"
new="const pq=preliminary.reduce((a,x)=>a+(Number(x.qty)||0),0),pr=preliminary.reduce((a,x)=>a+(Number(x.revenue)||0),0);body=`<div class=\"item\" style=\"margin-top:8px\"><div class=\"name\">Продажи уже есть, финансовый отчёт WB ещё ожидается</div><div class=\"muted\" style=\"margin-top:6px\">Чтобы не завышать прибыль, до появления финансовой детализации показываем только реализованное количество и выручку. Комиссии, логистика, хранение и другие удержания WB будут рассчитаны автоматически после появления отчёта.</div><div class=\"row\" style=\"margin-top:10px\"><div class=\"grow\"><div class=\"label\">Реализовано</div><b>${pq} шт.</b></div><div class=\"right\"><div class=\"label\">Выручка</div><b>${fmt(pr)}</b></div></div></div>`+preliminary.map((x,i)=>{return `<div class=\"item\" style=\"margin-top:8px;${x.productId?'cursor:pointer':''}\" ${x.productId?`onclick=\"openProduct('${x.productId}','${market}',${periodDays})\"`:''}><div class=\"name\">${i+1}. ${esc(x.name)}</div><div style=\"display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:10px\"><div><div class=\"label\">Реализовано</div><b>${x.qty} шт.</b></div><div class=\"right\"><div class=\"label\">Выручка</div><b>${fmt(x.revenue)}</b></div></div></div>`}).join('')"
if old not in t: raise SystemExit('frontend preliminary block missing')
t=t.replace(old,new,1)
h.write_text(t)
p.write_text(s)
print('patched all WB finance periods')
