from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')  # Always patch the full current main index.

old = """function createWriteoff(){let p=prod(document.getElementById('wp').value),q=+document.getElementById('wq').value||0,r=document.getElementById('wr').value;if(!p||q<=0)return alert('Проверьте данные');const available=Math.max(0,(Number(p.stock)||0)-reserved(p));if(q>available)return alert('Недостаточно свободного остатка. Доступно: '+available+' шт.');const fifo=fifoConsume(p.id,q);p.stock=(Number(p.stock)||0)-q;refreshProductAverageCost(p);log('списание',p.id,-q,r+' · FIFO '+fmt(fifo.totalCost));save();closeModal();render()}function inventoryForm(pid){let opts=state.products.map(p=>`<option value=\"${p.id}\" ${p.id===pid?'selected':''}>${esc(p.name)}</option>`).join('');return `<h3>Инвентаризация</h3><div class=\"field\"><label>Товар</label><select id=\"ip\">${opts}</select></div><div class=\"field\"><label>Фактический остаток</label><input id=\"iq\" type=\"number\"></div><button class=\"btn dark full\" onclick=\"doInventory()\">Сохранить</button>`}
function doInventory(){let p=prod(document.getElementById('ip').value);if(!p)return;let actual=+document.getElementById('iq').value||0;if(actual<0)return alert('Фактический остаток не может быть отрицательным');const ordered=reserved(p);if(actual<ordered)return alert('Остаток не может быть ниже количества в активных заказах: '+ordered+' шт.');let old=Number(p.stock)||0,delta=actual-old;if(delta<0){fifoConsume(p.id,-delta)}else if(delta>0){const now=Date.now(),unit=Math.max(0,Number(p.cost)||0);state.purchases.unshift({id:id(),productId:p.id,qty:delta,remainingQty:delta,unitCost:unit,delivery:0,landedUnitCost:unit,batch:'Инвентаризация +',receivedAt:now,date:now,inventoryAdjustment:true})}p.stock=actual;refreshProductAverageCost(p);log('инвентаризация',p.id,delta,`было ${old}, стало ${actual}`);save();closeModal();render()}function showSheet(x){document.getElementById('sheet').innerHTML=x;document.getElementById('modal').classList.add('open')}function closeModal(){document.getElementById('modal').classList.remove('open')}"""

new = """function createWriteoff(){let p=prod(document.getElementById('wp').value),q=+document.getElementById('wq').value||0,r=document.getElementById('wr').value;if(!p||q<=0)return alert('Проверьте данные');const available=Math.max(0,(Number(p.stock)||0)-reserved(p));if(q>available)return alert('Недостаточно свободного остатка. Доступно: '+available+' шт.');const fifo=fifoConsume(p.id,q);p.stock=(Number(p.stock)||0)-q;refreshProductAverageCost(p);log('списание',p.id,-q,r+' · FIFO '+fmt(fifo.totalCost));save();closeModal();render()}function inventoryForm(pid){const selected=prod(pid)||state.products[0]||null,stock=Math.max(0,Number(selected?.stock)||0),unit=Math.max(0,Number(selected?.cost)||0);let opts=state.products.map(p=>`<option value=\"${p.id}\" ${p.id===selected?.id?'selected':''}>${esc(p.name)}</option>`).join('');return `<h3>Инвентаризация</h3><div class=\"field\"><label>Товар</label><select id=\"ip\" onchange=\"syncInventoryFields()\">${opts}</select></div><div class=\"two\"><div class=\"field\"><label>Фактический остаток</label><input id=\"iq\" type=\"number\" min=\"0\" value=\"${stock}\"></div><div class=\"field\"><label>Себестоимость 1 шт. ₸</label><input id=\"icost\" type=\"number\" min=\"0\" step=\"0.01\" value=\"${Math.round(unit*100)/100}\"></div></div><div class=\"link-note\">Для исходных остатков без FIFO себестоимость создаёт начальную партию на фактический остаток. Количество, добавленное инвентаризацией, получает эту же себестоимость. Полученные закупки с уже записанной FIFO-себестоимостью не переписываются.</div><button class=\"btn dark full\" onclick=\"doInventory()\">Сохранить</button>`}
function syncInventoryFields(){const p=prod(document.getElementById('ip')?.value);if(!p)return;const q=document.getElementById('iq'),c=document.getElementById('icost');if(q)q.value=Math.max(0,Number(p.stock)||0);if(c)c.value=Math.round(Math.max(0,Number(p.cost)||0)*100)/100}
function doInventory(){let p=prod(document.getElementById('ip').value);if(!p)return;let actual=Number(document.getElementById('iq').value),unit=Math.max(0,Number(document.getElementById('icost')?.value)||0);if(!Number.isFinite(actual))actual=0;if(actual<0)return alert('Фактический остаток не может быть отрицательным');const ordered=reserved(p);if(actual<ordered)return alert('Остаток не может быть ниже количества в активных заказах: '+ordered+' шт.');const old=Math.max(0,Number(p.stock)||0),delta=actual-old,now=Date.now(),lotsBefore=fifoLots(p.id),trackedBefore=lotsBefore.reduce((a,x)=>a+Math.max(0,Number(x.remainingQty)||0),0),legacyQty=Math.max(0,old-trackedBefore),realLots=lotsBefore.filter(x=>!x.inventoryAdjustment),inventoryLots=lotsBefore.filter(x=>x.inventoryAdjustment);if(!realLots.length&&inventoryLots.length){for(const lot of inventoryLots){lot.unitCost=unit;lot.landedUnitCost=unit}}if(legacyQty>0){state.purchases.unshift({id:id(),productId:p.id,qty:legacyQty,remainingQty:legacyQty,unitCost:unit,delivery:0,landedUnitCost:unit,batch:'Инвентаризация · исходный остаток',receivedAt:now,date:now,inventoryAdjustment:true,inventoryCostBaseline:true})}if(delta<0){fifoConsume(p.id,-delta)}else if(delta>0){state.purchases.unshift({id:id(),productId:p.id,qty:delta,remainingQty:delta,unitCost:unit,delivery:0,landedUnitCost:unit,batch:'Инвентаризация +',receivedAt:now+1,date:now+1,inventoryAdjustment:true})}p.stock=actual;if(fifoLots(p.id).length)refreshProductAverageCost(p);else p.cost=unit;log('инвентаризация',p.id,delta,`было ${old}, стало ${actual} · себестоимость ${fmt(unit)}/шт.`);save();closeModal();render()}function showSheet(x){document.getElementById('sheet').innerHTML=x;document.getElementById('modal').classList.add('open')}function closeModal(){document.getElementById('modal').classList.remove('open')}"""

if old not in s:
    if 'id="icost"' in s and 'inventoryCostBaseline:true' in s:
        print('Inventory unit-cost patch already present')
        raise SystemExit(0)
    raise SystemExit('Current inventory form/function anchor not found; refusing unsafe patch')

s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')
print('Inventory now accepts unit cost and creates FIFO baseline only for previously untracked stock.')
