from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')

def rep(old, new, label):
    global s
    c = s.count(old)
    if c != 1:
        raise SystemExit(f'{label}: marker count={c}')
    s = s.replace(old, new, 1)

rep(
    ".purchase-search-wrap{margin:0 0 9px}.purchase-search-wrap input{width:100%;padding:11px;border:1px solid var(--line);border-radius:11px;background:#fff}.purchase-search-hint{font-size:11px;color:var(--muted);margin-top:5px}",
    ".purchase-search-wrap{margin:0 0 9px}.purchase-search-wrap input{width:100%;padding:11px;border:1px solid var(--line);border-radius:11px;background:#fff}.purchase-search-hint{font-size:11px;color:var(--muted);margin-top:5px}\n.purchase-metrics{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:12px}.purchase-metrics .card{padding:12px}.purchase-metrics .num{font-size:18px}.purchase-card.to-me{border-left:4px solid #7c3aed}.purchase-card.received{background:#f1f2f3}.purchase-card .purchase-lines{margin-top:10px;padding-top:9px;border-top:1px solid var(--line)}.purchase-card .purchase-line{display:flex;justify-content:space-between;gap:10px;margin-top:6px}.badge.purple{background:#eee7ff;color:#5b21b6}",
    'purchase css',
)

rep(
    '<section id="purchases" class="view"><h2>Закупки</h2><button class="btn dark full" onclick="openModal(\'arrival\')">+ Создать приход</button><div id="purchaseList" class="list" style="margin-top:10px"></div></section>',
    '<section id="purchases" class="view"><h2>Закупки</h2><div class="purchase-metrics"><div class="card"><div class="label">К доставщику</div><div class="num" id="pToForwarder">0 шт.</div></div><div class="card"><div class="label">Едет ко мне</div><div class="num" id="pToMe">0 шт.</div></div><div class="card"><div class="label">В пути, вложено</div><div class="num" id="pInTransitValue">0 ₸</div></div><div class="card"><div class="label">Получено за 30 дней</div><div class="num" id="pReceived30">0 шт.</div></div></div><button class="btn dark full" onclick="openModal(\'purchase\')">+ Новая закупка</button><button class="btn full" onclick="openModal(\'arrival\')">Приход сразу на склад</button><div id="purchaseList" class="list" style="margin-top:10px"></div></section>',
    'purchases section',
)

rep(
    "state.purchases.forEach(x=>{x.receivedAt=Number(x.receivedAt||x.date)||Date.now();x.remainingQty=Number.isFinite(Number(x.remainingQty))?Math.max(0,Number(x.remainingQty)):Math.max(0,Number(x.qty)||0);x.landedUnitCost=Number(x.landedUnitCost)||((Number(x.unitCost)||0)+((Number(x.delivery)||0)/(Math.max(1,Number(x.qty)||1))))});",
    "state.purchases.forEach(x=>{x.status=['to_forwarder','to_me','received'].includes(String(x.status||''))?String(x.status):'received';if(x.status==='received'){x.receivedAt=Number(x.receivedAt||x.date)||Date.now();x.remainingQty=Number.isFinite(Number(x.remainingQty))?Math.max(0,Number(x.remainingQty)):Math.max(0,Number(x.qty)||0);x.landedUnitCost=Number(x.landedUnitCost)||((Number(x.unitCost)||0)+((Number(x.delivery)||0)/(Math.max(1,Number(x.qty)||1))))}else{x.receivedAt=Number(x.receivedAt)||0;x.remainingQty=0;x.landedUnitCost=Number(x.landedUnitCost)||0}});",
    'startup purchase normalization',
)

rep(
    "state.purchases.forEach(x=>{x.receivedAt=Number(x.receivedAt||x.date)||Date.now();x.remainingQty=Number.isFinite(Number(x.remainingQty))?Math.max(0,Number(x.remainingQty)):Math.max(0,Number(x.qty)||0);x.landedUnitCost=Number(x.landedUnitCost)||((Number(x.unitCost)||0)+((Number(x.delivery)||0)/(Math.max(1,Number(x.qty)||1))))})",
    "state.purchases.forEach(x=>{x.status=['to_forwarder','to_me','received'].includes(String(x.status||''))?String(x.status):'received';if(x.status==='received'){x.receivedAt=Number(x.receivedAt||x.date)||Date.now();x.remainingQty=Number.isFinite(Number(x.remainingQty))?Math.max(0,Number(x.remainingQty)):Math.max(0,Number(x.qty)||0);x.landedUnitCost=Number(x.landedUnitCost)||((Number(x.unitCost)||0)+((Number(x.delivery)||0)/(Math.max(1,Number(x.qty)||1))))}else{x.receivedAt=Number(x.receivedAt)||0;x.remainingQty=0;x.landedUnitCost=Number(x.landedUnitCost)||0}})",
    'remote purchase normalization',
)

rep(
    "function costOf(p){return Number(p.cost)||0}\nfunction fifoLots(productId){return (state.purchases||[]).filter(x=>x.productId===productId&&(Number(x.remainingQty)||0)>0).sort((a,b)=>(Number(a.receivedAt||a.date)||0)-(Number(b.receivedAt||b.date)||0))}",
    "function costOf(p){return Number(p.cost)||0}\nfunction purchaseStatus(x){const v=String(x?.status||'');return ['to_forwarder','to_me','received'].includes(v)?v:'received'}\nfunction fifoLots(productId){return (state.purchases||[]).filter(x=>purchaseStatus(x)==='received'&&x.productId===productId&&(Number(x.remainingQty)||0)>0).sort((a,b)=>(Number(a.receivedAt||a.date)||0)-(Number(b.receivedAt||b.date)||0))}",
    'fifo purchase status',
)

old_render = "function renderPurchases(){document.getElementById('purchaseList').innerHTML=state.purchases.length?[...state.purchases].sort((a,b)=>(Number(b.receivedAt||b.date)||0)-(Number(a.receivedAt||a.date)||0)).map(x=>`<div class=\"item\"><div class=\"name\">${esc(prod(x.productId)?.name||'—')}</div><div class=\"muted\">Партия: ${esc(x.batch||'—')} · пришла ${new Date(Number(x.receivedAt||x.date)).toLocaleDateString('ru-RU')}</div><div class=\"muted\">${x.qty} шт. · закуп ${fmt(x.unitCost)}/шт. · доставка ${fmt(x.delivery)} · себестоимость партии ${fmt(x.landedUnitCost)}/шт.</div><div class=\"muted\">Осталось в партии: ${Number(x.remainingQty)||0} шт.</div></div>`).join(''):'<div class=\"empty\">Приходов пока нет</div>'}"
new_render = r'''function purchaseShipmentGroups(){const map=new Map();for(const x of(state.purchases||[])){const key=String(x.shipmentId||x.id||'');if(!key)continue;let g=map.get(key);if(!g){g={key,rows:[],status:purchaseStatus(x),batch:x.batch||'',orderedAt:Number(x.orderedAt||x.date)||0,receivedAt:Number(x.receivedAt)||0,forwarderReceivedAt:Number(x.forwarderReceivedAt)||0};map.set(key,g)}g.rows.push(x);if(purchaseStatus(x)!=='received')g.status=purchaseStatus(x);const ox=Number(x.orderedAt||x.date)||0;if(!g.orderedAt||ox<g.orderedAt)g.orderedAt=ox;g.receivedAt=Math.max(g.receivedAt,Number(x.receivedAt)||0);g.forwarderReceivedAt=Math.max(g.forwarderReceivedAt,Number(x.forwarderReceivedAt)||0)}return [...map.values()].sort((a,b)=>(Number(b.receivedAt||b.forwarderReceivedAt||b.orderedAt)||0)-(Number(a.receivedAt||a.forwarderReceivedAt||a.orderedAt)||0))}
function purchaseShipmentTotals(g){const rows=g?.rows||[],qty=rows.reduce((a,x)=>a+(Number(x.qty)||0),0),buy=rows.reduce((a,x)=>a+(Number(x.buyTotal)||((Number(x.unitCost)||0)*(Number(x.qty)||0))),0),delivery=rows.reduce((a,x)=>a+(Number(x.delivery)||0),0);return {qty,buy,delivery}}
function renderPurchases(){const groups=purchaseShipmentGroups(),toForwarder=groups.filter(g=>g.status==='to_forwarder'),toMe=groups.filter(g=>g.status==='to_me'),received=groups.filter(g=>g.status==='received'),sumQty=a=>a.reduce((n,g)=>n+purchaseShipmentTotals(g).qty,0),inTransit=[...toForwarder,...toMe],inTransitValue=inTransit.reduce((n,g)=>n+purchaseShipmentTotals(g).buy,0),since=reportPeriodStart(30),received30=received.filter(g=>Number(g.receivedAt)>=since);const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('pToForwarder',sumQty(toForwarder).toLocaleString('ru-RU')+' шт.');set('pToMe',sumQty(toMe).toLocaleString('ru-RU')+' шт.');set('pInTransitValue',fmt(inTransitValue));set('pReceived30',sumQty(received30).toLocaleString('ru-RU')+' шт.');const list=document.getElementById('purchaseList');if(!list)return;if(!groups.length){list.innerHTML='<div class="empty">Закупок пока нет</div>';return}list.innerHTML=groups.map(g=>{const t=purchaseShipmentTotals(g),status=g.status,label=status==='to_forwarder'?'К доставщику':status==='to_me'?'Едет ко мне':'Получено',badge=status==='to_me'?'purple':status==='received'?'':'',date=status==='received'?g.receivedAt:status==='to_me'?g.forwarderReceivedAt:g.orderedAt,dateLabel=status==='received'?'Получено':status==='to_me'?'У доставщика с':'Заказано',lines=g.rows.map(x=>`<div class="purchase-line"><div class="grow"><b>${esc(prod(x.productId)?.name||'—')}</b><div class="muted">${Number(x.qty)||0} шт. · закуп ${fmt(Number(x.buyTotal)||((Number(x.unitCost)||0)*(Number(x.qty)||0)))}</div></div>${status==='received'?`<div class="right"><div class="muted">себестоимость</div><b>${fmt(x.landedUnitCost)}/шт.</b></div>`:''}</div>`).join(''),action=status==='to_forwarder'?`<button class="btn dark full" onclick="advancePurchaseShipment('${encodeURIComponent(g.key)}')">Доставщик получил</button>`:status==='to_me'?`<button class="btn dark full" onclick="openReceivePurchaseShipment('${encodeURIComponent(g.key)}')">Получить поставку</button>`:'';return `<div class="item purchase-card ${status==='to_me'?'to-me':status==='received'?'received':'to-forwarder'}"><div class="order-head"><div class="grow"><div class="name">${esc(g.batch||'Поставка')}</div><div class="muted">${dateLabel}: ${date?new Date(date).toLocaleDateString('ru-RU'):'—'} · ${g.rows.length} поз. · ${t.qty} шт.</div></div><span class="badge ${badge}">${label}</span></div><div class="muted" style="margin-top:7px">Закупка: ${fmt(t.buy)}${status==='received'?' · доставка: '+fmt(t.delivery):''}</div><div class="purchase-lines">${lines}</div>${action}</div>`}).join('')}'''
rep(old_render, new_render, 'render purchases')

rep(
    "function openModal(type,pid=''){let s='';if(type==='menu'){s=`<h3>Быстрое действие</h3>${[['product','Добавить товар'],['arrival','Приход'],['sale','Ручная продажа'],['writeoff','Списание'],['inventory','Инвентаризация']].map(x=>`<button class=\"btn full\" onclick=\"closeModal();openModal('${x[0]}')\">${x[1]}</button>`).join('')}`;}else if(type==='product')s=productForm();else if(type==='edit')s=editProductForm(pid);else if(type==='arrival'){s=arrivalForm();setTimeout(()=>{if(!document.querySelector('.arrival-item'))addArrivalItem()},0);}else if(type==='sale')s=saleForm();else if(type==='writeoff')s=writeoffForm(pid);else if(type==='inventory')s=inventoryForm(pid);showSheet(s)}",
    "function openModal(type,pid=''){let s='';if(type==='menu'){s=`<h3>Быстрое действие</h3>${[['product','Добавить товар'],['purchase','Новая закупка'],['arrival','Приход сразу'],['sale','Ручная продажа'],['writeoff','Списание'],['inventory','Инвентаризация']].map(x=>`<button class=\"btn full\" onclick=\"closeModal();openModal('${x[0]}')\">${x[1]}</button>`).join('')}`;}else if(type==='product')s=productForm();else if(type==='edit')s=editProductForm(pid);else if(type==='purchase'){s=purchaseForm();setTimeout(()=>{if(!document.querySelector('.purchase-item'))addPurchaseItem()},0);}else if(type==='arrival'){s=arrivalForm();setTimeout(()=>{if(!document.querySelector('.arrival-item'))addArrivalItem()},0);}else if(type==='sale')s=saleForm();else if(type==='writeoff')s=writeoffForm(pid);else if(type==='inventory')s=inventoryForm(pid);showSheet(s)}",
    'open modal purchase',
)

marker = 'function saleForm(){let opts='
if s.count(marker) != 1:
    raise SystemExit('purchase functions insertion marker missing')
purchase_funcs = r'''function purchaseForm(){return `<h3>Новая закупка</h3><div class="link-note">Новая закупка сначала попадает в статус «К доставщику». Остаток склада не меняется. Когда доставщик получит товары, переведите поставку в «Едет ко мне». Только после фактического получения поставка станет приходом на склад.</div><div class="field"><label>Дата заказа</label><input id="porDate" type="date" value="${localDateInputValue()}"></div><div class="field"><label>Название / партия</label><input id="porBatch" placeholder="Например: Китай 11.08"></div><div id="purchaseItems"></div><button type="button" class="btn full" onclick="addPurchaseItem()">+ Добавить товар</button><div id="purchaseOrderCalc" class="link-note"></div><button class="btn dark full" onclick="createPurchaseOrder()">Сохранить закупку</button>`}
function addPurchaseItem(selected=''){const box=document.getElementById('purchaseItems');if(!box)return;const wrap=document.createElement('div');wrap.className='item purchase-item';wrap.style.marginBottom='9px';wrap.innerHTML=`<div class="field"><label>Поиск товара</label><input class="purchase-q" autocomplete="off" placeholder="Название или артикул" oninput="filterPurchaseProducts(this)"></div><div class="field"><label>Товар</label><select class="purchase-product">${arrivalProductOptions(selected)}</select></div><div class="two"><div class="field"><label>Количество</label><input class="purchase-qty" type="number" min="1" oninput="updatePurchaseOrderCalculator()"></div><div class="field"><label>Сумма закупки ₸</label><input class="purchase-buy" type="number" min="0" oninput="updatePurchaseOrderCalculator()"></div></div><button type="button" class="btn danger full" onclick="removePurchaseItem(this)">Убрать товар</button>`;box.appendChild(wrap);updatePurchaseOrderCalculator();setTimeout(()=>wrap.querySelector('.purchase-q')?.focus(),0)}
function removePurchaseItem(btn){const rows=document.querySelectorAll('.purchase-item');if(rows.length<=1)return alert('В закупке должен остаться хотя бы один товар');btn.closest('.purchase-item')?.remove();updatePurchaseOrderCalculator()}
function filterPurchaseProducts(input){const row=input.closest('.purchase-item'),sel=row?.querySelector('.purchase-product');if(!sel)return;const q=normalizeName(input.value),selected=String(sel.value||'');sel.innerHTML='';for(const p of state.products){const hay=normalizeName([p.name,p.kaspi,p.wb,p.wb2,p.ozon].filter(Boolean).join(' '));if(q&&!hay.includes(q))continue;const o=document.createElement('option');o.value=p.id;o.textContent=p.name;sel.appendChild(o)}if(selected&&[...sel.options].some(o=>o.value===selected))sel.value=selected;if(!sel.options.length){const o=document.createElement('option');o.value='';o.textContent='Ничего не найдено';o.disabled=true;o.selected=true;sel.appendChild(o)}updatePurchaseOrderCalculator()}
function purchaseDraftRows(){return [...document.querySelectorAll('.purchase-item')].map(row=>({productId:row.querySelector('.purchase-product')?.value||'',qty:Math.max(0,Number(row.querySelector('.purchase-qty')?.value)||0),buy:Math.max(0,Number(row.querySelector('.purchase-buy')?.value)||0)}))}
function updatePurchaseOrderCalculator(){const rows=purchaseDraftRows().filter(x=>x.productId&&x.qty>0),qty=rows.reduce((a,x)=>a+x.qty,0),buy=rows.reduce((a,x)=>a+x.buy,0),box=document.getElementById('purchaseOrderCalc');if(box)box.innerHTML=`<b>Закупка</b><div style="margin-top:6px">Позиций: ${rows.length} · товаров: ${qty} шт.</div><div><b>Вложено в товар: ${fmt(buy)}</b></div>`}
function createPurchaseOrder(){const rows=purchaseDraftRows(),valid=rows.filter(x=>x.productId&&x.qty>0),orderedAt=localDateStart(document.getElementById('porDate')?.value),batch=(document.getElementById('porBatch')?.value||'').trim();if(!valid.length)return alert('Добавьте хотя бы один товар и количество');if(valid.some(x=>!prod(x.productId)))return alert('Проверьте выбранные товары');const ids=valid.map(x=>x.productId);if(new Set(ids).size!==ids.length)return alert('Один и тот же товар добавлен несколько раз. Объедините количество в одну строку.');const shipmentId='po-'+id(),label=batch||('Китай '+new Date(orderedAt).toLocaleDateString('ru-RU')),totalBuy=valid.reduce((a,x)=>a+x.buy,0);for(const x of valid){state.purchases.unshift({id:id(),shipmentId,status:'to_forwarder',productId:x.productId,qty:x.qty,remainingQty:0,buyTotal:x.buy,unitCost:x.qty?x.buy/x.qty:0,delivery:0,landedUnitCost:0,batch:label,orderedAt,date:orderedAt,receivedAt:0,createdAt:Date.now(),shipmentPurchaseTotal:totalBuy})}save();closeModal();render();alert('Закупка создана. Товар пока едет к доставщику и в остаток склада не добавлен.')}
function purchaseShipmentRows(encodedKey){const key=decodeURIComponent(String(encodedKey||''));return (state.purchases||[]).filter(x=>String(x.shipmentId||x.id||'')===key)}
function advancePurchaseShipment(encodedKey){const rows=purchaseShipmentRows(encodedKey);if(!rows.length)return alert('Поставка не найдена');if(!rows.some(x=>purchaseStatus(x)==='to_forwarder'))return alert('Эта поставка уже передана дальше.');if(!confirm('Доставщик получил эту поставку?'))return;const now=Date.now();for(const x of rows){if(purchaseStatus(x)==='to_forwarder'){x.status='to_me';x.forwarderReceivedAt=now}}save();render();alert('Поставка теперь в статусе «Едет ко мне».')}
function openReceivePurchaseShipment(encodedKey){const rows=purchaseShipmentRows(encodedKey);if(!rows.length)return alert('Поставка не найдена');if(!rows.every(x=>purchaseStatus(x)==='to_me'))return alert('Получить можно только поставку в статусе «Едет ко мне».');const g={rows},t=purchaseShipmentTotals(g),key=encodeURIComponent(String(rows[0].shipmentId||rows[0].id||''));showSheet(`<h3>Получить поставку</h3><div class="item"><b>${esc(rows[0].batch||'Поставка')}</b><div class="muted">${rows.length} поз. · ${t.qty} шт. · закупка ${fmt(t.buy)}</div></div><div class="field"><label>Дата получения</label><input id="receivePurchaseDate" type="date" value="${localDateInputValue()}"></div><div class="field"><label>Доставка всей поставки ₸</label><input id="receivePurchaseDelivery" type="number" min="0" value="0"></div><div class="link-note">После подтверждения товар будет добавлен на склад. Доставка распределится по товарам пропорционально сумме закупки, а если закупка нулевая — пропорционально количеству.</div><button class="btn dark full" onclick="receivePurchaseShipment('${key}')">Оприходовать на склад</button>`)}
function receivePurchaseShipment(encodedKey){const rows=purchaseShipmentRows(encodedKey);if(!rows.length)return alert('Поставка не найдена');if(!rows.every(x=>purchaseStatus(x)==='to_me'))return alert('Поставка уже получена или ещё не передана доставщиком.');const receivedAt=localDateStart(document.getElementById('receivePurchaseDate')?.value),delivery=Math.max(0,Number(document.getElementById('receivePurchaseDelivery')?.value)||0),totalQty=rows.reduce((a,x)=>a+(Number(x.qty)||0),0),totalBuy=rows.reduce((a,x)=>a+(Number(x.buyTotal)||((Number(x.unitCost)||0)*(Number(x.qty)||0))),0),base=totalBuy>0?totalBuy:totalQty;if(!totalQty)return alert('В поставке нет количества');for(const x of rows){const p=prod(x.productId),qty=Math.max(0,Number(x.qty)||0);if(!p||!qty)continue;const buy=Number(x.buyTotal)||((Number(x.unitCost)||0)*qty),weight=totalBuy>0?buy:qty,deliveryShare=base>0?delivery*(weight/base):0,unitCost=qty?buy/qty:0,landedUnitCost=qty?(buy+deliveryShare)/qty:0;x.status='received';x.receivedAt=receivedAt;x.remainingQty=qty;x.unitCost=unitCost;x.delivery=deliveryShare;x.landedUnitCost=landedUnitCost;x.shipmentPurchaseTotal=totalBuy;x.shipmentDeliveryTotal=delivery;p.stock=(Number(p.stock)||0)+qty;refreshProductAverageCost(p);log('приход',p.id,qty,`поставка ${x.batch||x.shipmentId} · закуп ${fmt(buy)} · доставка ${fmt(deliveryShare)} · себестоимость ${fmt(landedUnitCost)}/шт.`)}save();closeModal();render();alert('Поставка получена и добавлена на склад.')}
'''
s = s.replace(marker, purchase_funcs + marker, 1)

rep(
    "state.purchases.unshift({id:id(),shipmentId,shipmentPurchaseTotal:totalBuy,shipmentDeliveryTotal:delivery,productId:p.id,qty:x.qty,remainingQty:x.qty,unitCost,delivery:deliveryShare,landedUnitCost,batch:b,receivedAt,date:now})",
    "state.purchases.unshift({id:id(),shipmentId,status:'received',shipmentPurchaseTotal:totalBuy,shipmentDeliveryTotal:delivery,productId:p.id,qty:x.qty,remainingQty:x.qty,unitCost,delivery:deliveryShare,landedUnitCost,batch:b,orderedAt:receivedAt,receivedAt,date:now})",
    'direct arrival status',
)

if s.count('version:4') != 1:
    raise SystemExit('backup version marker missing')
s = s.replace('version:4', 'version:5', 1)
p.write_text(s, encoding='utf-8')

w = Path('.github/workflows/smoke-test.yml')
y = w.read_text(encoding='utf-8')
req = "            'function fifoConsume(productId,qty)',\n"
add = "            'function fifoConsume(productId,qty)',\n            'function purchaseShipmentGroups()','function createPurchaseOrder()','function advancePurchaseShipment(','function receivePurchaseShipment(',\n            'В пути, вложено','+ Новая закупка',\n"
if y.count(req) != 1:
    raise SystemExit('smoke required marker count=' + str(y.count(req)))
y = y.replace(req, add, 1)
live = "              && grep -q 'id=\"koAmount\"' /tmp/site.html \\\n"
live_add = "              && grep -q 'id=\"koAmount\"' /tmp/site.html \\\n              && grep -q 'function createPurchaseOrder()' /tmp/site.html \\\n              && grep -q 'function receivePurchaseShipment(' /tmp/site.html \\\n              && grep -q 'В пути, вложено' /tmp/site.html \\\n"
if y.count(live) != 1:
    raise SystemExit('smoke live marker count=' + str(y.count(live)))
y = y.replace(live, live_add, 1)
final = "          grep -q 'id=\"koAmount\"' /tmp/site.html\n"
final_add = "          grep -q 'id=\"koAmount\"' /tmp/site.html\n          grep -q 'function createPurchaseOrder()' /tmp/site.html\n          grep -q 'function receivePurchaseShipment(' /tmp/site.html\n          grep -q 'В пути, вложено' /tmp/site.html\n"
if y.count(final) != 1:
    raise SystemExit('smoke final marker count=' + str(y.count(final)))
y = y.replace(final, final_add, 1)
w.write_text(y, encoding='utf-8')
