from pathlib import Path

path = Path('index.html')
html = path.read_text(encoding='utf-8')

old = "function saveProductEdit(pid){let p=prod(pid);if(!p)return;let n=document.getElementById('en').value.trim();if(!n)return alert('Введите название');const kind=document.getElementById('ekind')?.value==='bundle'?'bundle':'simple',wasBundle=isBundleProduct(p);let components=[];if(kind==='bundle'){components=readBundleComponents('ebundleRows',p.id);if(!components||!components.length)return alert('Добавьте хотя бы один товар в состав набора.');if(!wasBundle){const active=directReserved(p),transit=(state.purchases||[]).some(x=>x.productId===p.id&&purchaseStatus(x)!=='received'),fifo=fifoLots(p.id).reduce((a,x)=>a+(Number(x.remainingQty)||0),0);if((Number(p.stock)||0)>0||fifo>0||active>0||transit)return alert('Сначала обнулите остаток обычного товара и завершите его активные заказы/закупки, затем можно сделать из него набор.')}}else if(wasBundle&&directReserved(p)>0)return alert('Нельзя изменить набор на обычный товар, пока есть активные заказы на набор.');p.name=n;p.category=readCategoryPicker('ec','ecnew');rememberCategory(p.category);p.photo=document.getElementById('ep').value;p.kaspi=document.getElementById('ek').value;p.wb=document.getElementById('ew').value;p.wb2=document.getElementById('ew2').value;p.ozon=document.getElementById('eo').value;p.kind=kind;p.components=kind==='bundle'?components:[];p.min=Math.max(0,+document.getElementById('emin').value||0);if(kind==='bundle'){p.stock=0;p.cost=productDisplayCost(p)}else p.cost=Math.max(0,+document.getElementById('ecost')?.value||Number(p.cost)||0);save();closeModal();render()}"

new = "function convertSimpleProductToBundle(p){if(!p||isBundleProduct(p))return;const now=Date.now(),oldStock=Math.max(0,Number(p.stock)||0),lots=fifoLots(p.id),fifoQty=lots.reduce((a,x)=>a+Math.max(0,Number(x.remainingQty)||0),0);for(const lot of lots){const left=Math.max(0,Number(lot.remainingQty)||0);if(!left)continue;lot.bundleConvertedAt=now;lot.bundleConvertedQty=left;lot.remainingQty=0}p.stock=0;if(oldStock>0||fifoQty>0)log('инвентаризация',p.id,-oldStock,`переход в виртуальный набор · самостоятельный остаток ${oldStock} шт. обнулён · FIFO ${fifoQty} шт. архивировано`)}\nfunction saveProductEdit(pid){let p=prod(pid);if(!p)return;let n=document.getElementById('en').value.trim();if(!n)return alert('Введите название');const kind=document.getElementById('ekind')?.value==='bundle'?'bundle':'simple',wasBundle=isBundleProduct(p);let components=[];if(kind==='bundle'){components=readBundleComponents('ebundleRows',p.id);if(!components||!components.length)return alert('Добавьте хотя бы один товар в состав набора.');if(!wasBundle){const transit=(state.purchases||[]).some(x=>x.productId===p.id&&purchaseStatus(x)!=='received'),usedBy=(state.products||[]).find(x=>x.id!==p.id&&isBundleProduct(x)&&bundleComponents(x).some(c=>c.productId===p.id));if(transit)return alert('У этой карточки есть незавершённая закупка. Сначала завершите её: такую закупку нельзя безопасно разложить по компонентам набора.');if(usedBy)return alert('Этот товар уже используется как компонент набора «'+usedBy.name+'». Сначала уберите его из того набора.');const oldStock=Math.max(0,Number(p.stock)||0),fifo=fifoLots(p.id).reduce((a,x)=>a+Math.max(0,Number(x.remainingQty)||0),0);if((oldStock>0||fifo>0)&&!confirm(`Сделать «${p.name}» виртуальным набором?\\n\\nСтарый самостоятельный остаток ${oldStock} шт. будет автоматически обнулён. История закупок и продаж сохранится. Дальше остаток набора будет считаться только по его компонентам.`))return}}else if(wasBundle&&directReserved(p)>0)return alert('Нельзя изменить набор на обычный товар, пока есть активные заказы на набор.');if(kind==='bundle'&&!wasBundle)convertSimpleProductToBundle(p);p.name=n;p.category=readCategoryPicker('ec','ecnew');rememberCategory(p.category);p.photo=document.getElementById('ep').value;p.kaspi=document.getElementById('ek').value;p.wb=document.getElementById('ew').value;p.wb2=document.getElementById('ew2').value;p.ozon=document.getElementById('eo').value;p.kind=kind;p.components=kind==='bundle'?components:[];p.min=Math.max(0,+document.getElementById('emin').value||0);if(kind==='bundle'){p.stock=0;p.cost=productDisplayCost(p)}else p.cost=Math.max(0,+document.getElementById('ecost')?.value||Number(p.cost)||0);save();closeModal();render()}"

if old not in html:
    raise SystemExit('Current saveProductEdit block not found; refusing unsafe patch')
html = html.replace(old, new, 1)

old_note = '<div class="link-note">При продаже набора склад спишет FIFO-себестоимость и остаток каждого компонента.</div>'
new_note = '<div class="link-note">При продаже набора склад спишет FIFO-себестоимость и остаток каждого компонента. Если эта карточка раньше была обычным товаром, её старый самостоятельный остаток при сохранении будет безопасно обнулён, а история сохранится.</div>'
if old_note not in html:
    raise SystemExit('Bundle edit note not found; refusing unsafe patch')
html = html.replace(old_note, new_note, 1)

path.write_text(html, encoding='utf-8')
print('Patched safe simple-to-bundle conversion')
