from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')

def rep(old, new, label):
    global s
    count = s.count(old)
    if count != 1:
        raise SystemExit(f'{label}: marker count={count}')
    s = s.replace(old, new, 1)

rep(
    '''<div class="purchase-lines">${lines}</div>${action}</div>''',
    '''<div class="purchase-lines">${lines}</div>${status!=='received'?`<button class="btn full" onclick="openEditPurchaseShipment('${encodeURIComponent(g.key)}')">Редактировать поставку</button>`:''}${action}</div>''',
    'purchase card edit button',
)

marker = '''function purchaseShipmentRows(encodedKey){const key=decodeURIComponent(String(encodedKey||''));return (state.purchases||[]).filter(x=>String(x.shipmentId||x.id||'')===key)}\nfunction advancePurchaseShipment(encodedKey)'''
insert = r'''function purchaseShipmentRows(encodedKey){const key=decodeURIComponent(String(encodedKey||''));return (state.purchases||[]).filter(x=>String(x.shipmentId||x.id||'')===key)}
function openEditPurchaseShipment(encodedKey){const rows=purchaseShipmentRows(encodedKey);if(!rows.length)return alert('Поставка не найдена');if(rows.some(x=>purchaseStatus(x)==='received'))return alert('Полученную поставку нельзя менять здесь: она уже вошла в склад и FIFO.');const first=rows[0],t=purchaseShipmentTotals({rows}),key=encodeURIComponent(String(first.shipmentId||first.id||'')),buyValue=Math.round(t.buy*100)/100,deliveryValue=Math.round(t.delivery*100)/100;showSheet(`<h3>Редактировать поставку</h3><div class="link-note">Можно изменить дату, название, общую сумму закупки, доставку, товары и количество. Пока поставка не получена, склад и FIFO от этих изменений не меняются.</div><div class="field"><label>Дата заказа</label><input id="editPorDate" type="date" value="${localDateInputValue(first.orderedAt||first.date)}"></div><div class="field"><label>Название / партия</label><input id="editPorBatch" value="${esc(first.batch||'')}"></div><div class="two"><div class="field"><label>Общая сумма закупки ₸</label><input id="editPorBuyTotal" type="number" min="0" value="${buyValue}" oninput="updateEditPurchaseCalculator()"></div><div class="field"><label>Доставка ₸</label><input id="editPorDelivery" type="number" min="0" value="${deliveryValue}" oninput="updateEditPurchaseCalculator()"></div></div><div id="editPurchaseItems"></div><button type="button" class="btn full" onclick="addEditPurchaseItem()">+ Добавить товар</button><div id="editPurchaseCalc" class="link-note"></div><button class="btn dark full" onclick="savePurchaseShipmentEdit('${key}')">Сохранить изменения</button>`);setTimeout(()=>{for(const x of rows)addEditPurchaseItem(x.productId,Number(x.qty)||0);updateEditPurchaseCalculator()},0)}
function addEditPurchaseItem(selected='',qty=''){const box=document.getElementById('editPurchaseItems');if(!box)return;const wrap=document.createElement('div');wrap.className='item edit-purchase-item';wrap.style.marginBottom='9px';wrap.innerHTML=`<div class="field"><label>Поиск товара</label><input class="edit-purchase-q" autocomplete="off" placeholder="Название или артикул" oninput="filterEditPurchaseProducts(this)"></div><div class="field"><label>Товар</label><select class="edit-purchase-product">${arrivalProductOptions(selected)}</select></div><div class="field"><label>Количество</label><input class="edit-purchase-qty" type="number" min="1" value="${Math.max(0,Number(qty)||0)||''}" oninput="updateEditPurchaseCalculator()"></div><button type="button" class="btn danger full" onclick="removeEditPurchaseItem(this)">Убрать товар</button>`;box.appendChild(wrap);updateEditPurchaseCalculator()}
function removeEditPurchaseItem(btn){const rows=document.querySelectorAll('.edit-purchase-item');if(rows.length<=1)return alert('В поставке должен остаться хотя бы один товар');btn.closest('.edit-purchase-item')?.remove();updateEditPurchaseCalculator()}
function filterEditPurchaseProducts(input){const row=input.closest('.edit-purchase-item'),sel=row?.querySelector('.edit-purchase-product');if(!sel)return;const q=normalizeName(input.value),selected=String(sel.value||'');sel.innerHTML='';for(const p of state.products){const hay=normalizeName([p.name,p.kaspi,p.wb,p.wb2,p.ozon].filter(Boolean).join(' '));if(q&&!hay.includes(q))continue;const o=document.createElement('option');o.value=p.id;o.textContent=p.name;sel.appendChild(o)}if(selected&&[...sel.options].some(o=>o.value===selected))sel.value=selected;if(!sel.options.length){const o=document.createElement('option');o.value='';o.textContent='Ничего не найдено';o.disabled=true;o.selected=true;sel.appendChild(o)}updateEditPurchaseCalculator()}
function editPurchaseDraftRows(){return [...document.querySelectorAll('.edit-purchase-item')].map(row=>({productId:row.querySelector('.edit-purchase-product')?.value||'',qty:Math.max(0,Number(row.querySelector('.edit-purchase-qty')?.value)||0)}))}
function updateEditPurchaseCalculator(){const rows=editPurchaseDraftRows().filter(x=>x.productId&&x.qty>0),qty=rows.reduce((a,x)=>a+x.qty,0),buy=Math.max(0,Number(document.getElementById('editPorBuyTotal')?.value)||0),delivery=Math.max(0,Number(document.getElementById('editPorDelivery')?.value)||0),unit=qty?buy/qty:0,box=document.getElementById('editPurchaseCalc');if(box)box.innerHTML=`<b>После сохранения</b><div style="margin-top:6px">Позиций: ${rows.length} · товаров: ${qty} шт.</div><div>Закупка: ${fmt(buy)} · доставка: ${fmt(delivery)} · всего: ${fmt(buy+delivery)}</div><div>Закупочная цена: ${fmt(unit)}/шт.</div>`}
function savePurchaseShipmentEdit(encodedKey){const oldRows=purchaseShipmentRows(encodedKey);if(!oldRows.length)return alert('Поставка не найдена');if(oldRows.some(x=>purchaseStatus(x)==='received'))return alert('Полученную поставку редактировать нельзя.');const rows=editPurchaseDraftRows(),valid=rows.filter(x=>x.productId&&x.qty>0),orderedAt=localDateStart(document.getElementById('editPorDate')?.value),batch=(document.getElementById('editPorBatch')?.value||'').trim(),totalBuy=Math.max(0,Number(document.getElementById('editPorBuyTotal')?.value)||0),totalDelivery=Math.max(0,Number(document.getElementById('editPorDelivery')?.value)||0);if(!valid.length)return alert('Добавьте хотя бы один товар и количество');if(valid.some(x=>!prod(x.productId)))return alert('Проверьте выбранные товары');const ids=valid.map(x=>x.productId);if(new Set(ids).size!==ids.length)return alert('Один и тот же товар добавлен несколько раз. Объедините количество в одну строку.');const first=oldRows[0],shipmentId=String(first.shipmentId||first.id||''),status=purchaseStatus(first),forwarderReceivedAt=oldRows.reduce((a,x)=>Math.max(a,Number(x.forwarderReceivedAt)||0),0),totalQty=valid.reduce((a,x)=>a+x.qty,0),label=batch||('Китай '+new Date(orderedAt).toLocaleDateString('ru-RU')),oldByProduct=new Map(oldRows.map(x=>[String(x.productId),x])),updated=valid.map(x=>{const old=oldByProduct.get(String(x.productId)),share=totalQty>0?x.qty/totalQty:0,buyTotal=totalBuy*share,delivery=totalDelivery*share;return {...(old||{}),id:old?.id||id(),shipmentId,status,productId:x.productId,qty:x.qty,remainingQty:0,buyTotal,unitCost:x.qty?buyTotal/x.qty:0,delivery,landedUnitCost:0,batch:label,orderedAt,date:orderedAt,receivedAt:0,createdAt:Number(old?.createdAt)||Date.now(),forwarderReceivedAt:status==='to_me'?forwarderReceivedAt:0,shipmentPurchaseTotal:totalBuy,shipmentDeliveryTotal:totalDelivery}}),oldIds=new Set(oldRows.map(x=>x.id));state.purchases=state.purchases.filter(x=>!oldIds.has(x.id));state.purchases.unshift(...updated);save();closeModal();render();alert('Поставка обновлена. Остаток склада не изменился.')}
function advancePurchaseShipment(encodedKey)'''
rep(marker, insert, 'purchase edit functions')

p.write_text(s, encoding='utf-8')
