from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')  # full current main is read at runtime before every patch

def replace_once(old,new,label):
    global s
    if old not in s:
        if new in s:
            return
        raise SystemExit(f'{label} anchor not found')
    s=s.replace(old,new,1)

def cut(a,b):
    i=s.index(a); j=s.index(b,i); return i,j,s[i:j]

# Core bundle helpers. Bundle stock is virtual and derived from components.
old="function stockTotal(){return state.products.reduce((a,p)=>a+(Number(p.stock)||0),0)}\nfunction reserved(p){return (state.reservations||[]).filter(r=>r.productId===p.id&&r.active).reduce((a,r)=>a+(Number(r.qty)||0),0)}"
new="""function isBundleProduct(p){return String(p?.kind||'simple')==='bundle'&&Array.isArray(p?.components)&&p.components.length>0}
function bundleComponents(p){return isBundleProduct(p)?p.components.map(x=>({productId:String(x?.productId||''),qty:Math.max(1,Number(x?.qty)||1)})).filter(x=>x.productId):[]}
function stockProducts(){return (state.products||[]).filter(p=>!isBundleProduct(p))}
function directReserved(p){return p?(state.reservations||[]).filter(r=>r.productId===p.id&&r.active).reduce((a,r)=>a+(Number(r.qty)||0),0):0}
function reserved(p){if(!p)return 0;if(isBundleProduct(p))return directReserved(p);let total=directReserved(p);for(const bundle of(state.products||[])){if(!isBundleProduct(bundle))continue;const component=bundleComponents(bundle).find(x=>x.productId===p.id);if(!component)continue;total+=directReserved(bundle)*component.qty}return total}
function bundleAvailableStock(p){const parts=bundleComponents(p);if(!parts.length)return 0;let max=Infinity;for(const part of parts){const component=prod(part.productId);if(!component||isBundleProduct(component))return 0;const free=Math.max(0,(Number(component.stock)||0)-reserved(component));max=Math.min(max,Math.floor(free/part.qty))}return Number.isFinite(max)?Math.max(0,max):0}
function productDisplayStock(p){return isBundleProduct(p)?bundleAvailableStock(p):(Number(p?.stock)||0)}
function productAvailableStock(p){return isBundleProduct(p)?bundleAvailableStock(p):Math.max(0,(Number(p?.stock)||0)-reserved(p))}
function productDisplayCost(p){if(!isBundleProduct(p))return Number(p?.cost)||0;return bundleComponents(p).reduce((sum,part)=>sum+(Number(prod(part.productId)?.cost)||0)*part.qty,0)}
function stockTotal(){return stockProducts().reduce((a,p)=>a+(Number(p.stock)||0),0)}
function consumeSellableProduct(p,qty,context=''){qty=Math.max(0,Number(qty)||0);if(!p||!qty)return {totalCost:0,unitCost:0,lots:[],shortage:0};if(!isBundleProduct(p)){const stockBefore=Math.max(0,Number(p.stock)||0),fifo=fifoConsume(p.id,qty),shortage=Math.max(0,qty-stockBefore);p.stock=Math.max(0,stockBefore-qty);refreshProductAverageCost(p);log('продажа',p.id,-Math.min(qty,stockBefore),(context?context+' · ':'')+'FIFO'+(shortage?' · нехватка '+shortage+' шт.':''));return {totalCost:fifo.totalCost,unitCost:fifo.unitCost,lots:fifo.lots,shortage}}let totalCost=0,shortage=0,lots=[];for(const part of bundleComponents(p)){const component=prod(part.productId),need=qty*part.qty;if(!component)continue;const stockBefore=Math.max(0,Number(component.stock)||0),fifo=fifoConsume(component.id,need),partShortage=Math.max(0,need-stockBefore);component.stock=Math.max(0,stockBefore-need);refreshProductAverageCost(component);totalCost+=fifo.totalCost;shortage+=partShortage;lots.push({productId:component.id,qty:need,lots:fifo.lots});log('продажа',component.id,-Math.min(need,stockBefore),(context?context+' · ':'')+'набор «'+p.name+'»'+(partShortage?' · нехватка '+partShortage+' шт.':''))}return {totalCost,unitCost:qty?totalCost/qty:0,lots,shortage}}
"""
replace_once(old,new,'bundle core')

# Bundle editor UI helpers before productForm.
marker='function productForm(){'
if 'function bundleComponentOptions(' not in s:
    helpers="""function bundleComponentOptions(selected='',excludeId=''){return stockProducts().filter(x=>String(x.id)!==String(excludeId||'')).map(x=>`<option value=\"${x.id}\" ${String(x.id)===String(selected)?'selected':''}>${esc(x.name)}</option>`).join('')}
function bundleRowHtml(component={},excludeId=''){return `<div class=\"item bundle-component-row\" style=\"margin-top:8px\"><div class=\"two\"><div class=\"field\"><label>Товар в наборе</label><select class=\"bundle-component\">${bundleComponentOptions(component.productId||'',excludeId)}</select></div><div class=\"field\"><label>Количество</label><input class=\"bundle-qty\" type=\"number\" min=\"1\" value=\"${Math.max(1,Number(component.qty)||1)}\"></div></div><button type=\"button\" class=\"btn danger full\" onclick=\"removeBundleComponent(this)\">Убрать из набора</button></div>`}
function bundleRowsHtml(components=[],excludeId=''){return (components||[]).map(x=>bundleRowHtml(x,excludeId)).join('')}
function addBundleComponent(containerId,excludeId=''){const box=document.getElementById(containerId);if(!box)return;if(!stockProducts().some(x=>String(x.id)!==String(excludeId||'')))return alert('Сначала создайте обычные товары, из которых будет состоять набор.');box.insertAdjacentHTML('beforeend',bundleRowHtml({},excludeId))}
function removeBundleComponent(btn){btn.closest('.bundle-component-row')?.remove()}
function toggleProductKind(prefix){const kind=document.getElementById(prefix+'kind')?.value||'simple',bundle=document.getElementById(prefix+'bundle'),simple=document.getElementById(prefix+'simple');if(bundle)bundle.style.display=kind==='bundle'?'block':'none';if(simple)simple.style.display=kind==='bundle'?'none':'block';if(kind==='bundle'){const box=document.getElementById(prefix+'bundleRows');if(box&&!box.querySelector('.bundle-component-row'))addBundleComponent(prefix+'bundleRows',prefix==='e'?document.getElementById('editProductId')?.value||'':'')}}
function readBundleComponents(containerId,excludeId=''){const rows=[...document.querySelectorAll('#'+containerId+' .bundle-component-row')],map=new Map();for(const row of rows){const productId=String(row.querySelector('.bundle-component')?.value||''),qty=Math.max(1,Number(row.querySelector('.bundle-qty')?.value)||1),component=prod(productId);if(!productId||!component||isBundleProduct(component)||String(productId)===String(excludeId||'')){alert('Проверьте состав набора: каждый компонент должен быть обычным товаром.');return null}map.set(productId,(map.get(productId)||0)+qty)}return [...map.entries()].map(([productId,qty])=>({productId,qty}))}
"""
    s=s.replace(marker,helpers+marker,1)

# Replace create/edit forms and save functions.
i,j,_=cut('function productForm(){','function arrivalProductOptions(')
forms="""function productForm(){return `<h3>Добавить товар</h3><div class=\"field\"><label>Название</label><input id=\"pn\"></div>${categoryPickerHtml('pc','pcnew')}<div class=\"field\"><label>Тип товара</label><select id=\"pkind\" onchange=\"toggleProductKind('p')\"><option value=\"simple\">Обычный товар</option><option value=\"bundle\">Набор</option></select></div><div id=\"pbundle\" style=\"display:none\"><div class=\"link-note\">Набор не имеет отдельного физического остатка. Его доступное количество считается по остаткам компонентов.</div><div id=\"pbundleRows\"></div><button type=\"button\" class=\"btn full\" onclick=\"addBundleComponent('pbundleRows')\">+ Добавить товар в набор</button></div><div class=\"field\"><label>Фото (URL)</label><input id=\"pp\" placeholder=\"Можно добавить позже\"></div><div class=\"two\"><div class=\"field\"><label>Kaspi артикул</label><input id=\"pk\"></div><div class=\"field\"><label>WB1 артикул</label><input id=\"pw\"></div></div><div class=\"two\"><div class=\"field\"><label>WB2 артикул</label><input id=\"pw2\"></div><div class=\"field\"><label>Ozon артикул</label><input id=\"po\"></div></div><div id=\"psimple\"><div class=\"two\"><div class=\"field\"><label>Себестоимость / шт. ₸</label><input id=\"pcost\" type=\"number\" min=\"0\" value=\"0\"></div><div class=\"field\"><label>Начальный остаток</label><input id=\"pstock\" type=\"number\" value=\"0\"></div></div></div><div class=\"field\"><label>Минимальный остаток</label><input id=\"pmin\" type=\"number\" value=\"0\"></div><button class=\"btn dark full\" onclick=\"createProduct()\">Создать</button>`}
function editProductForm(pid){let p=prod(pid),bundle=isBundleProduct(p);return `<h3>Редактировать товар</h3><input id=\"editProductId\" type=\"hidden\" value=\"${esc(pid)}\"><div class=\"field\"><label>Название</label><input id=\"en\" value=\"${esc(p.name)}\"></div>${categoryPickerHtml('ec','ecnew',p.category||'')}<div class=\"field\"><label>Тип товара</label><select id=\"ekind\" onchange=\"toggleProductKind('e')\"><option value=\"simple\" ${!bundle?'selected':''}>Обычный товар</option><option value=\"bundle\" ${bundle?'selected':''}>Набор</option></select></div><div id=\"ebundle\" style=\"display:${bundle?'block':'none'}\"><div class=\"link-note\">При продаже набора склад спишет FIFO-себестоимость и остаток каждого компонента.</div><div id=\"ebundleRows\">${bundleRowsHtml(bundleComponents(p),p.id)}</div><button type=\"button\" class=\"btn full\" onclick=\"addBundleComponent('ebundleRows','${p.id}')\">+ Добавить товар в набор</button></div><div class=\"field\"><label>Фото (URL)</label><input id=\"ep\" value=\"${esc(p.photo||'')}\"></div><div class=\"two\"><div class=\"field\"><label>Kaspi артикул</label><input id=\"ek\" value=\"${esc(p.kaspi||'')}\"></div><div class=\"field\"><label>WB1 артикул</label><input id=\"ew\" value=\"${esc(p.wb||'')}\"></div></div><div class=\"two\"><div class=\"field\"><label>WB2 артикул</label><input id=\"ew2\" value=\"${esc(p.wb2||'')}\"></div><div class=\"field\"><label>Ozon артикул</label><input id=\"eo\" value=\"${esc(p.ozon||'')}\"></div></div><div id=\"esimple\" style=\"display:${bundle?'none':'block'}\"><div class=\"two\"><div class=\"field\"><label>Себестоимость / шт. ₸</label><input id=\"ecost\" type=\"number\" min=\"0\" value=\"${Number(p.cost)||0}\"></div><div class=\"field\"><label>Минимальный остаток</label><input id=\"eminSimple\" type=\"number\" value=\"${p.min||0}\"></div></div></div><div class=\"field\"><label>Минимальный остаток / наборов</label><input id=\"emin\" type=\"number\" value=\"${p.min||0}\"></div><div class=\"muted\">У обычного товара остаток меняется через «Приход» или «Инвентаризация». У набора остаток рассчитывается автоматически по компонентам.</div><button class=\"btn dark full\" onclick=\"saveProductEdit('${pid}')\">Сохранить изменения</button>`}
function saveProductEdit(pid){let p=prod(pid);if(!p)return;let n=document.getElementById('en').value.trim();if(!n)return alert('Введите название');const kind=document.getElementById('ekind')?.value==='bundle'?'bundle':'simple',wasBundle=isBundleProduct(p);let components=[];if(kind==='bundle'){components=readBundleComponents('ebundleRows',p.id);if(!components||!components.length)return alert('Добавьте хотя бы один товар в состав набора.');if(!wasBundle){const active=directReserved(p),transit=(state.purchases||[]).some(x=>x.productId===p.id&&purchaseStatus(x)!=='received'),fifo=fifoLots(p.id).reduce((a,x)=>a+(Number(x.remainingQty)||0),0);if((Number(p.stock)||0)>0||fifo>0||active>0||transit)return alert('Сначала обнулите остаток обычного товара и завершите его активные заказы/закупки, затем можно сделать из него набор.')}}else if(wasBundle&&directReserved(p)>0)return alert('Нельзя изменить набор на обычный товар, пока есть активные заказы на набор.');p.name=n;p.category=readCategoryPicker('ec','ecnew');rememberCategory(p.category);p.photo=document.getElementById('ep').value;p.kaspi=document.getElementById('ek').value;p.wb=document.getElementById('ew').value;p.wb2=document.getElementById('ew2').value;p.ozon=document.getElementById('eo').value;p.kind=kind;p.components=kind==='bundle'?components:[];p.min=Math.max(0,+document.getElementById('emin').value||0);if(kind==='bundle'){p.stock=0;p.cost=productDisplayCost(p)}else p.cost=Math.max(0,+document.getElementById('ecost')?.value||Number(p.cost)||0);save();closeModal();render()}
function createProduct(){let n=document.getElementById('pn').value.trim();if(!n)return alert('Введите название');const category=readCategoryPicker('pc','pcnew');rememberCategory(category);const kind=document.getElementById('pkind')?.value==='bundle'?'bundle':'simple',components=kind==='bundle'?readBundleComponents('pbundleRows'):[];if(kind==='bundle'&&(!components||!components.length))return alert('Добавьте хотя бы один товар в состав набора.');const p={id:id(),name:n,category,photo:document.getElementById('pp').value,kaspi:document.getElementById('pk').value,wb:document.getElementById('pw').value,wb2:document.getElementById('pw2').value,ozon:document.getElementById('po').value,min:Math.max(0,+document.getElementById('pmin').value||0),kind,components:kind==='bundle'?components:[],stock:kind==='bundle'?0:(+document.getElementById('pstock').value||0),cost:kind==='bundle'?0:Math.max(0,+document.getElementById('pcost').value||0),totalProfit:0};state.products.push(p);if(kind==='bundle')p.cost=productDisplayCost(p);if(!isBundleProduct(p)&&p.stock>0){const now=Date.now();state.purchases.unshift({id:id(),productId:p.id,qty:p.stock,remainingQty:p.stock,unitCost:p.cost,delivery:0,landedUnitCost:p.cost,batch:'Начальный остаток',receivedAt:now,date:now,opening:true});log('инвентаризация',p.id,p.stock,'начальный остаток')}save();closeModal();render()}
"""
s=s[:i]+forms+s[j:]

# Only physical products can be purchased/received/inventoried/written off directly.
s=s.replace("function arrivalProductOptions(selected=''){return state.products.map(p=>", "function arrivalProductOptions(selected=''){return stockProducts().map(p=>",1)
s=s.replace("for(const p of state.products){const hay=normalizeName([p.name,p.kaspi,p.wb,p.wb2,p.ozon]", "for(const p of stockProducts()){const hay=normalizeName([p.name,p.kaspi,p.wb,p.wb2,p.ozon]",2)
s=s.replace("function writeoffForm(pid){let opts=state.products.map(p=>", "function writeoffForm(pid){let opts=stockProducts().map(p=>",1)
s=s.replace("function inventoryForm(pid){const selected=prod(pid)||state.products[0]||null", "function inventoryForm(pid){const selected=(!isBundleProduct(prod(pid))?prod(pid):null)||stockProducts()[0]||null",1)
s=s.replace("let opts=state.products.map(p=>`<option value=\"${p.id}\" ${p.id===selected?.id?'selected':''}>${esc(p.name)}</option>`).join('');return `<h3>Инвентаризация</h3>", "let opts=stockProducts().map(p=>`<option value=\"${p.id}\" ${p.id===selected?.id?'selected':''}>${esc(p.name)}</option>`).join('');return `<h3>Инвентаризация</h3>",1)

# Product list/report cards should show computed bundle availability and component cost.
i,j,block=cut('function renderAttention(){','function renderMovement(){')
new_block="""function renderAttention(){let a=state.products.map(p=>({p,stock:productDisplayStock(p)})).filter(x=>x.stock<=x.p.min&&x.p.min>0||x.stock<0).sort((x,y)=>x.stock-y.stock).slice(0,5);document.getElementById('attention').innerHTML=a.length?a.map(x=>`<div class=\"item row\"><div class=\"grow\"><div class=\"name\">${esc(x.p.name)}</div><div class=\"muted\">Остаток ${x.stock} · минимум ${x.p.min}</div></div><span class=\"badge ${x.stock<0?'bad':'warn'}\">${x.stock<0?'Нехватка':'На закупку'}</span></div>`).join(''):'<div class=\"empty\">Всё в норме</div>'}
function renderRecent(){let a=state.movements.slice(0,5);document.getElementById('recent').innerHTML=a.length?a.map(m=>`<div class=\"item\"><div class=\"row\"><div class=\"grow\"><b>${esc(m.type)}</b><div class=\"muted\">${esc(productNameById(m.productId,'Товар удалён'))}</div></div><div class=\"right\">${m.qty>0?'+':''}${m.qty}<div class=\"muted\">${new Date(m.date).toLocaleString('ru-RU')}</div></div></div></div>`).join(''):'<div class=\"empty\">Операций пока нет</div>'}
function renderProducts(){let q=(document.getElementById('q')?.value||'').toLowerCase(),f=document.getElementById('filter')?.value||'all',sort=document.getElementById('sort')?.value||'name';let a=state.products.filter(p=>[p.name,p.kaspi,p.wb,p.wb2,p.ozon].join(' ').toLowerCase().includes(q));a=a.filter(p=>{const stock=productDisplayStock(p);return f==='all'||f==='low'&&stock<=p.min&&stock>0||f==='zero'&&stock<=0||f==='buy'&&(stock<=p.min||stock<0)});a.sort((x,y)=>{const xs=productDisplayStock(x),ys=productDisplayStock(y);return sort==='name'?x.name.localeCompare(y.name):sort==='stock'?ys-xs:sort==='sales'?salesDays(y)-salesDays(x):sort==='profit'?profitForProduct(y)-profitForProduct(x):salesDays(x)?xs/salesDays(x)-ys/salesDays(y):0});document.getElementById('productList').innerHTML=a.length?a.map(productCard).join(''):'<div class=\"empty\">Товаров не найдено</div>'}
function productCard(p){let d=salesDays(p),profit=profitForProduct(p),stock=productDisplayStock(p),cost=productDisplayCost(p),kind=isBundleProduct(p)?'Набор · ':'';return `<div class=\"item row\" onclick=\"openProduct('${p.id}')\">${p.photo?`<img class=\"thumb\" src=\"${p.photo}\">`:'<div class=\"thumb\">Фото</div>'}<div class=\"grow\"><div class=\"name\">${esc(p.name)}</div><div class=\"muted\">${kind}${esc(p.category||'Без категории')}</div><div class=\"muted\">Продажи/день: ${d.toFixed(1)} · Запас: ${d?(stock/d).toFixed(1):'∞'} дн.</div><div class=\"muted\">Себестоимость: ${fmt(cost)} · Прибыль 30д: ${fmt(profit)}</div></div><div class=\"right\"><b>${stock}</b><div class=\"muted\">${isBundleProduct(p)?'набор.':'шт.'}</div></div></div>`}
"""
# preserve renderMovement and replace up to it
s=s[:i]+new_block+s[j:]

# Manual sale supports bundles and uses component FIFO.
old="function createSale(){let p=prod(document.getElementById('sp').value),q=+document.getElementById('sq').value||0,price=Math.max(0,+document.getElementById('sprice').value||0),fee=Math.max(0,+document.getElementById('sfee').value||0);if(!p||q<=0)return alert('Проверьте данные');const available=Math.max(0,(Number(p.stock)||0)-reserved(p));if(q>available)return alert('Недостаточно свободного остатка. Доступно: '+available+' шт.');const fifo=fifoConsume(p.id,q);p.stock=(Number(p.stock)||0)-q;let c=fifo.unitCost;state.sales.push({id:id(),productId:p.id,qty:q,price,cost:c,fee,channel:'Ручная',date:Date.now(),fifoLots:fifo.lots});p.totalProfit=(p.totalProfit||0)+q*(price-c-fee);refreshProductAverageCost(p);log('продажа',p.id,-q,'FIFO');save();closeModal();render()}"
new="function createSale(){let p=prod(document.getElementById('sp').value),q=+document.getElementById('sq').value||0,price=Math.max(0,+document.getElementById('sprice').value||0),fee=Math.max(0,+document.getElementById('sfee').value||0);if(!p||q<=0)return alert('Проверьте данные');const available=productAvailableStock(p);if(q>available)return alert('Недостаточно свободного остатка. Доступно: '+available+(isBundleProduct(p)?' набор.':' шт.'));const consumed=consumeSellableProduct(p,q,'Ручная продажа');let c=consumed.unitCost;state.sales.push({id:id(),productId:p.id,qty:q,price,cost:c,fee,channel:'Ручная',date:Date.now(),fifoLots:consumed.lots,stockShortage:consumed.shortage});p.totalProfit=(p.totalProfit||0)+q*(price-c-fee);if(isBundleProduct(p))p.cost=productDisplayCost(p);save();closeModal();render()}"
replace_once(old,new,'manual sale')

# Write-off uses only physical products.
old="function createWriteoff(){let p=prod(document.getElementById('wp').value),q=+document.getElementById('wq').value||0,r=document.getElementById('wr').value;if(!p||q<=0)return alert('Проверьте данные');const available=Math.max(0,(Number(p.stock)||0)-reserved(p));if(q>available)return alert('Недостаточно свободного остатка. Доступно: '+available+' шт.');const fifo=fifoConsume(p.id,q);p.stock=(Number(p.stock)||0)-q;refreshProductAverageCost(p);log('списание',p.id,-q,r+' · FIFO '+fmt(fifo.totalCost));save();closeModal();render()}"
new="function createWriteoff(){let p=prod(document.getElementById('wp').value),q=+document.getElementById('wq').value||0,r=document.getElementById('wr').value;if(!p||q<=0||isBundleProduct(p))return alert('Проверьте данные');const available=productAvailableStock(p);if(q>available)return alert('Недостаточно свободного остатка. Доступно: '+available+' шт.');const fifo=fifoConsume(p.id,q);p.stock=(Number(p.stock)||0)-q;refreshProductAverageCost(p);log('списание',p.id,-q,r+' · FIFO '+fmt(fifo.totalCost));save();closeModal();render()}"
replace_once(old,new,'writeoff')

# Inventory cannot be applied to virtual bundle stock.
s=s.replace("function doInventory(){let p=prod(document.getElementById('ip').value);if(!p)return;", "function doInventory(){let p=prod(document.getElementById('ip').value);if(!p)return;if(isBundleProduct(p))return alert('Набор не инвентаризируется отдельно: его остаток считается по компонентам.');",1)

# Marketplace delivery consumes bundle components, while reservation remains on bundle.
old="const stockBefore=Math.max(0,Number(p.stock)||0),fifo=fifoConsume(p.id,qty),shortage=Math.max(0,qty-stockBefore);p.stock=Math.max(0,stockBefore-qty);state.sales.push({id:id(),productId:p.id,qty,price:Number(o.unitPrice)||0,cost:fifo.unitCost,fee:apiFeePerUnit,feeSource:o.feeSource||'',channel:market,date:marketplaceSaleTimestamp(market,o),externalKey:scoped,fifoLots:fifo.lots,stockShortage:shortage});refreshProductAverageCost(p);log('продажа',p.id,-Math.min(qty,stockBefore),market+' '+(o.code||'')+(shortage?' · нехватка '+shortage+' шт.':''));soldCount+=qty"
new="const consumed=consumeSellableProduct(p,qty,market+' '+(o.code||''));state.sales.push({id:id(),productId:p.id,qty,price:Number(o.unitPrice)||0,cost:consumed.unitCost,fee:apiFeePerUnit,feeSource:o.feeSource||'',channel:market,date:marketplaceSaleTimestamp(market,o),externalKey:scoped,fifoLots:consumed.lots,stockShortage:consumed.shortage});if(isBundleProduct(p))p.cost=productDisplayCost(p);soldCount+=qty"
replace_once(old,new,'marketplace bundle sale')

# Product details display virtual stock, current component cost and composition.
i,j,op=cut('function openProduct(pid,market=\'\',days=30){','function deleteProduct(pid)')
if 'bundleBlock=' not in op:
    op=op.replace("let p=prod(pid);if(!p)return;", "let p=prod(pid);if(!p)return;const displayStock=productDisplayStock(p),displayCost=productDisplayCost(p),bundleBlock=isBundleProduct(p)?`<div class=\\\"item\\\" style=\\\"margin-top:8px\\\"><b>Состав набора</b>${bundleComponents(p).map(x=>`<div class=\\\"row\\\" style=\\\"margin-top:8px\\\"><div class=\\\"grow\\\">${esc(productNameById(x.productId,'Удалённый товар'))}</div><b>× ${x.qty}</b></div>`).join('')}<div class=\\\"muted\\\" style=\\\"margin-top:9px\\\">Доступно наборов: ${displayStock}. Остаток считается по самому дефицитному компоненту с учётом активных резервов.</div></div>`:'';")
    op=op.replace('${p.stock} шт.','${displayStock} ${isBundleProduct(p)?\'набор.\':\'шт.\'}',1)
    op=op.replace('${fmt(p.cost)}','${fmt(displayCost)}',1)
    anchor='<div class="item" style="margin-top:8px"><b>Артикулы маркетплейсов</b>'
    op=op.replace(anchor,'${bundleBlock}'+anchor,1)
    s=s[:i]+op+s[j:]

# Prevent deleting a physical component while any active bundle depends on it.
needle="function deleteProduct(pid){const p=prod(pid);if(!p)return;const active=reserved(p);"
replacement="function deleteProduct(pid){const p=prod(pid);if(!p)return;const usedBy=(state.products||[]).filter(x=>x.id!==p.id&&isBundleProduct(x)&&bundleComponents(x).some(c=>c.productId===p.id));if(usedBy.length)return alert('Нельзя удалить товар: он используется в наборе «'+usedBy[0].name+'». Сначала измените состав набора.');const active=reserved(p);"
replace_once(needle,replacement,'delete bundle component guard')

required=[
 'function isBundleProduct(p)', 'function bundleAvailableStock(p)', 'function consumeSellableProduct(p,qty',
 'Тип товара', 'Набор', 'Состав набора', 'function readBundleComponents(',
 "kind==='bundle'", 'productAvailableStock(p)', 'набор «',
 "Набор не инвентаризируется отдельно", "он используется в наборе"
]
missing=[x for x in required if x not in s]
if missing: raise SystemExit('Bundle markers missing: '+', '.join(missing))

p.write_text(s,encoding='utf-8')
print('Product bundles added with virtual stock, reservation propagation and component FIFO consumption.')
