from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')

def rep(old, new, label):
    global s
    c = s.count(old)
    if c != 1:
        raise SystemExit(f'{label}: marker count={c}')
    s = s.replace(old, new, 1)

rep(
    '''function renderPurchases(){const groups=purchaseShipmentGroups(),toForwarder=groups.filter(g=>g.status==='to_forwarder'),toMe=groups.filter(g=>g.status==='to_me'),received=groups.filter(g=>g.status==='received'),sumQty=a=>a.reduce((n,g)=>n+purchaseShipmentTotals(g).qty,0),inTransit=[...toForwarder,...toMe],inTransitValue=inTransit.reduce((n,g)=>n+purchaseShipmentTotals(g).buy,0),since=reportPeriodStart(30),received30=received.filter(g=>Number(g.receivedAt)>=since);const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('pToForwarder',sumQty(toForwarder).toLocaleString('ru-RU')+' шт.');set('pToMe',sumQty(toMe).toLocaleString('ru-RU')+' шт.');set('pInTransitValue',fmt(inTransitValue));set('pReceived30',sumQty(received30).toLocaleString('ru-RU')+' шт.');const list=document.getElementById('purchaseList');if(!list)return;if(!groups.length){list.innerHTML='<div class="empty">Закупок пока нет</div>';return}list.innerHTML=groups.map(g=>{const t=purchaseShipmentTotals(g),status=g.status,label=status==='to_forwarder'?'К доставщику':status==='to_me'?'Едет ко мне':'Получено',badge=status==='to_me'?'purple':status==='received'?'':'',date=status==='received'?g.receivedAt:status==='to_me'?g.forwarderReceivedAt:g.orderedAt,dateLabel=status==='received'?'Получено':status==='to_me'?'У доставщика с':'Заказано',lines=g.rows.map(x=>`<div class="purchase-line"><div class="grow"><b>${esc(prod(x.productId)?.name||'—')}</b><div class="muted">${Number(x.qty)||0} шт. · закуп ${fmt(Number(x.buyTotal)||((Number(x.unitCost)||0)*(Number(x.qty)||0)))}</div></div>${status==='received'?`<div class="right"><div class="muted">себестоимость</div><b>${fmt(x.landedUnitCost)}/шт.</b></div>`:''}</div>`).join(''),action=status==='to_forwarder'?`<button class="btn dark full" onclick="advancePurchaseShipment('${encodeURIComponent(g.key)}')">Доставщик получил</button>`:status==='to_me'?`<button class="btn dark full" onclick="openReceivePurchaseShipment('${encodeURIComponent(g.key)}')">Получить поставку</button>`:'';return `<div class="item purchase-card ${status==='to_me'?'to-me':status==='received'?'received':'to-forwarder'}"><div class="order-head"><div class="grow"><div class="name">${esc(g.batch||'Поставка')}</div><div class="muted">${dateLabel}: ${date?new Date(date).toLocaleDateString('ru-RU'):'—'} · ${g.rows.length} поз. · ${t.qty} шт.</div></div><span class="badge ${badge}">${label}</span></div><div class="muted" style="margin-top:7px">Закупка: ${fmt(t.buy)}${status==='received'?' · доставка: '+fmt(t.delivery):''}</div><div class="purchase-lines">${lines}</div>${action}</div>`}).join('')}''',
    '''function renderPurchases(){const groups=purchaseShipmentGroups(),toForwarder=groups.filter(g=>g.status==='to_forwarder'),toMe=groups.filter(g=>g.status==='to_me'),received=groups.filter(g=>g.status==='received'),sumQty=a=>a.reduce((n,g)=>n+purchaseShipmentTotals(g).qty,0),inTransit=[...toForwarder,...toMe],inTransitValue=inTransit.reduce((n,g)=>{const t=purchaseShipmentTotals(g);return n+t.buy+t.delivery},0),since=reportPeriodStart(30),received30=received.filter(g=>Number(g.receivedAt)>=since);const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('pToForwarder',sumQty(toForwarder).toLocaleString('ru-RU')+' шт.');set('pToMe',sumQty(toMe).toLocaleString('ru-RU')+' шт.');set('pInTransitValue',fmt(inTransitValue));set('pReceived30',sumQty(received30).toLocaleString('ru-RU')+' шт.');const list=document.getElementById('purchaseList');if(!list)return;if(!groups.length){list.innerHTML='<div class="empty">Закупок пока нет</div>';return}list.innerHTML=groups.map(g=>{const t=purchaseShipmentTotals(g),status=g.status,label=status==='to_forwarder'?'К доставщику':status==='to_me'?'Едет ко мне':'Получено',badge=status==='to_me'?'purple':status==='received'?'':'',date=status==='received'?g.receivedAt:status==='to_me'?g.forwarderReceivedAt:g.orderedAt,dateLabel=status==='received'?'Получено':status==='to_me'?'У доставщика с':'Заказано',lines=g.rows.map(x=>{const qty=Number(x.qty)||0,buy=Number(x.buyTotal)||((Number(x.unitCost)||0)*qty),unitBuy=qty?buy/qty:0;return `<div class="purchase-line"><div class="grow"><b>${esc(prod(x.productId)?.name||'—')}</b><div class="muted">${qty} шт. · закуп ${fmt(unitBuy)}/шт.</div></div>${status==='received'?`<div class="right"><div class="muted">себестоимость</div><b>${fmt(x.landedUnitCost)}/шт.</b></div>`:''}</div>`}).join(''),action=status==='to_forwarder'?`<button class="btn dark full" onclick="advancePurchaseShipment('${encodeURIComponent(g.key)}')">Доставщик получил</button>`:status==='to_me'?`<button class="btn dark full" onclick="openReceivePurchaseShipment('${encodeURIComponent(g.key)}')">Получить поставку</button>`:'';return `<div class="item purchase-card ${status==='to_me'?'to-me':status==='received'?'received':'to-forwarder'}"><div class="order-head"><div class="grow"><div class="name">${esc(g.batch||'Поставка')}</div><div class="muted">${dateLabel}: ${date?new Date(date).toLocaleDateString('ru-RU'):'—'} · ${g.rows.length} поз. · ${t.qty} шт.</div></div><span class="badge ${badge}">${label}</span></div><div class="muted" style="margin-top:7px">Закупка: ${fmt(t.buy)} · доставка: ${fmt(t.delivery)} · всего: ${fmt(t.buy+t.delivery)}</div><div class="purchase-lines">${lines}</div>${action}</div>`}).join('')}''',
    'render purchases totals',
)

rep(
    '''function purchaseForm(){return `<h3>Новая закупка</h3><div class="link-note">Новая закупка сначала попадает в статус «К доставщику». Остаток склада не меняется. Когда доставщик получит товары, переведите поставку в «Едет ко мне». Только после фактического получения поставка станет приходом на склад.</div><div class="field"><label>Дата заказа</label><input id="porDate" type="date" value="${localDateInputValue()}"></div><div class="field"><label>Название / партия</label><input id="porBatch" placeholder="Например: Китай 11.08"></div><div id="purchaseItems"></div><button type="button" class="btn full" onclick="addPurchaseItem()">+ Добавить товар</button><div id="purchaseOrderCalc" class="link-note"></div><button class="btn dark full" onclick="createPurchaseOrder()">Сохранить закупку</button>`}''',
    '''function purchaseForm(){return `<h3>Новая закупка</h3><div class="link-note">Укажите одной суммой весь платёж за товары. Он автоматически распределится между выбранными товарами по количеству. Доставку можно указать сразу, если она уже известна, либо оставить 0 и изменить при получении.</div><div class="field"><label>Дата заказа</label><input id="porDate" type="date" value="${localDateInputValue()}"></div><div class="field"><label>Название / партия</label><input id="porBatch" placeholder="Например: Китай 11.08"></div><div class="two"><div class="field"><label>Общая сумма закупки ₸</label><input id="porBuyTotal" type="number" min="0" value="0" oninput="updatePurchaseOrderCalculator()"></div><div class="field"><label>Доставка ₸</label><input id="porDelivery" type="number" min="0" value="0" oninput="updatePurchaseOrderCalculator()"></div></div><div id="purchaseItems"></div><button type="button" class="btn full" onclick="addPurchaseItem()">+ Добавить товар</button><div id="purchaseOrderCalc" class="link-note"></div><button class="btn dark full" onclick="createPurchaseOrder()">Сохранить закупку</button>`}''',
    'purchase form totals',
)

rep(
    '''function addPurchaseItem(selected=''){const box=document.getElementById('purchaseItems');if(!box)return;const wrap=document.createElement('div');wrap.className='item purchase-item';wrap.style.marginBottom='9px';wrap.innerHTML=`<div class="field"><label>Поиск товара</label><input class="purchase-q" autocomplete="off" placeholder="Название или артикул" oninput="filterPurchaseProducts(this)"></div><div class="field"><label>Товар</label><select class="purchase-product">${arrivalProductOptions(selected)}</select></div><div class="two"><div class="field"><label>Количество</label><input class="purchase-qty" type="number" min="1" oninput="updatePurchaseOrderCalculator()"></div><div class="field"><label>Сумма закупки ₸</label><input class="purchase-buy" type="number" min="0" oninput="updatePurchaseOrderCalculator()"></div></div><button type="button" class="btn danger full" onclick="removePurchaseItem(this)">Убрать товар</button>`;box.appendChild(wrap);updatePurchaseOrderCalculator();setTimeout(()=>wrap.querySelector('.purchase-q')?.focus(),0)}''',
    '''function addPurchaseItem(selected=''){const box=document.getElementById('purchaseItems');if(!box)return;const wrap=document.createElement('div');wrap.className='item purchase-item';wrap.style.marginBottom='9px';wrap.innerHTML=`<div class="field"><label>Поиск товара</label><input class="purchase-q" autocomplete="off" placeholder="Название или артикул" oninput="filterPurchaseProducts(this)"></div><div class="field"><label>Товар</label><select class="purchase-product">${arrivalProductOptions(selected)}</select></div><div class="field"><label>Количество</label><input class="purchase-qty" type="number" min="1" oninput="updatePurchaseOrderCalculator()"></div><button type="button" class="btn danger full" onclick="removePurchaseItem(this)">Убрать товар</button>`;box.appendChild(wrap);updatePurchaseOrderCalculator();setTimeout(()=>wrap.querySelector('.purchase-q')?.focus(),0)}''',
    'purchase item quantity only',
)

rep(
    '''function purchaseDraftRows(){return [...document.querySelectorAll('.purchase-item')].map(row=>({productId:row.querySelector('.purchase-product')?.value||'',qty:Math.max(0,Number(row.querySelector('.purchase-qty')?.value)||0),buy:Math.max(0,Number(row.querySelector('.purchase-buy')?.value)||0)}))}''',
    '''function purchaseDraftRows(){return [...document.querySelectorAll('.purchase-item')].map(row=>({productId:row.querySelector('.purchase-product')?.value||'',qty:Math.max(0,Number(row.querySelector('.purchase-qty')?.value)||0)}))}''',
    'purchase draft rows',
)

rep(
    '''function updatePurchaseOrderCalculator(){const rows=purchaseDraftRows().filter(x=>x.productId&&x.qty>0),qty=rows.reduce((a,x)=>a+x.qty,0),buy=rows.reduce((a,x)=>a+x.buy,0),box=document.getElementById('purchaseOrderCalc');if(box)box.innerHTML=`<b>Закупка</b><div style="margin-top:6px">Позиций: ${rows.length} · товаров: ${qty} шт.</div><div><b>Вложено в товар: ${fmt(buy)}</b></div>`}''',
    '''function updatePurchaseOrderCalculator(){const rows=purchaseDraftRows().filter(x=>x.productId&&x.qty>0),qty=rows.reduce((a,x)=>a+x.qty,0),buy=Math.max(0,Number(document.getElementById('porBuyTotal')?.value)||0),delivery=Math.max(0,Number(document.getElementById('porDelivery')?.value)||0),unit=qty?buy/qty:0,box=document.getElementById('purchaseOrderCalc');if(box)box.innerHTML=`<b>Закупка</b><div style="margin-top:6px">Позиций: ${rows.length} · товаров: ${qty} шт.</div><div>Общая закупка: ${fmt(buy)} · доставка: ${fmt(delivery)}</div><div>Закупочная цена: ${fmt(unit)}/шт.</div><div><b>Всего оплачено: ${fmt(buy+delivery)}</b></div>`}''',
    'purchase calculator totals',
)

rep(
    '''function createPurchaseOrder(){const rows=purchaseDraftRows(),valid=rows.filter(x=>x.productId&&x.qty>0),orderedAt=localDateStart(document.getElementById('porDate')?.value),batch=(document.getElementById('porBatch')?.value||'').trim();if(!valid.length)return alert('Добавьте хотя бы один товар и количество');if(valid.some(x=>!prod(x.productId)))return alert('Проверьте выбранные товары');const ids=valid.map(x=>x.productId);if(new Set(ids).size!==ids.length)return alert('Один и тот же товар добавлен несколько раз. Объедините количество в одну строку.');const shipmentId='po-'+id(),label=batch||('Китай '+new Date(orderedAt).toLocaleDateString('ru-RU')),totalBuy=valid.reduce((a,x)=>a+x.buy,0);for(const x of valid){state.purchases.unshift({id:id(),shipmentId,status:'to_forwarder',productId:x.productId,qty:x.qty,remainingQty:0,buyTotal:x.buy,unitCost:x.qty?x.buy/x.qty:0,delivery:0,landedUnitCost:0,batch:label,orderedAt,date:orderedAt,receivedAt:0,createdAt:Date.now(),shipmentPurchaseTotal:totalBuy})}save();closeModal();render();alert('Закупка создана. Товар пока едет к доставщику и в остаток склада не добавлен.')}''',
    '''function createPurchaseOrder(){const rows=purchaseDraftRows(),valid=rows.filter(x=>x.productId&&x.qty>0),orderedAt=localDateStart(document.getElementById('porDate')?.value),batch=(document.getElementById('porBatch')?.value||'').trim(),totalBuy=Math.max(0,Number(document.getElementById('porBuyTotal')?.value)||0),totalDelivery=Math.max(0,Number(document.getElementById('porDelivery')?.value)||0);if(!valid.length)return alert('Добавьте хотя бы один товар и количество');if(valid.some(x=>!prod(x.productId)))return alert('Проверьте выбранные товары');const ids=valid.map(x=>x.productId);if(new Set(ids).size!==ids.length)return alert('Один и тот же товар добавлен несколько раз. Объедините количество в одну строку.');const totalQty=valid.reduce((a,x)=>a+x.qty,0),shipmentId='po-'+id(),label=batch||('Китай '+new Date(orderedAt).toLocaleDateString('ru-RU'));for(const x of valid){const share=totalQty>0?x.qty/totalQty:0,buyTotal=totalBuy*share,deliveryShare=totalDelivery*share;state.purchases.unshift({id:id(),shipmentId,status:'to_forwarder',productId:x.productId,qty:x.qty,remainingQty:0,buyTotal,unitCost:x.qty?buyTotal/x.qty:0,delivery:deliveryShare,landedUnitCost:0,batch:label,orderedAt,date:orderedAt,receivedAt:0,createdAt:Date.now(),shipmentPurchaseTotal:totalBuy,shipmentDeliveryTotal:totalDelivery})}save();closeModal();render();alert(`Закупка создана. Закупка: ${fmt(totalBuy)} · доставка: ${fmt(totalDelivery)}. Товар пока не добавлен в остаток склада.`)}''',
    'create purchase order totals',
)

rep(
    '''function openReceivePurchaseShipment(encodedKey){const rows=purchaseShipmentRows(encodedKey);if(!rows.length)return alert('Поставка не найдена');if(!rows.every(x=>purchaseStatus(x)==='to_me'))return alert('Получить можно только поставку в статусе «Едет ко мне».');const g={rows},t=purchaseShipmentTotals(g),key=encodeURIComponent(String(rows[0].shipmentId||rows[0].id||''));showSheet(`<h3>Получить поставку</h3><div class="item"><b>${esc(rows[0].batch||'Поставка')}</b><div class="muted">${rows.length} поз. · ${t.qty} шт. · закупка ${fmt(t.buy)}</div></div><div class="field"><label>Дата получения</label><input id="receivePurchaseDate" type="date" value="${localDateInputValue()}"></div><div class="field"><label>Доставка всей поставки ₸</label><input id="receivePurchaseDelivery" type="number" min="0" value="0"></div><div class="link-note">После подтверждения товар будет добавлен на склад. Доставка распределится по товарам пропорционально сумме закупки, а если закупка нулевая — пропорционально количеству.</div><button class="btn dark full" onclick="receivePurchaseShipment('${key}')">Оприходовать на склад</button>`)}''',
    '''function openReceivePurchaseShipment(encodedKey){const rows=purchaseShipmentRows(encodedKey);if(!rows.length)return alert('Поставка не найдена');if(!rows.every(x=>purchaseStatus(x)==='to_me'))return alert('Получить можно только поставку в статусе «Едет ко мне».');const g={rows},t=purchaseShipmentTotals(g),key=encodeURIComponent(String(rows[0].shipmentId||rows[0].id||'')),deliveryValue=Math.round(t.delivery*100)/100;showSheet(`<h3>Получить поставку</h3><div class="item"><b>${esc(rows[0].batch||'Поставка')}</b><div class="muted">${rows.length} поз. · ${t.qty} шт. · закупка ${fmt(t.buy)} · доставка ${fmt(t.delivery)}</div></div><div class="field"><label>Дата получения</label><input id="receivePurchaseDate" type="date" value="${localDateInputValue()}"></div><div class="field"><label>Доставка всей поставки ₸</label><input id="receivePurchaseDelivery" type="number" min="0" value="${deliveryValue}"></div><div class="link-note">Если доставку указали ещё при закупке, она уже подставлена. Здесь её можно изменить на фактическую сумму. После подтверждения товар будет добавлен на склад, а доставка войдёт в себестоимость.</div><button class="btn dark full" onclick="receivePurchaseShipment('${key}')">Оприходовать на склад</button>`)}''',
    'receive purchase delivery prefill',
)

p.write_text(s, encoding='utf-8')
