from pathlib import Path

PATH = Path('index.html')
html = PATH.read_text(encoding='utf-8')


def once(old: str, new: str, label: str):
    global html
    n = html.count(old)
    if n != 1:
        raise SystemExit(f'{label}: expected 1 match, got {n}')
    html = html.replace(old, new, 1)


once('<div class="label">Чистая прибыль</div><div class="num" id="mProfit">0 ₸</div>',
     '<div class="label">Прибыль</div><div class="num" id="mProfit">0 ₸</div>',
     'dashboard profit label')
once('<div class="label">Чистая прибыль</div><div class="num" id="rProfit">0 ₸</div>',
     '<div class="label">Прибыль</div><div class="num" id="rProfit">0 ₸</div>',
     'report profit label')

old_helpers = "function stockTotal(){return state.products.reduce((a,p)=>a+p.stock,0)}function reserved(p){return state.reservations.filter(r=>r.productId===p.id&&r.active).reduce((a,r)=>a+r.qty,0)}function salesDays(p,days=30){let since=Date.now()-days*86400000;return state.sales.filter(s=>s.productId===p.id&&s.date>=since).reduce((a,s)=>a+s.qty,0)/days}function costOf(p){return p.cost||0}function log(type,pid,qty,extra=''){state.movements.unshift({id:id(),date:Date.now(),type,productId:pid,qty,extra});state.movements=state.movements.slice(0,1000)}"
new_helpers = """function stockTotal(){return state.products.reduce((a,p)=>a+(Number(p.stock)||0),0)}
function reserved(p){return state.reservations.filter(r=>r.productId===p.id&&r.active).reduce((a,r)=>a+(Number(r.qty)||0),0)}
function isCompletedOrder(market,status){const s=String(status||'').toUpperCase();return market==='WB'?['COMPLETE','COMPLETED'].includes(s):s==='COMPLETED'}
function financialSales(){const result=[...(state.sales||[])],seen=new Set(result.map(s=>s.externalKey).filter(Boolean));for(const [market,feed] of [['Kaspi',state.kaspiOrderFeed],['WB',state.wbOrderFeed],['Ozon',state.ozonOrderFeed]]){for(const o of(feed||[])){if(!isCompletedOrder(market,o.status)||!o.productId)continue;const key=String(o.orderId)+':'+String(o.entryId);if(seen.has(key))continue;const p=prod(o.productId);if(!p)continue;const qty=Math.max(0,Number(o.qty)||0);if(!qty)continue;const total=Number(o.totalPrice)||0;const price=Number(o.unitPrice)||(total/qty)||0;result.push({id:'virtual-'+market+'-'+key,productId:p.id,qty,price,cost:Number(p.cost)||0,fee:0,channel:market,date:toTimestamp(o.creationDate),externalKey:key,virtual:true});seen.add(key)}}return result}
function salesDays(p,days=30){let since=Date.now()-days*86400000;return financialSales().filter(s=>s.productId===p.id&&s.date>=since).reduce((a,s)=>a+(Number(s.qty)||0),0)/days}
function profitForProduct(p,days=30){let since=Date.now()-days*86400000;return financialSales().filter(s=>s.productId===p.id&&s.date>=since).reduce((a,s)=>a+(Number(s.qty)||0)*((Number(s.price)||0)-(Number(s.cost)||0)-(Number(s.fee)||0)),0)}
function costOf(p){return Number(p.cost)||0}
function log(type,pid,qty,extra=''){state.movements.unshift({id:id(),date:Date.now(),type,productId:pid,qty,extra});state.movements=state.movements.slice(0,1000)}"""
once(old_helpers, new_helpers, 'financial helpers')

once("  let ss=state.sales.filter(s=>s.date>=since);", "  let ss=financialSales().filter(s=>s.date>=since);", 'dashboard financial sales')

old_products = "a.sort((x,y)=>s==='name'?x.name.localeCompare(y.name):s==='stock'?y.stock-x.stock:s==='sales'?salesDays(y)-salesDays(x):s==='profit'?(y.totalProfit||0)-(x.totalProfit||0):salesDays(x)?x.stock/salesDays(x)-y.stock/salesDays(y):0);"
new_products = "a.sort((x,y)=>s==='name'?x.name.localeCompare(y.name):s==='stock'?y.stock-x.stock:s==='sales'?salesDays(y)-salesDays(x):s==='profit'?profitForProduct(y)-profitForProduct(x):salesDays(x)?x.stock/salesDays(x)-y.stock/salesDays(y):0);"
once(old_products, new_products, 'product profit sorting')

old_card = "function productCard(p){let r=reserved(p),d=salesDays(p);return `<div class=\"item row\" onclick=\"openProduct('${p.id}')\">${p.photo?`<img class=\"thumb\" src=\"${p.photo}\">`:'<div class=\"thumb\">Фото</div>'}<div class=\"grow\"><div class=\"name\">${esc(p.name)}</div><div class=\"muted\">${esc(p.category||'Без категории')}</div><div class=\"muted\">Продажи/день: ${d.toFixed(1)} · Запас: ${d?(p.stock/d).toFixed(1):'∞'} дн.</div><div class=\"muted\">Себестоимость: ${fmt(p.cost)}</div></div><div class=\"right\"><b>${p.stock}</b><div class=\"muted\">шт.</div>${r?`<div class=\"badge\">резерв ${r}</div>`:''}</div></div>`}"
new_card = "function productCard(p){let r=reserved(p),d=salesDays(p),profit=profitForProduct(p);return `<div class=\"item row\" onclick=\"openProduct('${p.id}')\">${p.photo?`<img class=\"thumb\" src=\"${p.photo}\">`:'<div class=\"thumb\">Фото</div>'}<div class=\"grow\"><div class=\"name\">${esc(p.name)}</div><div class=\"muted\">${esc(p.category||'Без категории')}</div><div class=\"muted\">Продажи/день: ${d.toFixed(1)} · Запас: ${d?(p.stock/d).toFixed(1):'∞'} дн.</div><div class=\"muted\">Себестоимость: ${fmt(p.cost)} · Прибыль 30д: ${fmt(profit)}</div></div><div class=\"right\"><b>${p.stock}</b><div class=\"muted\">шт.</div>${r?`<div class=\"badge\">резерв ${r}</div>`:''}</div></div>`}"
once(old_card, new_card, 'product card')

old_reports = "function renderReports(){let since=Date.now()-30*86400000,ss=state.sales.filter(s=>s.date>=since),rev=ss.reduce((a,s)=>a+s.qty*s.price,0),cost=ss.reduce((a,s)=>a+s.qty*s.cost,0),fees=ss.reduce((a,s)=>a+s.qty*s.fee,0);document.getElementById('rRevenue').textContent=fmt(rev);document.getElementById('rCost').textContent=fmt(cost);document.getElementById('rFees').textContent=fmt(fees);document.getElementById('rProfit').textContent=fmt(rev-cost-fees);let names=['Kaspi','WB','Ozon','Ручная'];document.getElementById('mpReport').innerHTML=names.map(n=>{let a=ss.filter(s=>s.channel===n);return `<div class=\"item row\"><div class=\"grow\"><b>${n}</b><div class=\"muted\">${a.reduce((x,s)=>x+s.qty,0)} шт.</div></div><b>${fmt(a.reduce((x,s)=>x+s.qty*s.price,0))}</b></div>`}).join('')}"
new_reports = "function renderReports(){let since=Date.now()-selectedPeriod*86400000,ss=financialSales().filter(s=>s.date>=since),rev=ss.reduce((a,s)=>a+(Number(s.qty)||0)*(Number(s.price)||0),0),cost=ss.reduce((a,s)=>a+(Number(s.qty)||0)*(Number(s.cost)||0),0),fees=ss.reduce((a,s)=>a+(Number(s.qty)||0)*(Number(s.fee)||0),0);document.getElementById('rRevenue').textContent=fmt(rev);document.getElementById('rCost').textContent=fmt(cost);document.getElementById('rFees').textContent=fmt(fees);document.getElementById('rProfit').textContent=fmt(rev-cost-fees);let names=['Kaspi','WB','Ozon','Ручная'];document.getElementById('mpReport').innerHTML=names.map(n=>{let a=ss.filter(s=>s.channel===n),channelRev=a.reduce((x,s)=>x+(Number(s.qty)||0)*(Number(s.price)||0),0),channelProfit=a.reduce((x,s)=>x+(Number(s.qty)||0)*((Number(s.price)||0)-(Number(s.cost)||0)-(Number(s.fee)||0)),0);return `<div class=\"item row\"><div class=\"grow\"><b>${n}</b><div class=\"muted\">${a.reduce((x,s)=>x+(Number(s.qty)||0),0)} шт. · прибыль ${fmt(channelProfit)}</div></div><b>${fmt(channelRev)}</b></div>`}).join('')}"
once(old_reports, new_reports, 'reports')

old_open = "function openProduct(pid){let p=prod(pid),r=reserved(p);let s=`<h3>${esc(p.name)}</h3><div class=\"item\"><div class=\"row\"><div class=\"grow\"><b>Остаток</b><div class=\"muted\">Резерв: ${r} · Свободно: ${p.stock-r}</div></div><b>${p.stock} шт.</b></div></div><div class=\"item\" style=\"margin-top:8px\"><b>Артикулы</b><div class=\"muted\">Kaspi: ${esc(p.kaspi||'—')} · WB: ${esc(p.wb||'—')} · Ozon: ${esc(p.ozon||'—')}</div></div><button class=\"btn dark full\" onclick=\"closeModal();openModal('edit','${pid}')\">Редактировать товар</button><button class=\"btn full\" onclick=\"closeModal();openModal('writeoff','${pid}')\">Списать</button><button class=\"btn full\" onclick=\"closeModal();openModal('inventory','${pid}')\">Инвентаризация</button>`;showSheet(s)}"
new_open = "function openProduct(pid){let p=prod(pid),r=reserved(p),profit=profitForProduct(p),value=(Number(p.stock)||0)*(Number(p.cost)||0);let s=`<h3>${esc(p.name)}</h3><div class=\"item\"><div class=\"row\"><div class=\"grow\"><b>Остаток</b><div class=\"muted\">Резерв: ${r} · Свободно: ${p.stock-r}</div></div><b>${p.stock} шт.</b></div><div class=\"muted\" style=\"margin-top:7px\">Себестоимость: ${fmt(p.cost)} / шт. · Стоимость остатка: ${fmt(value)} · Прибыль 30д: ${fmt(profit)}</div></div><div class=\"item\" style=\"margin-top:8px\"><b>Артикулы</b><div class=\"muted\">Kaspi: ${esc(p.kaspi||'—')} · WB: ${esc(p.wb||'—')} · Ozon: ${esc(p.ozon||'—')}</div></div><button class=\"btn dark full\" onclick=\"closeModal();openModal('edit','${pid}')\">Редактировать товар</button><button class=\"btn full\" onclick=\"closeModal();openModal('writeoff','${pid}')\">Списать</button><button class=\"btn full\" onclick=\"closeModal();openModal('inventory','${pid}')\">Инвентаризация</button>`;showSheet(s)}"
once(old_open, new_open, 'product details')

old_product_form = "function productForm(){return `<h3>Добавить товар</h3><div class=\"field\"><label>Название</label><input id=\"pn\"></div><div class=\"field\"><label>Категория</label><input id=\"pc\"></div><div class=\"field\"><label>Фото (URL)</label><input id=\"pp\" placeholder=\"Можно добавить позже\"></div><div class=\"two\"><div class=\"field\"><label>Kaspi артикул</label><input id=\"pk\"></div><div class=\"field\"><label>WB артикул</label><input id=\"pw\"></div></div><div class=\"field\"><label>Ozon артикул</label><input id=\"po\"></div><div class=\"field\"><label>Минимальный остаток</label><input id=\"pmin\" type=\"number\" value=\"0\"></div><button class=\"btn dark full\" onclick=\"createProduct()\">Создать</button>`}"
new_product_form = "function productForm(){return `<h3>Добавить товар</h3><div class=\"field\"><label>Название</label><input id=\"pn\"></div><div class=\"field\"><label>Категория</label><input id=\"pc\"></div><div class=\"field\"><label>Фото (URL)</label><input id=\"pp\" placeholder=\"Можно добавить позже\"></div><div class=\"two\"><div class=\"field\"><label>Kaspi артикул</label><input id=\"pk\"></div><div class=\"field\"><label>WB артикул</label><input id=\"pw\"></div></div><div class=\"field\"><label>Ozon артикул</label><input id=\"po\"></div><div class=\"two\"><div class=\"field\"><label>Себестоимость / шт. ₸</label><input id=\"pcost\" type=\"number\" min=\"0\" value=\"0\"></div><div class=\"field\"><label>Начальный остаток</label><input id=\"pstock\" type=\"number\" value=\"0\"></div></div><div class=\"field\"><label>Минимальный остаток</label><input id=\"pmin\" type=\"number\" value=\"0\"></div><button class=\"btn dark full\" onclick=\"createProduct()\">Создать</button>`}"
once(old_product_form, new_product_form, 'product form')

old_edit_form = "function editProductForm(pid){let p=prod(pid);return `<h3>Редактировать товар</h3><div class=\"field\"><label>Название</label><input id=\"en\" value=\"${esc(p.name)}\"></div><div class=\"field\"><label>Категория</label><input id=\"ec\" value=\"${esc(p.category||'')}\"></div><div class=\"field\"><label>Фото (URL)</label><input id=\"ep\" value=\"${esc(p.photo||'')}\"></div><div class=\"two\"><div class=\"field\"><label>Kaspi артикул</label><input id=\"ek\" value=\"${esc(p.kaspi||'')}\"></div><div class=\"field\"><label>WB артикул</label><input id=\"ew\" value=\"${esc(p.wb||'')}\"></div></div><div class=\"field\"><label>Ozon артикул</label><input id=\"eo\" value=\"${esc(p.ozon||'')}\"></div><div class=\"field\"><label>Минимальный остаток</label><input id=\"emin\" type=\"number\" value=\"${p.min||0}\"></div><button class=\"btn dark full\" onclick=\"saveProductEdit('${pid}')\">Сохранить изменения</button>`}"
new_edit_form = "function editProductForm(pid){let p=prod(pid);return `<h3>Редактировать товар</h3><div class=\"field\"><label>Название</label><input id=\"en\" value=\"${esc(p.name)}\"></div><div class=\"field\"><label>Категория</label><input id=\"ec\" value=\"${esc(p.category||'')}\"></div><div class=\"field\"><label>Фото (URL)</label><input id=\"ep\" value=\"${esc(p.photo||'')}\"></div><div class=\"two\"><div class=\"field\"><label>Kaspi артикул</label><input id=\"ek\" value=\"${esc(p.kaspi||'')}\"></div><div class=\"field\"><label>WB артикул</label><input id=\"ew\" value=\"${esc(p.wb||'')}\"></div></div><div class=\"field\"><label>Ozon артикул</label><input id=\"eo\" value=\"${esc(p.ozon||'')}\"></div><div class=\"two\"><div class=\"field\"><label>Себестоимость / шт. ₸</label><input id=\"ecost\" type=\"number\" min=\"0\" value=\"${Number(p.cost)||0}\"></div><div class=\"field\"><label>Минимальный остаток</label><input id=\"emin\" type=\"number\" value=\"${p.min||0}\"></div></div><div class=\"muted\">Остаток меняется через «Приход» или «Инвентаризация», чтобы сохранялась история движений.</div><button class=\"btn dark full\" onclick=\"saveProductEdit('${pid}')\">Сохранить изменения</button>`}"
once(old_edit_form, new_edit_form, 'edit form')

old_save_edit = "function saveProductEdit(pid){let p=prod(pid);if(!p)return;let n=document.getElementById('en').value.trim();if(!n)return alert('Введите название');p.name=n;p.category=document.getElementById('ec').value;p.photo=document.getElementById('ep').value;p.kaspi=document.getElementById('ek').value;p.wb=document.getElementById('ew').value;p.ozon=document.getElementById('eo').value;p.min=+document.getElementById('emin').value||0;save();closeModal();render()}"
new_save_edit = "function saveProductEdit(pid){let p=prod(pid);if(!p)return;let n=document.getElementById('en').value.trim();if(!n)return alert('Введите название');p.name=n;p.category=document.getElementById('ec').value;p.photo=document.getElementById('ep').value;p.kaspi=document.getElementById('ek').value;p.wb=document.getElementById('ew').value;p.ozon=document.getElementById('eo').value;p.cost=Math.max(0,+document.getElementById('ecost').value||0);p.min=Math.max(0,+document.getElementById('emin').value||0);save();closeModal();render()}"
once(old_save_edit, new_save_edit, 'save edit')

old_create = "function createProduct(){let n=document.getElementById('pn').value.trim();if(!n)return alert('Введите название');state.products.push({id:id(),name:n,category:document.getElementById('pc').value,photo:document.getElementById('pp').value,kaspi:document.getElementById('pk').value,wb:document.getElementById('pw').value,ozon:document.getElementById('po').value,min:+document.getElementById('pmin').value||0,stock:0,cost:0,totalProfit:0});save();closeModal();render()}"
new_create = "function createProduct(){let n=document.getElementById('pn').value.trim();if(!n)return alert('Введите название');const p={id:id(),name:n,category:document.getElementById('pc').value,photo:document.getElementById('pp').value,kaspi:document.getElementById('pk').value,wb:document.getElementById('pw').value,ozon:document.getElementById('po').value,min:Math.max(0,+document.getElementById('pmin').value||0),stock:+document.getElementById('pstock').value||0,cost:Math.max(0,+document.getElementById('pcost').value||0),totalProfit:0};state.products.push(p);if(p.stock)log('инвентаризация',p.id,p.stock,'начальный остаток');save();closeModal();render()}"
once(old_create, new_create, 'create product')

old_arrival = "function createArrival(){let p=prod(document.getElementById('ap').value),q=+document.getElementById('aq').value||0,c=+document.getElementById('ac').value||0,d=+document.getElementById('ad').value||0,b=document.getElementById('ab').value||'';if(!p||q<=0)return alert('Проверьте данные');let old=p.stock,total=p.cost*old+c*q+d;p.stock+=q;p.cost=p.stock?total/p.stock:0;state.purchases.unshift({id:id(),productId:p.id,qty:q,unitCost:c,delivery:d,batch:b,date:Date.now()});log('приход',p.id,q,`партия ${b}`);save();closeModal();render()}"
new_arrival = "function createArrival(){let p=prod(document.getElementById('ap').value),q=+document.getElementById('aq').value||0,c=Math.max(0,+document.getElementById('ac').value||0),d=Math.max(0,+document.getElementById('ad').value||0),b=document.getElementById('ab').value||'';if(!p||q<=0)return alert('Проверьте данные');const oldQty=Math.max(0,Number(p.stock)||0),newPositiveQty=oldQty+q,total=(Number(p.cost)||0)*oldQty+c*q+d;p.stock=(Number(p.stock)||0)+q;if(newPositiveQty>0)p.cost=total/newPositiveQty;state.purchases.unshift({id:id(),productId:p.id,qty:q,unitCost:c,delivery:d,batch:b,date:Date.now()});log('приход',p.id,q,`партия ${b}`);save();closeModal();render()}"
once(old_arrival, new_arrival, 'arrival costing')

old_sale_form = "function saleForm(){let opts=state.products.map(p=>`<option value=\"${p.id}\">${esc(p.name)}</option>`).join('');return `<h3>Ручная продажа</h3><div class=\"field\"><label>Товар</label><select id=\"sp\">${opts}</select></div><div class=\"two\"><div class=\"field\"><label>Количество</label><input id=\"sq\" type=\"number\"></div><div class=\"field\"><label>Цена продажи/шт. ₸</label><input id=\"sprice\" type=\"number\"></div></div><button class=\"btn dark full\" onclick=\"createSale()\">Продать</button>`}"
new_sale_form = "function saleForm(){let opts=state.products.map(p=>`<option value=\"${p.id}\">${esc(p.name)}</option>`).join('');return `<h3>Ручная продажа</h3><div class=\"field\"><label>Товар</label><select id=\"sp\">${opts}</select></div><div class=\"two\"><div class=\"field\"><label>Количество</label><input id=\"sq\" type=\"number\"></div><div class=\"field\"><label>Цена продажи/шт. ₸</label><input id=\"sprice\" type=\"number\"></div></div><div class=\"field\"><label>Комиссия / расходы на 1 шт. ₸</label><input id=\"sfee\" type=\"number\" min=\"0\" value=\"0\"></div><button class=\"btn dark full\" onclick=\"createSale()\">Продать</button>`}"
once(old_sale_form, new_sale_form, 'sale form')

old_sale = "function createSale(){let p=prod(document.getElementById('sp').value),q=+document.getElementById('sq').value||0,price=+document.getElementById('sprice').value||0;if(!p||q<=0)return alert('Проверьте данные');p.stock-=q;let c=p.cost;state.sales.push({id:id(),productId:p.id,qty:q,price,cost:c,fee:0,channel:'Ручная',date:Date.now()});p.totalProfit=(p.totalProfit||0)+q*(price-c);log('продажа',p.id,-q);save();closeModal();render()}"
new_sale = "function createSale(){let p=prod(document.getElementById('sp').value),q=+document.getElementById('sq').value||0,price=Math.max(0,+document.getElementById('sprice').value||0),fee=Math.max(0,+document.getElementById('sfee').value||0);if(!p||q<=0)return alert('Проверьте данные');p.stock=(Number(p.stock)||0)-q;let c=Number(p.cost)||0;state.sales.push({id:id(),productId:p.id,qty:q,price,cost:c,fee,channel:'Ручная',date:Date.now()});p.totalProfit=(p.totalProfit||0)+q*(price-c-fee);log('продажа',p.id,-q);save();closeModal();render()}"
once(old_sale, new_sale, 'manual sale')

old_writeoff = "function createWriteoff(){let p=prod(document.getElementById('wp').value),q=+document.getElementById('wq').value||0,r=document.getElementById('wr').value;if(!p||q<=0)return alert('Проверьте данные');p.stock-=q;recalcCostAfterLoss(p,q);log('списание',p.id,-q,r);save();closeModal();render()}\nfunction recalcCostAfterLoss(p,q){if(p.stock>0)p.cost=p.cost*(p.stock+q)/p.stock}"
new_writeoff = "function createWriteoff(){let p=prod(document.getElementById('wp').value),q=+document.getElementById('wq').value||0,r=document.getElementById('wr').value;if(!p||q<=0)return alert('Проверьте данные');p.stock=(Number(p.stock)||0)-q;log('списание',p.id,-q,r);save();closeModal();render()}"
once(old_writeoff, new_writeoff, 'writeoff accounting')

old_inventory = "function doInventory(){let p=prod(document.getElementById('ip').value),actual=+document.getElementById('iq').value||0,delta=actual-p.stock;if(!p)return;let old=p.stock;p.stock=actual;if(delta<0)recalcCostAfterLoss(p,-delta);log('инвентаризация',p.id,delta,`было ${old}, стало ${actual}`);save();closeModal();render()}"
new_inventory = "function doInventory(){let p=prod(document.getElementById('ip').value);if(!p)return;let actual=+document.getElementById('iq').value||0,old=Number(p.stock)||0,delta=actual-old;p.stock=actual;log('инвентаризация',p.id,delta,`было ${old}, стало ${actual}`);save();closeModal();render()}"
once(old_inventory, new_inventory, 'inventory accounting')

if 'recalcCostAfterLoss(' in html:
    raise SystemExit('legacy recalcCostAfterLoss call/function remains')
for marker in ['id="pcost"', 'id="ecost"', 'function financialSales()', 'id="sfee"', 'Прибыль 30д']:
    if marker not in html:
        raise SystemExit(f'missing marker: {marker}')

PATH.write_text(html, encoding='utf-8')
print('Warehouse core upgrade applied')
